import {
  CONNECTION_DEFAULT_SETUP,
  SHORT_TEXT_DEFAULT_SETUP,
  MCQ_DEFAULT_SETUP,
  SIGNATURE_DEFAULT_SETUP,
  LONG_TEXT_DEFAULT_SETUP,
  EMAIL_DEFAULT_SETUP,
  PHONE_NUMBER_DEFAULT_SETUP,
  SCQ_DEFAULT_SETUP,
  ZIP_CODE_DEFAULT_SETUP,
  DROP_DOWN_DEFAULT_SETUP,
  DROP_DOWN_STATIC_DEFAULT_SETUP,
  YES_NO_DEFAULT_SETUP,
  RANKING_DEFAULT_SETUP,
  WELCOME_DEFAULT_SETUP,
  QUOTE_DEFAULT_SETUP,
  ENDING_DEFAULT_SETUP,
  DATE_DEFAULT_SETUP,
  KEY_VALUE_TABLE_DEFAULT_SETUP,
  NUMBER_DEFAULT_SETUP,
  FILE_PICKER_DEFAULT_SETUP,
  CURRENCY_DEFAULT_SETUP,
  TIME_DEFAULT_SETUP,
  LOADING_DEFAULT_SETUP,
  ADDRESS_DEFAULT_SETUP,
  PDF_VIEWER_DEFAULT_SETUP,
  TEXT_PREVIEW_DEFAULT_SETUP,
  AUTOCOMPLETE_DEFAULT_SETUP,
  QUESTIONS_GRID_DEFAULT_SETUP,
  PICTURE_DEFAULT_SETUP,
  MULTI_PAGE_QUESTION_DEFAULT_SETUP,
  QUESTION_REPEATOR_DEFAULT_SETUP,
  FORMULA_BAR_DEFAULT_SETUP,
  COLLECT_PAYMENT_DEFAULT_SETUP,
  RATING_DEFAULT_SETUP,
  SLIDER_DEFAULT_SETUP,
  OPINION_SCALE_DEFAULT_SETUP,
  TERMS_OF_USE_DEFAULT_SETUP,
  STRIPE_PAYMENT_DEFAULT_SETUP,
} from "../../../../../module/constants";

import { QuestionType } from "../../../../../module/constants";
import extensionIcons from "../../../assets/extensions/index";
import { NODE_TEMPLATES } from "../../../templates/nodeTemplates";
// import default_theme from "oute-ds-shared-assets";
import { sharedAssets as default_theme } from "@src/module/ods";

const { connectionIcon, questionFxIcon, keyValueTableIcon, pictureIcon } =
  extensionIcons;

const QUESTIONS_NODES = {
  [QuestionType.MULTI_QUESTION_PAGE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1742542153398/QuestionGroup.svg",
    name: "Question Group",
    // description: "Question Group",
    type: QuestionType.MULTI_QUESTION_PAGE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#3C9C40",
    module: "Question",
    go_data: MULTI_PAGE_QUESTION_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Multi Question",
        "Suggestion Box",
        "Auto Fill",
        "Predictive Text",
        "Search & Select",
        "Dropdown with Search",
      ],
    },
  },
  [QuestionType.AUTOCOMPLETE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762548153/Autocomplete.svg",
    name: "Autocomplete",
    // description: "Autocomplete",
    type: QuestionType.AUTOCOMPLETE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#263238",
    module: "Question",
    go_data: AUTOCOMPLETE_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Suggestion Box",
        "Auto Fill",
        "Predictive Text",
        "Search & Select",
        "Dropdown with Search",
      ],
    },
  },
  [QuestionType.QUESTIONS_GRID]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1743140338067/Matrix.svg",
    name: "Questions Grid",
    type: QuestionType.QUESTIONS_GRID,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: QUESTIONS_GRID_DEFAULT_SETUP,
    meta: {
      search_keys: [],
    },
  },
  [QuestionType.LOADING]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762471274/Loading.svg",
    name: "Loading",
    // description: "Loading",
    type: QuestionType.LOADING,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#2196F3",
    module: "Question",
    go_data: LOADING_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Progress Indicator",
        "Loading Animation",
        "Wait Screen",
        "Spinner",
        "Buffer Screen",
      ],
    },
  },
  [QuestionType.WELCOME]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762387011/Welcome.svg",
    name: "Welcome",
    type: QuestionType.WELCOME,
    template: NODE_TEMPLATES.START_ROUNDED_RECTANGLE, // Using our new welcome template
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#1E88E5",
    module: "Question",
    go_data: WELCOME_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Intro Screen",
        "Start Page",
        "Greeting Page",
        "Form Intro",
        "Welcome Message",
      ],
    },
    denyFromLink: true,
  },
  [QuestionType.ENDING]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762292733/Ending.svg",
    name: "Ending",
    // description: "Ending",
    type: QuestionType.ENDING,
    template: NODE_TEMPLATES.END_ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#490081",
    module: "Question",
    go_data: ENDING_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Final Step",
        "Submit Button",
        "Completion Page",
        "Thank You Screen",
        "Form End",
        "Close",
      ],
    },
    denyToLink: true,
  },
  [QuestionType.QUOTE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762210051/Quote.svg",
    name: "Quote",
    // description: "Quote",
    type: QuestionType.QUOTE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#6780D8",
    module: "Question",
    go_data: QUOTE_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Citation Box",
        "Reference Input",
        "Quote Text",
        "Quotation Field",
        "Quoted Text",
      ],
    },
  },
  [QuestionType.ADDRESS]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762129628/Address.svg",
    name: "Address",
    // description: "Address",
    type: QuestionType.ADDRESS,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#FF5252",
    module: "Question",
    go_data: ADDRESS_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Location Input",
        "Address Field",
        "Place Input",
        "Geo Details",
        "Location Picker",
      ],
    },
  },
  [QuestionType.TEXT_PREVIEW]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741762028516/TextPreview.svg",
    name: "Text Preview",
    // description: "Text Preview",
    type: QuestionType.TEXT_PREVIEW,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#B0542D",
    module: "Question",
    go_data: TEXT_PREVIEW_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Preview Mode",
        "Text Display",
        "Static Text",
        "Read-Only Text",
        "View Text",
      ],
    },
  },
  [QuestionType.SHORT_TEXT]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741761897530/Short-text.svg",
    name: "Short Text",
    // description: "Short Text",
    type: QuestionType.SHORT_TEXT,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#FF5252",
    module: "Question",
    go_data: SHORT_TEXT_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      search_keys: [
        "Small Input",
        "Text Field",
        "One-Liner",
        "Single Line Text",
        "Input Box",
        "Name",
        "Full Name",
        "First Name",
        "Url",
        "Website",
      ],
    },
  },
  [QuestionType.LONG_TEXT]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741761703117/LongText.svg",
    name: "Long Text",
    // description: "Long Text",
    type: QuestionType.LONG_TEXT,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#0D47A1",
    module: "Question",
    go_data: LONG_TEXT_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Text Area",
        "Paragraph Input",
        "Large Text Field",
        "Essay Box",
        "Comment Box",
        "Notes",
      ],
    },
  },
  [QuestionType.MCQ]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741761589947/Mcq.svg",
    name: "Multi Choice",
    // description: "MCQ",
    type: QuestionType.MCQ,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#2196F3",
    module: "Question",
    go_data: MCQ_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "MCQ",
        "Multi-Select",
        "Checkbox Options",
        "Multiple Answers",
        "Choose Multiple",
        "Select Many",
      ],
    },
  },
  [QuestionType.PICTURE]: {
    _src: pictureIcon,
    name: "Picture",
    // description: "MCQ",
    type: QuestionType.PICTURE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#2196F3",
    module: "Question",
    go_data: PICTURE_DEFAULT_SETUP,
    meta: {
      search_keys: ["Picture", "Image", "Gallery", "Photo"],
    },
  },
  [QuestionType.QUESTION_REPEATER]: {
    _src: pictureIcon,
    name: "Question Repeater",
    // description: "MCQ",
    type: QuestionType.QUESTION_REPEATER,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#2196F3",
    module: "Question",
    go_data: QUESTION_REPEATOR_DEFAULT_SETUP,
    meta: {
      search_keys: ["Question Repeater", "Question Sequence", "Question Loop"],
    },
  },
  [QuestionType.SCQ]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1742541141311/SingleChoice.svg",
    name: "Single Choice",
    // description: "SCQ",
    type: QuestionType.SCQ,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#EDB900",
    module: "Question",
    go_data: SCQ_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "SCQ",
        "Radio Button",
        "Single Answer",
        "Choose One",
        "Pick an Option",
        "One Option Selector",
      ],
    },
  },
  [QuestionType.YES_NO]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741761365360/YesNo.svg",
    name: "Yes/No",
    // description: "Yes/No",
    type: QuestionType.YES_NO,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#212121",
    module: "Question",
    go_data: YES_NO_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      isQuestionRepeatorSupported: true,
      search_keys: [
        "Binary Question",
        "Decision Box",
        "Toggle Input",
        "Confirm/Reject",
        "True/False Selector",
        "Boolean",
      ],
    },
  },
  [QuestionType.DROP_DOWN]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741761077015/Dropdown.svg",
    name: "Dynamic Dropdown",
    // description: "Dropdown",
    type: QuestionType.DROP_DOWN,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#4694E2",
    module: "Question",
    go_data: DROP_DOWN_DEFAULT_SETUP,
    meta: {
      isQuestionRepeatorSupported: true,
      search_keys: [
        "Select Menu",
        "Dropdown List",
        "Choose From Options",
        "Select Field",
        "Pick List",
      ],
    },
  },
  [QuestionType.DROP_DOWN_STATIC]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741761077015/Dropdown.svg",
    name: "Dropdown Static",
    // description: "Dropdown",
    type: QuestionType.DROP_DOWN_STATIC,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#4694E2",
    module: "Question",
    go_data: DROP_DOWN_STATIC_DEFAULT_SETUP,
    meta: {
      isQuestionRepeatorSupported: true,

      search_keys: [
        "Select Menu",
        "Dropdown List",
        "Choose From Options",
        "Select Field",
        "Pick List",
        "Collection",
      ],
    },
  },
  [QuestionType.PHONE_NUMBER]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760967713/PhoneNumber.svg",
    name: "Phone Number",
    // description: "Phone Number",
    type: QuestionType.PHONE_NUMBER,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#C501E4",
    module: "Question",
    go_data: PHONE_NUMBER_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      search_keys: [
        "Contact Number",
        "Mobile Input",
        "Phone Field",
        "Dialer Input",
        "Number Box",
        "Integer",
      ],
    },
  },
  [QuestionType.ZIP_CODE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760875136/Zipcode.svg",
    name: "Zip Code",
    // description: "Zip Code",
    type: QuestionType.ZIP_CODE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#007B47",
    module: "Question",
    go_data: ZIP_CODE_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      search_keys: [
        "Postal Code",
        "PIN Input",
        "ZIP Field",
        "Area Code",
        "Postcode Field",
      ],
    },
  },
  [QuestionType.RANKING]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760620438/Ranking.svg",
    name: "Ranking",
    // description: "Ranking",
    type: QuestionType.RANKING,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#9721F3",
    module: "Question",
    go_data: RANKING_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Priority Order",
        "Sort Options",
        "Rating Scale",
        "Order Selector",
        "List Ranking",
      ],
    },
  },
  [QuestionType.EMAIL]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760530699/Email.svg",
    name: "Email",
    // description: "Email",
    type: QuestionType.EMAIL,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#6780D8",
    module: "Question",
    go_data: EMAIL_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      search_keys: [
        "Email Address",
        "Contact Email",
        "Email Input",
        "Email Field",
        "Email Box",
      ],
    },
  },
  [QuestionType.SIGNATURE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760405590/Signature.svg",
    name: "Signature",
    // description: "Signature",
    type: QuestionType.SIGNATURE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#0BAA3F",
    module: "Question",
    go_data: SIGNATURE_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Digital Signature",
        "Sign Field",
        "E-Signature",
        "Draw Sign",
        "Signature Pad",
      ],
    },
  },
  [QuestionType.DATE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760179749/Date.svg",
    name: "Date",
    // description: "Date",
    type: QuestionType.DATE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#4CAF50",
    module: "Question",
    go_data: DATE_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      isQuestionRepeatorSupported: true,
      search_keys: [
        "Date Picker",
        "Calendar Input",
        "Date Field",
        "Select Date",
        "Schedule Date",
        "Age",
      ],
    },
  },
  [QuestionType.TIME]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741760082965/Time.svg",
    name: "Time",
    // description: "Time",
    type: QuestionType.TIME,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#049032",
    module: "Question",
    go_data: TIME_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Time Picker",
        "Clock Input",
        "Time Field",
        "Select Time",
        "Hour/Minute Selector",
        "Time Stamp",
      ],
    },
  },
  [QuestionType.CURRENCY]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741759302457/Currency.svg",
    name: "Currency",
    // description: "Currency",
    type: QuestionType.CURRENCY,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#4A51EB",
    module: "Question",
    go_data: CURRENCY_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      search_keys: [
        "Money Input",
        "Price Field",
        "Currency Selector",
        "Cost Box",
        "Amount Input",
      ],
    },
  },
  [QuestionType.NUMBER]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741759605326/Number.svg",
    name: "Number",
    // description: "Number",
    type: QuestionType.NUMBER,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#212121",
    module: "Question",
    go_data: NUMBER_DEFAULT_SETUP,
    meta: {
      isMultiQuestionSupported: true,
      search_keys: [
        "Numeric Input",
        "Quantity Field",
        "Number Box",
        "Digit Entry",
        "Counter Input",
        "Integer",
        "Age",
      ],
    },
  },
  [QuestionType.FILE_PICKER]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741759812576/Filepicker.svg",
    name: "File Upload",
    // description: "File Upload",
    type: QuestionType.FILE_PICKER,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#2196F3",
    module: "Question",
    go_data: FILE_PICKER_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "File Picker",
        "File Upload",
        "Document Uploader",
        "Attachment Field",
        "Upload Files",
        "File Selector",
        "Image",
        "Photo",
      ],
    },
  },
  [QuestionType.PDF_VIEWER]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1741759977994/PDFViewer.svg",
    name: "PDF Viewer",
    // description: "PDF Viewer",
    type: QuestionType.PDF_VIEWER,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: "#D33B35",
    module: "Question",
    go_data: PDF_VIEWER_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Document Viewer",
        "PDF Reader",
        "File Preview",
        "Attachment Viewer",
        "View Document",
        "Image",
        "Photo",
      ],
    },
  },
  [QuestionType.CONNECTION]: {
    _src: connectionIcon,
    name: "Connection",
    // description: "Connection",
    type: QuestionType.CONNECTION,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: CONNECTION_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "API Integrator",
        "Data Connector",
        "Integration Manager",
        "Workflow Connection",
        "Module Linker",
      ],
    },
  },
  [QuestionType.FORMULA_BAR]: {
    _src: questionFxIcon,
    name: "FXQ",
    // description: "",
    type: QuestionType.FORMULA_BAR,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: FORMULA_BAR_DEFAULT_SETUP,
    meta: {
      isQuestionRepeatorSupported: true,
      search_keys: [
        "Formula Field",
        "Equation Input",
        "Math Expression",
        "Calculation Box",
        "Formula Editor",
      ],
    },
  },
  [QuestionType.KEY_VALUE_TABLE]: {
    _src: keyValueTableIcon,
    name: "Key Value Table",
    // description: "",
    type: QuestionType.KEY_VALUE_TABLE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: KEY_VALUE_TABLE_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Table Input",
        "Key-Value Pair",
        "Dynamic Table",
        "Editable Grid",
        "Data Grid",
      ],
    },
  },
  [QuestionType.COLLECT_PAYMENT]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1751455989565/payment.svg",
    name: "Collect Payment",
    // description: "",
    type: QuestionType.COLLECT_PAYMENT,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: COLLECT_PAYMENT_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Razorpay",
        "Cashfree",
        "Payment",
        "Amount",
        "Payment Gateway",
      ],
    },
  },
  [QuestionType.RATING]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1756444282174/rating.svg",
    name: "Rating",
    // description: "",
    type: QuestionType.RATING,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: RATING_DEFAULT_SETUP,
    meta: {
      search_keys: ["Rating Field", "Rating Input", "Rating Scale", "Rating"],
    },
  },
  [QuestionType.OPINION_SCALE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1762326873802/opinion-scale-colored.svg",
    name: "Opinion Scale",
    // description: "",
    type: QuestionType.OPINION_SCALE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: OPINION_SCALE_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Opinion Scale",
        "Opinion Scale Input",
        "Opinion Scale Scale",
        "Opinion Scale",
      ],
    },
  },
  [QuestionType.SLIDER]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1762326870891/slider-colored.svg",
    name: "Opinion Scale",
    // description: "",
    type: QuestionType.SLIDER,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: SLIDER_DEFAULT_SETUP,
    meta: {
      search_keys: ["Slider", "Slider Input", "Slider Scale", "Slider"],
    },
  },
  [QuestionType.STRIPE_PAYMENT]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1764325146780/stripe-logo-full.svg",
    name: "Stripe Payment",
    // description: "",
    type: QuestionType.STRIPE_PAYMENT,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: STRIPE_PAYMENT_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Stripe",
        "Payment",
        "Amount",
        "Stripe Payment",
        "Credit Card",
        "Card Payment",
      ],
    },
  },
  [QuestionType.TERMS_OF_USE]: {
    _src: "https://cdn-v1.tinycommand.com/1234567890/1767588961540/legal-terms.svg",
    name: "Consent",
    // description: "",
    type: QuestionType.TERMS_OF_USE,
    template: NODE_TEMPLATES.ROUNDED_RECTANGLE,
    background: default_theme.palette?.grey["A100"],
    foreground: "#fff",
    light: default_theme.palette?.grey["A100"],
    module: "Question",
    go_data: TERMS_OF_USE_DEFAULT_SETUP,
    meta: {
      search_keys: [
        "Terms of Use",
        "Terms",
        "Legal",
        "Agreement",
        "Terms and Conditions",
        "Legal Agreement",
        "Consent",
        "Acknowledgment",
      ],
    },
  },
};

export { QUESTIONS_NODES };
