const UNSUPPORTED_TYPES_SET = new Set([
	"FILE_PICKER",
	"TIME",
	"CURRENCY",
	"LIST",
	"RANKING",
	"SIGNATURE",
	"ENRICHMENT",
]);

const TEXT_BASED_FILTER_TYPES = ["SHORT_TEXT", "LONG_TEXT", "EMAIL", "ADDRESS"];

export { UNSUPPORTED_TYPES_SET, TEXT_BASED_FILTER_TYPES };
