export const tableSetting = [
	{
		name: "importTable",
		label: "Import data",
		iconName: "OUTEDownloadIcon",
		hasSubMenu: true,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: false,
	},
	{
		name: "renameTable",
		label: "Rename table",
		iconName: "OUTEEditIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: false,
	},
	{
		name: "hideTable",
		label: "Hide table",
		iconName: "OUTEVisibilityOffIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: true,
	},
	{
		name: "manageFields",
		label: "Manage fields",
		iconName: "OUTESettingsIcon",
		hasSubMenu: false,
		hasTeamBadge: true,
		hasDividerAfter: false,
		hasComingSoon: true,
	},
	{
		name: "duplicateTable",
		label: "Duplicate table",
		iconName: "OUTEFileCopyIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: true, // Divider after duplicate table
		hasComingSoon: true,
	},
	{
		name: "configureDateDependencies",
		label: "Configure date dependencies",
		iconName: "OUTECalendarTodayIcon",
		hasSubMenu: false,
		hasTeamBadge: true,
		hasDividerAfter: false,
		hasComingSoon: true,
	},
	{
		name: "editTableDescription",
		label: "Edit table description",
		iconName: "OUTEInfoIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: true,
	},
	{
		name: "editTablePermissions",
		label: "Edit table permissions",
		iconName: "OUTELockIcon",
		hasSubMenu: false,
		hasTeamBadge: true,
		hasDividerAfter: true,
		hasComingSoon: true,
	},
	{
		name: "exportAsCSV",
		label: "Export as CSV",
		iconName: "OUTEDownloadIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: false,
	},
	{
		name: "clearData",
		label: "Clear data",
		iconName: "OUTECloseIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: false,
	},
	{
		name: "deleteTable",
		label: "Delete table",
		iconName: "OUTETrashIcon",
		hasSubMenu: false,
		hasTeamBadge: false,
		hasDividerAfter: false,
		hasComingSoon: false,
	},
];
