import type { CoachMarkDefinition } from './types';

export const JOURNEYS: Record<string, string[]> = {
  'journey-welcome': [
    'cm-add-table',
    'cm-sidebar-tables',
    'cm-view-switcher',
    'cm-add-record',
    'cm-toolbar-overview',
  ],
  'journey-grid': [
    'cm-grid-cell-edit',
    'cm-grid-column-header',
    'cm-grid-add-column',
    'cm-grid-row-expand',
    'cm-grid-row-height',
  ],
  'journey-data-tools': [
    'cm-filter',
    'cm-sort',
    'cm-group',
    'cm-hide-fields',
    'cm-conditional-color',
  ],
  'journey-views': [
    'cm-kanban-intro',
    'cm-calendar-intro',
    'cm-gantt-intro',
    'cm-gallery-intro',
    'cm-form-intro',
  ],
  'journey-record-detail': [
    'cm-record-expand-fields',
    'cm-record-comments',
    'cm-record-history',
  ],
  'journey-ai': [
    'cm-ai-chat-panel',
    'cm-ai-enrichment',
  ],
  'journey-sharing': [
    'cm-share',
    'cm-workflow-button',
  ],
};

export const COACH_MARKS: Record<string, CoachMarkDefinition> = {
  'cm-add-table': {
    id: 'cm-add-table',
    journeyId: 'journey-welcome',
    stepIndex: 0,
    title: 'Add a New Table',
    description: 'Each sheet can hold multiple tables — like worksheets in a spreadsheet. Click here to create one.',
    placement: 'right',
  },
  'cm-sidebar-tables': {
    id: 'cm-sidebar-tables',
    journeyId: 'journey-welcome',
    stepIndex: 1,
    title: 'Your Tables',
    description: 'All tables in this sheet live here. Click any table to open it, or create a new one using the + button below.',
    placement: 'right',
  },
  'cm-view-switcher': {
    id: 'cm-view-switcher',
    journeyId: 'journey-welcome',
    stepIndex: 2,
    title: 'Switch Views',
    description: 'See your data your way. Toggle between Grid, Kanban, Calendar, Gantt, Gallery, and Form views here.',
    placement: 'bottom',
  },
  'cm-add-record': {
    id: 'cm-add-record',
    journeyId: 'journey-welcome',
    stepIndex: 3,
    title: 'Add a Row',
    description: 'Click here to add a new record to your table. You can also press the down-arrow key from the last row.',
    placement: 'bottom',
  },
  'cm-toolbar-overview': {
    id: 'cm-toolbar-overview',
    journeyId: 'journey-welcome',
    stepIndex: 4,
    title: 'Organise Your Data',
    description: 'Filter, sort, group, and hide fields — all without changing the underlying data. Try Filter first.',
    placement: 'bottom',
  },

  'cm-grid-cell-edit': {
    id: 'cm-grid-cell-edit',
    journeyId: 'journey-grid',
    stepIndex: 0,
    title: 'Edit Any Cell',
    description: 'Double-click a cell — or just start typing — to edit it inline. Press Enter or Tab to move on.',
    placement: 'top',
  },
  'cm-grid-column-header': {
    id: 'cm-grid-column-header',
    journeyId: 'journey-grid',
    stepIndex: 1,
    title: 'Manage Fields',
    description: 'Click a column header to rename it, change its type, sort, or hide it. Right-click for even more options.',
    placement: 'bottom',
  },
  'cm-grid-add-column': {
    id: 'cm-grid-add-column',
    journeyId: 'journey-grid',
    stepIndex: 2,
    title: 'Add a New Field',
    description: 'Click the + at the end of the header row to add a new column. Choose from 20+ field types.',
    placement: 'bottom',
  },
  'cm-grid-row-expand': {
    id: 'cm-grid-row-expand',
    journeyId: 'journey-grid',
    stepIndex: 3,
    title: 'Expand a Record',
    description: 'Click the expand icon on any row to open a full-detail view with all fields, a history log, and comments.',
    placement: 'right',
  },
  'cm-grid-row-height': {
    id: 'cm-grid-row-height',
    journeyId: 'journey-grid',
    stepIndex: 4,
    title: 'Adjust Row Height',
    description: 'Toggle between compact, medium, and tall row heights to see more or less content at a glance.',
    placement: 'bottom',
  },

  'cm-filter': {
    id: 'cm-filter',
    journeyId: 'journey-data-tools',
    stepIndex: 0,
    title: 'Filter Your Data',
    description: 'Show only the rows that match your criteria. Combine multiple conditions with AND / OR logic.',
    placement: 'bottom',
  },
  'cm-sort': {
    id: 'cm-sort',
    journeyId: 'journey-data-tools',
    stepIndex: 1,
    title: 'Sort Records',
    description: 'Sort by any field, in any direction. Chain multiple sort rules to get the exact order you need.',
    placement: 'bottom',
  },
  'cm-group': {
    id: 'cm-group',
    journeyId: 'journey-data-tools',
    stepIndex: 2,
    title: 'Group by Field',
    description: 'Collapse records into expandable groups based on a field value — great for status or category fields.',
    placement: 'bottom',
  },
  'cm-hide-fields': {
    id: 'cm-hide-fields',
    journeyId: 'journey-data-tools',
    stepIndex: 3,
    title: 'Hide Fields',
    description: "Declutter your view by hiding fields you don't need right now. The data is still there — just out of sight.",
    placement: 'bottom',
  },
  'cm-conditional-color': {
    id: 'cm-conditional-color',
    journeyId: 'journey-data-tools',
    stepIndex: 4,
    title: 'Highlight with Color',
    description: 'Set rules to automatically color rows or cells based on their values. Perfect for status-at-a-glance.',
    placement: 'bottom',
  },

  'cm-kanban-intro': {
    id: 'cm-kanban-intro',
    journeyId: 'journey-views',
    stepIndex: 0,
    title: 'Kanban View',
    description: 'Your records are now cards on a board, grouped by a single-select field. Drag cards between columns to update values.',
    placement: 'top',
    showCondition: 'view:kanban',
  },
  'cm-calendar-intro': {
    id: 'cm-calendar-intro',
    journeyId: 'journey-views',
    stepIndex: 1,
    title: 'Calendar View',
    description: 'Records with date fields appear here as events. Drag them to reschedule.',
    placement: 'top',
    showCondition: 'view:calendar',
  },
  'cm-gantt-intro': {
    id: 'cm-gantt-intro',
    journeyId: 'journey-views',
    stepIndex: 2,
    title: 'Gantt View',
    description: 'Visualise tasks over time with start and end dates. Drag bars to reschedule or resize them.',
    placement: 'top',
    showCondition: 'view:gantt',
  },
  'cm-gallery-intro': {
    id: 'cm-gallery-intro',
    journeyId: 'journey-views',
    stepIndex: 3,
    title: 'Gallery View',
    description: 'See your records as a visual card grid. Great when you have image attachment fields.',
    placement: 'top',
    showCondition: 'view:gallery',
  },
  'cm-form-intro': {
    id: 'cm-form-intro',
    journeyId: 'journey-views',
    stepIndex: 4,
    title: 'Form View',
    description: 'Share a link to this form so anyone can add records to your table — no account needed.',
    placement: 'top',
    showCondition: 'view:form',
  },

  'cm-record-expand-fields': {
    id: 'cm-record-expand-fields',
    journeyId: 'journey-record-detail',
    stepIndex: 0,
    title: 'All Fields in One Place',
    description: 'Every field for this record is shown here. Click any value to edit it directly.',
    placement: 'right',
  },
  'cm-record-comments': {
    id: 'cm-record-comments',
    journeyId: 'journey-record-detail',
    stepIndex: 1,
    title: 'Comment on Records',
    description: 'Discuss this record with your team, leave notes, or track decisions — all in context.',
    placement: 'left',
  },
  'cm-record-history': {
    id: 'cm-record-history',
    journeyId: 'journey-record-detail',
    stepIndex: 2,
    title: 'Change History',
    description: 'See every edit ever made to this record, who made it, and when.',
    placement: 'left',
  },

  'cm-ai-chat-panel': {
    id: 'cm-ai-chat-panel',
    journeyId: 'journey-ai',
    stepIndex: 0,
    title: 'Ask AI About Your Data',
    description: 'Chat with an AI assistant that has full context of your table. Ask it to summarise, find patterns, or draft content.',
    placement: 'left',
  },
  'cm-ai-enrichment': {
    id: 'cm-ai-enrichment',
    journeyId: 'journey-ai',
    stepIndex: 1,
    title: 'Auto-Enrich with AI',
    description: 'Use AI workflows to automatically fill fields — find company info, people data, email addresses and more.',
    placement: 'right',
  },

  'cm-share': {
    id: 'cm-share',
    journeyId: 'journey-sharing',
    stepIndex: 0,
    title: 'Share Your Sheet',
    description: 'Invite team members, set their permission level, or generate a public read-only link.',
    placement: 'bottom',
  },
  'cm-workflow-button': {
    id: 'cm-workflow-button',
    journeyId: 'journey-sharing',
    stepIndex: 1,
    title: 'Automate with Workflows',
    description: 'Build no-code automations that trigger actions when records change — send emails, call webhooks, and more.',
    placement: 'right',
  },

  'cm-search': {
    id: 'cm-search',
    journeyId: null,
    stepIndex: 0,
    title: 'Search & Replace',
    description: 'Press Ctrl+F (or click here) to search across all visible cells. Hold Shift to also replace values.',
    placement: 'bottom',
  },
  'cm-theme-picker': {
    id: 'cm-theme-picker',
    journeyId: null,
    stepIndex: 0,
    title: 'Customise Your Theme',
    description: 'Switch between light and dark mode, or pick an accent colour that matches your brand.',
    placement: 'bottom',
  },
  'cm-language-switcher': {
    id: 'cm-language-switcher',
    journeyId: null,
    stepIndex: 0,
    title: 'Change Language',
    description: 'Tiny Tables is available in English, Spanish, Portuguese, and Arabic. Pick what feels natural.',
    placement: 'right',
  },
  'cm-import-export': {
    id: 'cm-import-export',
    journeyId: null,
    stepIndex: 0,
    title: 'Import Data',
    description: 'Bring in data from a CSV or Excel file instantly — field types are detected automatically.',
    placement: 'bottom',
  },
};
