import { Country, State, City } from "country-state-city";

// Get all countries, states, and cities from the package
export const ALL_COUNTRIES = Country.getAllCountries().map(
	(country) => country.name,
);
export const ALL_STATES = State.getAllStates().map((state) => state.name);
export const ALL_CITIES = City.getAllCities().map((city) => city.name);

// Top 50 famous countries for initial display
export const TOP_COUNTRIES = [
	"United States",
	"China",
	"India",
	"Brazil",
	"Japan",
	"Germany",
	"United Kingdom",
	"France",
	"Canada",
	"Australia",
	"South Korea",
	"Italy",
	"Spain",
	"Mexico",
	"Netherlands",
	"Sweden",
	"Switzerland",
	"Singapore",
	"Norway",
	"Denmark",
	"Finland",
	"New Zealand",
	"Belgium",
	"Austria",
	"Ireland",
	"Israel",
	"Portugal",
	"Czech Republic",
	"Poland",
	"Hungary",
	"Greece",
	"Chile",
	"Estonia",
	"Slovenia",
	"Lithuania",
	"Slovakia",
	"Latvia",
	"Luxembourg",
	"Croatia",
	"Malta",
	"Cyprus",
	"South Africa",
	"Argentina",
	"Uruguay",
	"Costa Rica",
	"Panama",
	"Colombia",
	"Peru",
	"Ecuador",
	"Thailand",
	"Malaysia",
];

// Top 50 famous states/provinces for initial display (USA + India focused)
export const TOP_STATES = [
	// Major US States
	"California",
	"Texas",
	"Florida",
	"New York",
	"Pennsylvania",
	"Illinois",
	"Ohio",
	"Georgia",
	"North Carolina",
	"Michigan",
	"New Jersey",
	"Virginia",
	"Washington",
	"Arizona",
	"Massachusetts",
	"Tennessee",
	"Indiana",
	"Missouri",
	"Maryland",
	"Wisconsin",
	"Colorado",
	"Minnesota",
	"South Carolina",
	"Alabama",
	"Louisiana",
	"Kentucky",
	"Oregon",
	"Oklahoma",
	"Connecticut",
	"Utah",
	"Iowa",
	"Nevada",
	"Arkansas",
	"Mississippi",
	"Kansas",
	"New Mexico",
	"Nebraska",
	"West Virginia",
	"Idaho",
	"Hawaii",
	"New Hampshire",
	"Maine",
	"Montana",
	"Rhode Island",
	"Delaware",
	"South Dakota",
	"North Dakota",
	"Alaska",
	"Vermont",
	"Wyoming",
	// Major Indian States
	"Maharashtra",
	"Karnataka",
	"Tamil Nadu",
	"Uttar Pradesh",
	"Gujarat",
	"West Bengal",
	"Rajasthan",
	"Madhya Pradesh",
	"Andhra Pradesh",
	"Kerala",
	"Punjab",
	"Haryana",
	"Delhi",
	"Telangana",
	"Bihar",
	"Odisha",
	"Assam",
	"Jharkhand",
	"Chhattisgarh",
	"Uttarakhand",
	"Himachal Pradesh",
	"Goa",
	"Manipur",
	"Meghalaya",
	"Mizoram",
	"Nagaland",
	"Sikkim",
	"Tripura",
	"Arunachal Pradesh",
];

// Top 50 famous cities for initial display
export const TOP_CITIES = [
	"New York",
	"Los Angeles",
	"Chicago",
	"Houston",
	"Phoenix",
	"Philadelphia",
	"San Antonio",
	"San Diego",
	"Dallas",
	"San Jose",
	"Austin",
	"Jacksonville",
	"Fort Worth",
	"Columbus",
	"Charlotte",
	"San Francisco",
	"Indianapolis",
	"Seattle",
	"Denver",
	"Washington",
	"Boston",
	"El Paso",
	"Nashville",
	"Detroit",
	"Oklahoma City",
	"Portland",
	"Las Vegas",
	"Memphis",
	"Louisville",
	"Baltimore",
	"Milwaukee",
	"Albuquerque",
	"Tucson",
	"Fresno",
	"Sacramento",
	"Mesa",
	"Kansas City",
	"Atlanta",
	"Long Beach",
	"Colorado Springs",
	"Raleigh",
	"Miami",
	"Virginia Beach",
	"Omaha",
	"Oakland",
	"Minneapolis",
	"Tulsa",
	"Arlington",
	"Tampa",
	"New Orleans",
	"Wichita",
	"Cleveland",
	"Bakersfield",
	"Aurora",
	"Anaheim",
	"Honolulu",
	"Santa Ana",
	"Corpus Christi",
	"Riverside",
	"Lexington",
	"Stockton",
	"Henderson",
	"Saint Paul",
	"St. Louis",
	"Plano",
	"Newark",
	"Toledo",
	"Greensboro",
	"Lincoln",
	"Anchorage",
	"London",
	"Birmingham",
	"Leeds",
	"Glasgow",
	"Sheffield",
	"Bradford",
	"Edinburgh",
	"Liverpool",
	"Manchester",
	"Bristol",
	"Paris",
	"Marseille",
	"Lyon",
	"Toulouse",
	"Nice",
	"Nantes",
	"Strasbourg",
	"Montpellier",
	"Bordeaux",
	"Lille",
	"Tokyo",
	"Yokohama",
	"Osaka",
	"Nagoya",
	"Sapporo",
	"Fukuoka",
	"Kobe",
	"Kawasaki",
	"Kyoto",
	"Saitama",
	"Berlin",
	"Hamburg",
	"Munich",
	"Cologne",
	"Frankfurt",
	"Stuttgart",
	"Düsseldorf",
	"Dortmund",
	"Essen",
	"Leipzig",
	"Sydney",
	"Melbourne",
	"Brisbane",
	"Perth",
	"Adelaide",
	"Gold Coast",
	"Newcastle",
	"Canberra",
	"Sunshine Coast",
	"Wollongong",
	"Mumbai",
	"Delhi",
	"Bangalore",
	"Hyderabad",
	"Ahmedabad",
	"Chennai",
	"Kolkata",
	"Surat",
	"Pune",
	"Jaipur",
	"São Paulo",
	"Rio de Janeiro",
	"Brasília",
	"Salvador",
	"Fortaleza",
	"Belo Horizonte",
	"Manaus",
	"Curitiba",
	"Recife",
	"Porto Alegre",
	"Toronto",
	"Montreal",
	"Vancouver",
	"Calgary",
	"Edmonton",
	"Ottawa",
	"Winnipeg",
	"Quebec City",
	"Hamilton",
	"Kitchener",
];

// Mapping system for LocationFilter autocomplete fields
export const LOCATION_FIELD_MAPPING = {
	countriesInclude: {
		label: "Countries to include",
		placeholder: "e.g. United States, India",
		options: TOP_COUNTRIES.map((country, index) => ({
			id: `country_${index}`,
			label: country,
			value: country,
		})),
		stateKey: "countriesInclude",
		allOptions: ALL_COUNTRIES,
	},
	countriesExclude: {
		label: "Countries to exclude",
		placeholder: "e.g. France, Spain",
		options: TOP_COUNTRIES.map((country, index) => ({
			id: `country_${index}`,
			label: country,
			value: country,
		})),
		stateKey: "countriesExclude",
		allOptions: ALL_COUNTRIES,
	},
	statesInclude: {
		label: "States to include",
		placeholder: "e.g. California, New York",
		options: TOP_STATES.map((state, index) => ({
			id: `state_${index}`,
			label: state,
			value: state,
		})),
		stateKey: "statesInclude",
		allOptions: ALL_STATES,
	},
	statesExclude: {
		label: "States to exclude",
		placeholder: "e.g. Texas, Florida",
		options: TOP_STATES.map((state, index) => ({
			id: `state_${index}`,
			label: state,
			value: state,
		})),
		stateKey: "statesExclude",
		allOptions: ALL_STATES,
	},
	citiesInclude: {
		label: "Cities to include",
		placeholder: "e.g. New York, Mumbai",
		options: TOP_CITIES.map((city, index) => ({
			id: `city_${index}`,
			label: city,
			value: city,
		})),
		stateKey: "citiesInclude",
		allOptions: ALL_CITIES,
	},
	citiesExclude: {
		label: "Cities to exclude",
		placeholder: "e.g. San Francisco",
		options: TOP_CITIES.map((city, index) => ({
			id: `city_${index}`,
			label: city,
			value: city,
		})),
		stateKey: "citiesExclude",
		allOptions: ALL_CITIES,
	},
};

// Field order for rendering
export const LOCATION_FIELD_ORDER = [
	"countriesInclude",
	"countriesExclude",
	"statesInclude",
	"statesExclude",
	"citiesInclude",
	"citiesExclude",
];

// Utility function to filter options based on user input
export const filterLocationOptions = (allOptions, searchTerm, limit = 50) => {
	if (!searchTerm || searchTerm.length < 2) {
		return allOptions.slice(0, limit);
	}

	const filtered = allOptions.filter((option) =>
		option.toLowerCase().includes(searchTerm.toLowerCase()),
	);

	return filtered.slice(0, limit);
};
