export const LANGUAGE_OPTIONS = [
  { id: "af", label: "Afrikaans - af" },
  { id: "sq", label: "Albanian - sq" },
  { id: "am", label: "Amharic - am" },
  { id: "ar", label: "Arabic - ar" },
  { id: "hy", label: "Armenian - hy" },
  { id: "az", label: "Azerbaijani - az" },
  { id: "eu", label: "Basque - eu" },
  { id: "bn", label: "Bengali - bn" },
  { id: "bs", label: "Bosnian - bs" },
  { id: "bg", label: "Bulgarian - bg" },
  { id: "ca", label: "Catalan - ca" },
  { id: "ceb", label: "Cebuano - ceb" }, // used in translation APIs
  { id: "zh-cn", label: "Chinese (Simplified) - zh-cn" },
  { id: "zh-tw", label: "Chinese (Traditional) - zh-tw" },
  { id: "hr", label: "Croatian - hr" },
  { id: "cs", label: "Czech - cs" },
  { id: "da", label: "Danish - da" },
  { id: "nl", label: "Dutch - nl" },
  { id: "en", label: "English - en" },
  { id: "en-gb", label: "English (UK) - en-gb" },
  { id: "en-us", label: "English (US) - en-us" },
  { id: "eo", label: "Esperanto - eo" },
  { id: "et", label: "Estonian - et" },
  { id: "fi", label: "Finnish - fi" },
  { id: "fr", label: "French - fr" },
  { id: "gl", label: "Galician - gl" },
  { id: "ka", label: "Georgian - ka" },
  { id: "de", label: "German - de" },
  { id: "el", label: "Greek - el" },
  { id: "gu", label: "Gujarati - gu" },
  { id: "ht", label: "Haitian Creole - ht" },
  { id: "ha", label: "Hausa - ha" },
  { id: "he", label: "Hebrew - he" },
  { id: "hi", label: "Hindi - hi" },
  { id: "hu", label: "Hungarian - hu" },
  { id: "is", label: "Icelandic - is" },
  { id: "id", label: "Indonesian - id" },
  { id: "ga", label: "Irish - ga" },
  { id: "it", label: "Italian - it" },
  { id: "ja", label: "Japanese - ja" },
  { id: "jv", label: "Javanese - jv" },
  { id: "kn", label: "Kannada - kn" },
  { id: "kk", label: "Kazakh - kk" },
  { id: "km", label: "Khmer - km" },
  { id: "ko", label: "Korean - ko" },
  { id: "ku", label: "Kurdish - ku" },
  { id: "ky", label: "Kyrgyz - ky" },
  { id: "lo", label: "Lao - lo" },
  { id: "la", label: "Latin - la" },
  { id: "lv", label: "Latvian - lv" },
  { id: "lt", label: "Lithuanian - lt" },
  { id: "mk", label: "Macedonian - mk" },
  { id: "mg", label: "Malagasy - mg" },
  { id: "ms", label: "Malay - ms" },
  { id: "ml", label: "Malayalam - ml" },
  { id: "mt", label: "Maltese - mt" },
  { id: "mi", label: "Maori - mi" },
  { id: "mr", label: "Marathi - mr" },
  { id: "mn", label: "Mongolian - mn" },
  { id: "my", label: "Myanmar (Burmese) - my" },
  { id: "ne", label: "Nepali - ne" },
  { id: "no", label: "Norwegian - no" },
  { id: "or", label: "Odia (Oriya) - or" },
  { id: "ps", label: "Pashto - ps" },
  { id: "fa", label: "Persian - fa" },
  { id: "pl", label: "Polish - pl" },
  { id: "pt", label: "Portuguese - pt" },
  { id: "pt-br", label: "Portuguese (Brazil) - pt-br" },
  { id: "pa", label: "Punjabi - pa" },
  { id: "ro", label: "Romanian - ro" },
  { id: "ru", label: "Russian - ru" },
  { id: "sm", label: "Samoan - sm" },
  { id: "gd", label: "Scots Gaelic - gd" },
  { id: "sr", label: "Serbian - sr" },
  { id: "st", label: "Sesotho - st" },
  { id: "sn", label: "Shona - sn" },
  { id: "sd", label: "Sindhi - sd" },
  { id: "si", label: "Sinhala - si" },
  { id: "sk", label: "Slovak - sk" },
  { id: "sl", label: "Slovenian - sl" },
  { id: "so", label: "Somali - so" },
  { id: "es", label: "Spanish - es" },
  { id: "es-mx", label: "Spanish (Mexico) - es-mx" },
  { id: "es-es", label: "Spanish (Spain) - es-es" },
  { id: "su", label: "Sundanese - su" },
  { id: "sw", label: "Swahili - sw" },
  { id: "sv", label: "Swedish - sv" },
  { id: "tl", label: "Tagalog - tl" },
  { id: "tg", label: "Tajik - tg" },
  { id: "ta", label: "Tamil - ta" },
  { id: "te", label: "Telugu - te" },
  { id: "th", label: "Thai - th" },
  { id: "tr", label: "Turkish - tr" },
  { id: "uk", label: "Ukrainian - uk" },
  { id: "ur", label: "Urdu - ur" },
  { id: "uz", label: "Uzbek - uz" },
  { id: "vi", label: "Vietnamese - vi" },
  { id: "cy", label: "Welsh - cy" },
  { id: "xh", label: "Xhosa - xh" },
  { id: "yi", label: "Yiddish - yi" },
  { id: "yo", label: "Yoruba - yo" },
  { id: "zu", label: "Zulu - zu" },
];
