export const DATABASE_TYPES = {
  MYSQL: "mysql",
  POSTGRESQL: "postgres",
};

export const DATABASE_CONFIGS = {
  [DATABASE_TYPES.MYSQL]: {
    defaultPort: 3306,
    name: "MySQL",
    colorTheme: { dark: "#00758f", light: "#00a8cc", foreground: "#fff" },
    supportsSchema: false,
    formConfig: [
      {
        key: "name",
        label: "Connection Name",
        description: "Provide connection name",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "host",
        label: "Host",
        description: "Provide hostname or ip address",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "port",
        label: "Port",
        description: "Provide port number",
        is_advanced: false,
        type: "INT",
        required: true,
      },
      {
        key: "database",
        label: "Database name",
        description: "Provide database name",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "username",
        label: "Username",
        description: "Provide username",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        description: "Provide database password",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
    ],
  },
  [DATABASE_TYPES.POSTGRESQL]: {
    defaultPort: 5432,
    name: "PostgreSQL",
    colorTheme: { dark: "#336791", light: "#4a9bd1", foreground: "#fff" },
    supportsSchema: true,
    defaultSchema: "public",
    formConfig: [
      {
        key: "name",
        label: "Connection Name",
        description: "Provide connection name",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "host",
        label: "Host",
        description: "Provide hostname or ip address",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "port",
        label: "Port",
        description: "Provide port number",
        is_advanced: false,
        type: "INT",
        required: true,
        value: 5432,
      },
      {
        key: "schema",
        label: "Schema name",
        description: "Provide schema name",
        is_advanced: false,
        type: "STRING",
        required: true,
        value: "public",
      },
      {
        key: "database",
        label: "Database name",
        description: "Provide database name",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "username",
        label: "Username",
        description: "Provide username",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        description: "Provide database password",
        is_advanced: false,
        type: "STRING",
        required: true,
      },
    ],
  },
};
