export const MODE = Object.freeze({
  INTEGRATION_CANVAS: "INTEGRATION_CANVAS", //IC
  WORKFLOW_CANVAS: "WORKFLOW_CANVAS", //FC
  CMS_CANVAS: "CMS_CANVAS", //CMS
  WC_CANVAS: "WC_CANVAS", //WC
  AGENT_CANVAS: "AGENT_CANVAS", //AGENT
  TOOL_CANVAS: "TOOL_CANVAS",
});
