import { useCallback, useMemo, useRef, useState, useEffect } from "react";
// import ODSAutoComplete from "oute-ds-autocomplete";
// import ODSButton from "oute-ds-button";
// import ODSIcon from "oute-ds-icon";
// import ODSLabel from "oute-ds-label";
// import Radio from "oute-ds-radio";
// import RadioGroup from "oute-ds-radio-group";
// import default_theme from "oute-ds-shared-assets";
import InputGridV2 from "@oute/oute-ds.molecule.input-grid-v2";
// import { showConfirmDialog } from "oute-ds-dialog";
// import ODSAdvancedLabel from "oute-ds-advanced-label";
// import ODSDialog from "oute-ds-dialog";
// import { showAlert } from "oute-ds-alert";
// import { FormulaBar } from "oute-ds-formula-bar";
import { RequestBodyType } from "../../../../classes";
import RequestRawDataType from "../../../../classes/http/request-raw-data-type";
// import ODSTextField from "oute-ds-text-field";
import { ODSAutocomplete as ODSAutoComplete, ODSButton, ODSIcon, ODSLabel, ODSRadio as Radio, ODSRadioGroup as RadioGroup, default_theme, showConfirmDialog, ODSAdvancedLabel, ODSDialog, showAlert, ODSFormulaBar as FormulaBar, ODSTextField } from "@src/module/ods";

import classes from "./BodyPanel.module.css";
import {
  CONTENT_TYPE,
  DEFAULT_BINARY_TYPE,
  FORM_DATA_CONTENT_TYPE,
  X_WWW_FORM_URLENCODED_CONTENT_TYPE,
} from "../../constant";
import {
  createPrimitive,
  createContentTypeRow,
  radioGroupData,
  subTypeOptions,
} from "../../utils";
import storageSDKServices from "../../../../services/storageSDKServices";
import cloneDeep from "lodash/cloneDeep";
import { convertJsonToGridSchema } from "@oute/oute-ds.molecule.input-grid-v2/components";
import JsonDialogContent from "../../../common-components/jsonDialog/jsonDialogContent";

const BodyPanel = ({
  bodyType,
  setBodyType,
  formGridData,
  setFormGridData,
  urlencodedGridData,
  setUrlEncodedGridData,
  binaryData,
  setBinaryData,
  rawData,
  setRawData,
  subType,
  setSubType,
  headers,
  setHeaders,
  variables,
}) => {
  const inputGridRef = useRef();
  const [editingCell, setEditingCell] = useState(null);
  const [showJSONDialog, setShowJSONDialog] = useState(false);

  // Function to check if a row is empty (no key and no value)
  const isEmptyRow = (row) => {
    return (
      (!row.key || row.key.trim() === "") &&
      (!row.value?.blocks ||
        row.value.blocks.length === 0 ||
        (row.value.blocks.length === 1 && row.value.blocks[0].text === ""))
    );
  };

  const urlencodedAddRow = useCallback(() => {
    setUrlEncodedGridData((prev) => {
      const newData = [
        ...prev,
        {
          rowid: crypto.randomUUID(),
          key: "",
          value: { type: "fx", blocks: [] },
          valueStr: "",
        },
      ];
      return newData;
    });
  }, [setUrlEncodedGridData]);

  const formGridAddRow = useCallback(() => {
    setFormGridData((prev) => {
      const newData = [
        ...prev,
        {
          rowid: crypto.randomUUID(),
          key: "",
          value: { type: "fx", blocks: [] },
          valueStr: "",
        },
      ];

      return newData;
    });
  }, [setFormGridData]);

  const deleteRow = useCallback(
    (rowIndex) => {
      bodyType === RequestBodyType.FORM_DATA
        ? setFormGridData((prev) => {
            const newData = [...prev];
            newData.splice(rowIndex, 1);

            // If we deleted the last row or all rows, add an empty row
            if (newData.length === 0) {
              newData.push({ rowid: crypto.randomUUID(), expand: false });
            }

            return newData;
          })
        : setUrlEncodedGridData((prev) => {
            const newData = [...prev];
            newData.splice(rowIndex, 1);

            // If we deleted the last row or all rows, add an empty row
            if (newData.length === 0) {
              newData.push({ rowid: crypto.randomUUID(), expand: false });
            }

            return newData;
          });
    },
    [bodyType, setFormGridData, setUrlEncodedGridData]
  );

  const updateHeadersWithContentType = (contentType) => {
    const headersCopy = cloneDeep(headers);
    const isAutogeneratedContentType = (header) =>
      header.key?.toLowerCase() === CONTENT_TYPE && header?.autoGenerated;

    const autoGeneratedContentTypeIndex = headersCopy.findIndex(
      isAutogeneratedContentType
    );

    if (autoGeneratedContentTypeIndex !== -1) {
      headersCopy[autoGeneratedContentTypeIndex].value =
        createPrimitive(contentType);
    } else {
      const contentTypeData = createContentTypeRow(contentType);
      headersCopy.unshift(contentTypeData);
    }

    setHeaders(headersCopy);
  };

  const handleSubTypeChange = async (e, updatedSubType) => {
    let response = "ok";
    if (
      updatedSubType.id === RequestRawDataType.JSON.id ||
      subType.id === RequestRawDataType.JSON.id
    ) {
      await showConfirmDialog({
        showCloseIcon: false,
        dialogTitle: (
          <ODSAdvancedLabel
            fullWidth
            labelText="Warning: Data Will Be Replaced"
            labelProps={{
              variant: "h6",
              color: default_theme.palette?.grey["A100"],
            }}
            leftAdornment={<ODSIcon outeIconName="OUTEWarningIcon" />}
            data-testid="http-configure-raw-warning-title"
          />
        ),
        dialogContent: (
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              width: "37.5rem",
              gap: "1rem",
            }}
          >
            <ODSLabel
              variant="body1"
              color={default_theme.palette?.grey["A100"]}
              data-testid="http-configure-raw-warning-description"
            >
              You are about to replace the current data with new data. This
              cannot be undone.
            </ODSLabel>
          </div>
        ),
        okLabel: "Continue",
        okButtonVariant: "black",
        okButtonProps: { "data-testid": "http-configure-raw-warning-continue" },
        cancelButtonProps: {
          "data-testid": "http-configure-raw-warning-cancel",
        },
        cancelLabel: "Cancel",
        cancelButtonVariant: "black-outlined",
        onOk: () => {
          setRawData([]);
          setShowJSONDialog(false);
        },
        onCancel: () => {
          response = "cancel";
        },
        dialogProps: { "data-testid": "http-configure-raw-warning-modal" },
      });
    }
    if (response !== "cancel") {
      updateHeadersWithContentType(updatedSubType.contentType);
      setSubType(updatedSubType);
    }
  };

  const handleBodyTypeChange = (e, bodyType) => {
    if (bodyType === RequestBodyType.FORM_DATA) {
      updateHeadersWithContentType(FORM_DATA_CONTENT_TYPE);

      // Ensure there's at least one row in form data
      if (formGridData.length === 0) {
        setFormGridData([{ rowid: crypto.randomUUID(), expand: false }]);
      }
    }
    if (bodyType === RequestBodyType.X_WWW_FORM_URL_ENCODED) {
      updateHeadersWithContentType(X_WWW_FORM_URLENCODED_CONTENT_TYPE);

      // Ensure there's at least one row in URL encoded data
      if (urlencodedGridData.length === 0) {
        setUrlEncodedGridData([{ rowid: crypto.randomUUID(), expand: false }]);
      }
    }
    if (bodyType === RequestBodyType.BINARY) {
      updateHeadersWithContentType(binaryData?.fileType || DEFAULT_BINARY_TYPE);
    }
    if (bodyType === RequestBodyType.RAW) {
      updateHeadersWithContentType(subType.contentType);
    }
    setBodyType(bodyType);
  };

  const onCloseJSONDialog = () => {
    setShowJSONDialog(false);
  };

  const modifyJSONHandler = async (data) => {
    const _rawData = convertJsonToGridSchema({ "": data }, true);
    inputGridRef?.current?.updateGrid(_rawData);
    setRawData(_rawData);
    onCloseJSONDialog();
  };

  const JSONGridData = useMemo(
    () => (Array.isArray(rawData) ? cloneDeep(rawData) : []),
    [rawData]
  );

  const deleteBinaryFile = async () => {
    const response = await storageSDKServices.getUploadSignedUrl({
      ...binaryData,
      op: "delete",
    });
    if (response.status == "success") {
      setBinaryData(null);
    }
  };

  const fileUploadHandler = (e) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      const file = files[0];
      const fileName = file.name;
      const fileType = file.type || DEFAULT_BINARY_TYPE;
      // if (!file.type.includes("image")) {
      //   return showAlert({
      //     type: ERROR_TYPE,
      //     message: INCORRECT_FILE_TYPE,
      //   });
      // }
      // const fileSizeInMB = file.size / (1024 * 1024); // Convert bytes to megabytes
      // if (fileSizeInMB > 1) {
      //   showAlert({
      //     type: ERROR_TYPE,
      //     message: FILE_SIZE_ERROR,
      //   });
      //   return;
      // }
      const reader = new FileReader();
      reader.onload = async (e) => {
        const arrayBuffer = e.target.result;
        // Convert ArrayBuffer to Blob
        const file_obj = new Blob([arrayBuffer], { type: fileType });
        const body = {
          fileName,
          fileType,
          file_obj,
        };
        if (binaryData?.filePath) {
          body.op = "update";
          body.filePath = binaryData.filePath;
        }
        storageSDKServices
          .uploadFile(body)
          .then((response) => {
            if (response.status === "success") {
              setBinaryData({
                fileName,
                fileType,
                ...response.result,
              });
              updateHeadersWithContentType(fileType);
            }
          })
          .catch(() => {
            showAlert({
              type: "error",
              message:
                "An error occured while uploading the file. Please try again.",
            });
            setBinaryData(null);
          });
      };
      reader.readAsArrayBuffer(file);
    }
  };

  const handleKeyChange = (rowIndex, value, isFormData = true) => {
    if (isFormData) {
      setFormGridData((prev) => {
        const newData = [...prev];
        newData[rowIndex] = {
          ...newData[rowIndex],
          key: value,
        };
        if (rowIndex === newData.length - 1) {
          newData.push({
            rowid: crypto.randomUUID(),
            key: "",
            value: { type: "fx", blocks: [] },
            valueStr: "",
          });
        }
        return newData;
      });
    } else {
      setUrlEncodedGridData((prev) => {
        const newData = [...prev];
        newData[rowIndex] = {
          ...newData[rowIndex],
          key: value,
        };
        if (rowIndex === newData.length - 1) {
          newData.push({
            rowid: crypto.randomUUID(),
            key: "",
            value: { type: "fx", blocks: [] },
            valueStr: "",
          });
        }
        return newData;
      });
    }
  };

  const handleValueChange = (rowIndex, data, dataStr, isFormData = true) => {
    if (isFormData) {
      setFormGridData((prev) => {
        const newData = [...prev];
        newData[rowIndex] = {
          ...newData[rowIndex],
          value: {
            type: "fx",
            blocks: data,
          },
          valueStr: dataStr,
        };
        if (rowIndex === newData.length - 1) {
          newData.push({
            rowid: crypto.randomUUID(),
            key: "",
            value: { type: "fx", blocks: [] },
            valueStr: "",
          });
        }
        return newData;
      });
    } else {
      setUrlEncodedGridData((prev) => {
        const newData = [...prev];
        newData[rowIndex] = {
          ...newData[rowIndex],
          value: {
            type: "fx",
            blocks: data,
          },
          valueStr: dataStr,
        };
        if (rowIndex === newData.length - 1) {
          newData.push({
            rowid: crypto.randomUUID(),
            key: "",
            value: { type: "fx", blocks: [] },
            valueStr: "",
          });
        }
        return newData;
      });
    }
  };

  const handleDescriptionChange = (rowIndex, value, isFormData = true) => {
    if (isFormData) {
      setFormGridData((prev) => {
        const newData = [...prev];
        newData[rowIndex] = {
          ...newData[rowIndex],
          default: value,
        };
        if (rowIndex === newData.length - 1) {
          newData.push({
            rowid: crypto.randomUUID(),
            key: "",
            value: { type: "fx", blocks: [] },
            valueStr: "",
          });
        }
        return newData;
      });
    } else {
      setUrlEncodedGridData((prev) => {
        const newData = [...prev];
        newData[rowIndex] = {
          ...newData[rowIndex],
          default: value,
        };
        if (rowIndex === newData.length - 1) {
          newData.push({
            rowid: crypto.randomUUID(),
            key: "",
            value: { type: "fx", blocks: [] },
            valueStr: "",
          });
        }
        return newData;
      });
    }
  };

  // Add an empty row if there are no form data or URL encoded data
  useEffect(() => {
    const hasEmptyFormRow = formGridData.some((row) => isEmptyRow(row));
    const hasEmptyFormUrlEncodedRow = urlencodedGridData.some((row) =>
      isEmptyRow(row)
    );
    if (
      bodyType === RequestBodyType.FORM_DATA &&
      (formGridData.length === 0 ||
        (formGridData.length > 0 && !hasEmptyFormRow))
    ) {
      formGridAddRow();
    } else if (
      bodyType === RequestBodyType.X_WWW_FORM_URL_ENCODED &&
      (urlencodedGridData.length === 0 ||
        (urlencodedGridData.length > 0 && !hasEmptyFormUrlEncodedRow))
    ) {
      urlencodedAddRow();
    }
  }, [
    bodyType,
    formGridAddRow,
    formGridData,
    urlencodedAddRow,
    urlencodedGridData,
  ]);

  return (
    <div className={classes["body-panel"]} data-testid="body-panel">
      <RadioGroup value={bodyType} onChange={handleBodyTypeChange} row>
        <>
          {radioGroupData.map((data, index) => (
            <Radio
              key={`${data.labelText}_${index}`}
              labelText={data.labelText}
              formControlLabelProps={{
                value: data.value,
                sx: {
                  "& .Mui-checked": {
                    color: "#000 !important",
                  },
                },
              }}
              radioProps={{
                "data-testid": `http-configure-body-type-${data.labelText}`,
              }}
              labelProps={{ variant: "body1" }}
            />
          ))}
        </>
      </RadioGroup>
      <div
        style={{
          display: "flex",
          gap: "1rem",
          alignItems: "center",
          justifyContent: "flex-start",
        }}
      >
        {bodyType === RequestBodyType.RAW && (
          <ODSAutoComplete
            id="raw-data-type"
            getOptionLabel={(option) => option.label}
            isOptionEqualToValue={(option, value) => {
              return option.id === value.id;
            }}
            fullWidth
            variant="black"
            value={subType}
            options={subTypeOptions}
            sx={{
              "min-width": "13rem",
            }}
            data-testid="http-configure-body-raw-mode"
            onChange={handleSubTypeChange}
            required
          />
        )}
        {bodyType === RequestBodyType.RAW &&
          subType === RequestRawDataType.JSON &&
          rawData?.type !== "fx" && (
            <ODSButton
              variant="black-text"
              label="IMPORT JSON"
              size="large"
              onClick={() => {
                setShowJSONDialog(true);
              }}
              sx={{
                minWidth: "10rem",
              }}
            />
          )}
      </div>

      {bodyType === RequestBodyType.NONE && (
        <div className={classes["none-body-container"]}>
          <ODSLabel sx={{ font: "var(--h6)" }}>
            This request does not have body
          </ODSLabel>
        </div>
      )}

      {bodyType === RequestBodyType.FORM_DATA && (
        <div className={classes["radio-body-container"]}>
          <table className={classes["body-table"]}>
            <thead>
              <tr>
                <th>KEY</th>
                <th>VALUE</th>
                <th>DESCRIPTION</th>
                <th className={classes["action-column"]}></th>
              </tr>
            </thead>
            <tbody>
              {formGridData.map((row, rowIndex) => (
                <tr key={row.rowid} className={classes["data-row"]}>
                  <td
                    className={classes["key-cell"]}
                    onClick={() => {
                      if (
                        editingCell?.rowIndex !== rowIndex ||
                        editingCell?.colKey !== "key"
                      ) {
                        setEditingCell({ rowIndex, colKey: "key" });
                      }
                    }}
                  >
                    <ODSTextField
                      value={row.key || ""}
                      fullWidth
                      hideBorders
                      placeholder="Enter key"
                      onChange={(e) =>
                        handleKeyChange(rowIndex, e.target.value, true)
                      }
                      autoFocus={
                        editingCell?.rowIndex === rowIndex &&
                        editingCell?.colKey === "key"
                      }
                      className="black"
                      sx={{
                        "& .MuiOutlinedInput-root ": {
                          background: "transparent",
                        },
                      }}
                      inputProps={{
                        "data-testid": `http-configure-body-key-${rowIndex}`,
                      }}
                    />
                  </td>
                  <td
                    className={classes["value-cell"]}
                    onClick={() => {
                      if (
                        editingCell?.rowIndex !== rowIndex ||
                        editingCell?.colKey !== "value"
                      ) {
                        setEditingCell({ rowIndex, colKey: "value" });
                      }
                    }}
                  >
                    <FormulaBar
                      hideBorders
                      key={rowIndex}
                      onInputContentChanged={(data, dataStr) =>
                        handleValueChange(rowIndex, data, dataStr, true)
                      }
                      placeholder="Enter value"
                      wrapContent={
                        editingCell?.rowIndex === rowIndex &&
                        editingCell?.colKey === "value"
                      }
                      defaultInputContent={row.value?.blocks || []}
                      variables={variables}
                      data-testid={`body-value-${rowIndex}`}
                      slotProps={{
                        container: {
                          style: {
                            maxHeight: "10rem",
                            overflow: "auto",
                          },
                        },
                        content: {
                          "data-testid": `http-configure-body-value-${rowIndex}`,
                        },
                      }}
                    />
                  </td>
                  <td
                    className={classes["description-cell"]}
                    onClick={() => {
                      if (
                        editingCell?.rowIndex !== rowIndex ||
                        editingCell?.colKey !== "description"
                      ) {
                        setEditingCell({ rowIndex, colKey: "description" });
                      }
                    }}
                  >
                    <ODSTextField
                      value={row.default || ""}
                      fullWidth
                      hideBorders
                      className="black"
                      placeholder="Enter description"
                      sx={{
                        "& .MuiOutlinedInput-root ": {
                          background: "transparent",
                        },
                      }}
                      onChange={(e) =>
                        handleDescriptionChange(rowIndex, e.target.value, true)
                      }
                      inputProps={{
                        "data-testid": `http-configure-body-description-${rowIndex}`,
                      }}
                    />
                  </td>
                  <td className={classes["delete-cell"]}>
                    <div className={classes["delete-icon-container"]}>
                      {rowIndex === formGridData.length - 1 ? null : (
                        <ODSIcon
                          outeIconName="OUTETrashIcon"
                          onClick={() => deleteRow(rowIndex)}
                          outeIconProps={{
                            "data-testid": `http-configure-body-delete-${rowIndex}`,
                            sx: {
                              color: "#212121",
                            },
                          }}
                        />
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {bodyType === RequestBodyType.X_WWW_FORM_URL_ENCODED && (
        <div className={classes["radio-body-container"]}>
          <table className={classes["body-table"]}>
            <thead>
              <tr>
                <th>KEY</th>
                <th>VALUE</th>
                <th>DESCRIPTION</th>
                <th className={classes["action-column"]}></th>
              </tr>
            </thead>
            <tbody>
              {urlencodedGridData.map((row, rowIndex) => (
                <tr key={row.rowid} className={classes["data-row"]}>
                  <td
                    className={classes["key-cell"]}
                    onClick={() => {
                      if (
                        editingCell?.rowIndex !== rowIndex ||
                        editingCell?.colKey !== "key"
                      ) {
                        setEditingCell({ rowIndex, colKey: "key" });
                      }
                    }}
                  >
                    <ODSTextField
                      value={row.key || ""}
                      fullWidth
                      hideBorders
                      placeholder="Enter key"
                      onChange={(e) =>
                        handleKeyChange(rowIndex, e.target.value, false)
                      }
                      className="black"
                      sx={{
                        "& .MuiOutlinedInput-root ": {
                          background: "transparent",
                        },
                      }}
                      autoFocus={
                        editingCell?.rowIndex === rowIndex &&
                        editingCell?.colKey === "key"
                      }
                      inputProps={{
                        "data-testid": `http-configure-body-key-${rowIndex}`,
                      }}
                    />
                  </td>
                  <td
                    className={classes["value-cell"]}
                    onClick={() => {
                      if (
                        editingCell?.rowIndex !== rowIndex ||
                        editingCell?.colKey !== "value"
                      ) {
                        setEditingCell({ rowIndex, colKey: "value" });
                      }
                    }}
                  >
                    <FormulaBar
                      hideBorders
                      key={rowIndex}
                      onInputContentChanged={(data, dataStr) =>
                        handleValueChange(rowIndex, data, dataStr, false)
                      }
                      placeholder="Enter value"
                      wrapContent={
                        editingCell?.rowIndex === rowIndex &&
                        editingCell?.colKey === "value"
                      }
                      defaultInputContent={row.value?.blocks || []}
                      variables={variables}
                      data-testid={`body-value-${rowIndex}`}
                      slotProps={{
                        container: {
                          style: {
                            maxHeight: "10rem",
                            overflow: "auto",
                          },
                        },
                        content: {
                          "data-testid": `http-configure-body-value-${rowIndex}`,
                        },
                      }}
                    />
                  </td>
                  <td
                    className={classes["description-cell"]}
                    onClick={() => {
                      if (
                        editingCell?.rowIndex !== rowIndex ||
                        editingCell?.colKey !== "description"
                      ) {
                        setEditingCell({ rowIndex, colKey: "description" });
                      }
                    }}
                  >
                    <ODSTextField
                      value={row.default || ""}
                      fullWidth
                      hideBorders
                      className="black"
                      placeholder="Enter description"
                      sx={{
                        "& .MuiOutlinedInput-root ": {
                          background: "transparent",
                        },
                      }}
                      onChange={(e) =>
                        handleDescriptionChange(rowIndex, e.target.value, false)
                      }
                      inputProps={{
                        "data-testid": `http-configure-body-description-${rowIndex}`,
                      }}
                    />
                  </td>
                  <td className={classes["delete-cell"]}>
                    <div className={classes["delete-icon-container"]}>
                      {rowIndex === urlencodedGridData.length - 1 ? null : (
                        <ODSIcon
                          outeIconName="OUTETrashIcon"
                          onClick={() => deleteRow(rowIndex)}
                          outeIconProps={{
                            "data-testid": `http-configure-body-delete-${rowIndex}`,
                            sx: {
                              color: "#212121",
                            },
                          }}
                        />
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {bodyType === RequestBodyType.BINARY && (
        <div className={classes["binary-body-container"]}>
          {binaryData?.fileName && (
            <>
              <a href={binaryData?.cdn} download={binaryData?.fileName}>
                {binaryData?.fileName}
              </a>
              <ODSIcon
                outeIconName="OUTETrashIcon"
                onClick={deleteBinaryFile}
              />
            </>
          )}
          <ODSButton
            type="file"
            variant="black"
            onFileChanged={fileUploadHandler}
            label="Upload File"
          />
        </div>
      )}

      {bodyType === RequestBodyType.RAW && (
        <div className={classes["raw-body-container"]}>
          {(rawData?.type === "fx" &&
            subType.id === RequestRawDataType.JSON.id) ||
          subType.id !== RequestRawDataType.JSON.id ? (
            <FormulaBar
              onInputContentChanged={(fxContent, contentStr) => {
                setRawData({ type: "fx", blocks: fxContent, text: contentStr });
              }}
              defaultInputContent={rawData?.blocks?.slice() || []}
              variables={variables}
              style={{ height: "100%" }}
              slotProps={{
                content: { "data-testid": "http-configure-body-raw-content" },
              }}
              wrapContent
            />
          ) : (
            <InputGridV2
              ref={inputGridRef}
              variables={variables}
              onGridDataChange={(data) => {
                setRawData(data);
              }}
              initialValue={JSONGridData}
              isValueMode
            />
          )}
        </div>
      )}
      <ODSDialog
        open={showJSONDialog}
        onClose={() => {
          onCloseJSONDialog();
        }}
        showFullscreenIcon={false}
        hideBackdrop={false}
        dividers={true}
        draggable={false}
        dialogWidth="800px"
        dialogTitle={
          <div className={classes["dialog-title"]}>
            <ODSIcon outeIconName="OUTEInfoIcon" />
            Import Json
          </div>
        }
        dialogContent={
          <JsonDialogContent
            onClose={onCloseJSONDialog}
            onModify={modifyJSONHandler}
          />
        }
      />
    </div>
  );
};

export default BodyPanel;
