// Converted from Emotion css to plain JavaScript style objects
export const styles = {
  container: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "1rem",
    backgroundColor: "#f5f7f8",
    position: "relative",
    overflowX: "hidden",
  },
  contentWrapper: {
    width: "100%",
    maxWidth: "32rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1.5rem",
    // Media query handled via className or inline style override
  },
  iconContainer: {
    display: "flex",
    height: "4rem",
    width: "4rem",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "9999px",
    backgroundColor: "#fef3c7",
    color: "#f59e0b",
  },
  content: {
    display: "flex",
    maxWidth: "28rem",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.5rem",
    textAlign: "center",
  },
  heading: {
    fontSize: "1.25rem",
    fontWeight: 700,
    lineHeight: 1.2,
    color: "#18181b",
    margin: 0,
  },
  description: {
    fontSize: "0.875rem",
    lineHeight: 1.5,
    color: "#71717a",
    margin: 0,
  },
  buttonContainer: {
    display: "flex",
    minWidth: "84px",
    width: "100%",
    maxWidth: "280px",
    justifyContent: "center",
  },
  divider: {
    width: "100%",
    maxWidth: "28rem",
    borderTop: "1px solid rgba(63, 63, 70, 0.1)",
    paddingTop: "1rem",
    marginTop: "0.5rem",
  },
  detailsContainer: {
    width: "100%",
    maxWidth: "28rem",
    display: "flex",
    flexDirection: "column",
  },
  detailsSummary: {
    display: "flex",
    cursor: "pointer",
    listStyle: "none",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "1rem",
    padding: "0.5rem 0",
    // Webkit details marker handled via CSS class
  },
  detailsSummaryText: {
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "#3f3f46",
  },
  detailsIcon: {
    color: "#71717a",
    transition: "transform 0.2s",
    fontSize: "1.25rem",
    lineHeight: 1,
    // details[open] state handled via className
  },
  detailsContentWrapper: {
    overflow: "hidden",
  },
  detailsContent: {
    borderRadius: "0.5rem",
    backgroundColor: "#f4f4f5",
    padding: "1rem",
    fontSize: "0.75rem",
    color: "#3f3f46",
  },
  detailsPre: {
    margin: 0,
    whiteSpace: "pre-wrap",
    fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace',
    fontSize: "0.75rem",
    lineHeight: 1.5,
  },
};
