import { PLUS_ICON } from "./Icons/commonIcons";
import {
	CALENDER_ICON,
	CONTACT_PHONE_ICON,
	CURRENCY_ICON,
	DROPDOWN_STATIC_ICON,
	FILE_UPLOAD_ICON,
	HASH_ICON,
	LOCATION_ICON,
	LONG_TEXT_ICON,
	MAIL_OUTLINE_ICON,
	MCQ_ICON,
	PHONE_ICON,
	RANKING,
	SHORT_TEXT_ICON,
	SIGNATURE_ICON,
	SINGLE_CHOICE_ICON,
	TIME_ICON,
	YES_NO_ICON,
	FORMULA_ICON,
	ENRICHMENT_ICON,
	LIST_ICON,
	CREATED_TIME_ICON,
	RATING_ICON,
	OPINION_SCALE_ICON,
	SLIDER_ICON,
} from "./Icons/questionTypeIcons";

export type QuestionTypeIconKey =
	| "SHORT_TEXT"
	| "LONG_TEXT"
	| "DATE"
	| "DROP_DOWN"
	| "ADDRESS"
	| "FILE_PICKER"
	| "NUMBER"
	| "ZIP_CODE"
	| "MCQ"
	| "SCQ"
	| "PHONE_NUMBER"
	| "CURRENCY"
	| "TIME"
	| "YES_NO"
	| "EMAIL"
	| "DROP_DOWN_STATIC"
	| "ADD"
	| "SIGNATURE"
	| "RANKING"
	| "FORMULA"
	| "ENRICHMENT"
	| "LIST"
	| "CREATED_TIME"
	| "RATING"
	| "SLIDER"
	| "OPINION_SCALE";

const QUESTION_TYPE_ICON_MAPPING: Record<QuestionTypeIconKey, string> = {
	SHORT_TEXT: SHORT_TEXT_ICON,
	LONG_TEXT: LONG_TEXT_ICON,
	DATE: CALENDER_ICON,
	DROP_DOWN: DROPDOWN_STATIC_ICON,
	ADDRESS: CONTACT_PHONE_ICON,
	FILE_PICKER: FILE_UPLOAD_ICON,
	NUMBER: HASH_ICON,
	ZIP_CODE: LOCATION_ICON,
	MCQ: MCQ_ICON,
	SCQ: SINGLE_CHOICE_ICON,
	PHONE_NUMBER: PHONE_ICON,
	CURRENCY: CURRENCY_ICON,
	TIME: TIME_ICON,
	YES_NO: YES_NO_ICON,
	EMAIL: MAIL_OUTLINE_ICON,
	DROP_DOWN_STATIC: DROPDOWN_STATIC_ICON,
	ADD: PLUS_ICON,
	SIGNATURE: SIGNATURE_ICON,
	RANKING: RANKING,
	FORMULA: FORMULA_ICON,
	ENRICHMENT: ENRICHMENT_ICON,
	LIST: LIST_ICON,
	CREATED_TIME: CREATED_TIME_ICON,
	RATING: RATING_ICON,
	SLIDER: SLIDER_ICON,
	OPINION_SCALE: OPINION_SCALE_ICON,
};

export default QUESTION_TYPE_ICON_MAPPING;
