const SOCKET_EXECUTE_NODE_INIT_KEY = "execute_node_init";
const SOCKET_EXECUTE_NODE_ERROR_KEY = "execute_node_error";
const SOCKET_EXECUTE_NODE_RESULT_KEY = "execute_node_result";
const SOCKET_BEGIN_NODE_KEY = "begin_node";
const SOCKET_NODE_INPUT_KEY = "node_input";
const SOCKET_NODE_OUTPUT_KEY = "node_output";
const SOCKET_NODE_LOG_KEY = "node_log";
const SOCKET_END_NODE_KEY = "end_node";
const SOCKET_ABORT_NODE_KEY = "abort_node";
const SOCKET_ABORT_NODE_ERROR_KEY = "abort_node_error";
const SOCKET_ABORT_NODE_RESULT_KEY = "abort_node_result";

const SOCKET_PRE_LOG_TYPE = "pre_log";
const SOCKET_POST_LOG_TYPE = "post_log";

export const SOCKET_EVENTS = {
  SOCKET_EXECUTE_NODE_INIT_KEY,
  SOCKET_EXECUTE_NODE_ERROR_KEY,
  SOCKET_EXECUTE_NODE_RESULT_KEY,
  SOCKET_BEGIN_NODE_KEY,
  SOCKET_NODE_INPUT_KEY,
  SOCKET_NODE_OUTPUT_KEY,
  SOCKET_NODE_LOG_KEY,
  SOCKET_END_NODE_KEY,
  SOCKET_ABORT_NODE_KEY,
  SOCKET_ABORT_NODE_ERROR_KEY,
  SOCKET_ABORT_NODE_RESULT_KEY,
  SOCKET_PRE_LOG_TYPE,
  SOCKET_POST_LOG_TYPE,
};
