export const dummyVariables = {
  NODE: [
    {
      key: "1698821223565",
      src: "/static/media/input-setup.6bc4e1375793765dd9b1e7463776f5c9.svg",
      name: "Input",
      description: "",
      type: "Input Setup",
      template: "startNode",
      background: "rgb(33, 150, 243)",
      foreground: "#fff",
      viewSpot: "0 0.5",
      location: "-896 -8.500000000000057",
      errors: [],
      go_data: {
        inputs: [
          {
            key: "hello",
            value: "",
            type: "STRING",
            default: "world",
            required: false,
            validation: null,
          },
        ],
        errors: [],
        output: {
          schema: {
            schema: [
              {
                key: "hello",
                sample_value: "world",
                path: ["hello"],
                pathStr: "hello",
                type: "string",
              },
            ],
            path: [],
            keys: ["hello"],
            flattened_schema: [
              {
                key: "hello",
                sample_value: "world",
                path: ["hello"],
                pathStr: "hello",
                type: "string",
              },
            ],
          },
        },
      },
      data: {
        schema: {
          schema: [
            {
              key: "hello",
              sample_value: "world",
              path: ["hello"],
              pathStr: "hello",
              type: "string",
            },
          ],
          path: [],
          keys: ["hello"],
          flattened_schema: [
            {
              key: "hello",
              sample_value: "world",
              path: ["hello"],
              pathStr: "hello",
              type: "string",
            },
          ],
        },
      },
    },
  ],
  LOCAL: [
    {
      _id: "k_OU86WDA",
      name: "Name",
      data_type: "STRING",
      mode: "LOCAL",
      workspace_id: "PhgvxiJ7o",
      asset_id: "UVEqfJmap",
      parent_id: "32Md3eIeO",
      implemented_asset_ids: [],
      default: "Pratik",
      state: "ACTIVE",
      created_at: "2023-09-08T13:04:24.994Z",
      updated_at: "2023-11-23T09:20:49.747Z",
      __v: 0,
      env: {
        Env_3: "Pratik",
        Env_4: "Pratik",
        Env_4_cawdfawfawfawfawfawfawfawfawfwfwfaw: "Pratik",
        Env_4_cawdfawfawfawfawfawfaw: "Pratik",
        Env_4_cawdfawfawfawfawfawfawasEnv_4_cawdfawfawfawfawfawfawas: "Pratik",
        Env_18: "Pratik",
        NEw_env: "Pratik",
        kolo: "Pratik",
        Env_134: "Pratik",
      },
      implemented_assets: [],
    },
    {
      _id: "k-hl8nWTt",
      name: "Age",
      data_type: "INT",
      mode: "LOCAL",
      workspace_id: "PhgvxiJ7o",
      asset_id: "UVEqfJmap",
      parent_id: "32Md3eIeO",
      implemented_asset_ids: [],
      default: "23",
      state: "ACTIVE",
      created_at: "2023-09-11T08:05:26.351Z",
      updated_at: "2023-11-23T09:20:49.747Z",
      __v: 0,
      env: {
        Env_3: "23",
        Env_4: "23",
        Env_4_cawdfawfawfawfawfawfawfawfawfwfwfaw: "23",
        Env_4_cawdfawfawfawfawfawfaw: "23",
        Env_4_cawdfawfawfawfawfawfawasEnv_4_cawdfawfawfawfawfawfawas: "23",
        Env_18: "23",
        NEw_env: "23",
        kolo: "23",
        Env_134: "23",
      },
      implemented_assets: [],
    },
    {
      _id: "bpgzhzTyF",
      name: "One",
      data_type: "STRING",
      mode: "LOCAL",
      workspace_id: "PhgvxiJ7o",
      asset_id: "IgEP1aH9f",
      parent_id: "32Md3eIeO",
      implemented_asset_ids: [],
      default: "",
      env: {
        kolo: "qwrqw",
      },
      state: "ACTIVE",
      created_at: "2023-11-23T11:40:27.127Z",
      updated_at: "2023-11-23T11:40:27.128Z",
      __v: 0,
      implemented_assets: [],
    },
    {
      _id: "OqffSZurQ",
      name: "Three",
      data_type: "STRING",
      mode: "LOCAL",
      workspace_id: "PhgvxiJ7o",
      asset_id: "OJJ-ekQ18",
      parent_id: "32Md3eIeO",
      implemented_asset_ids: [],
      default: "",
      env: {
        kolo: "dasdadaw",
      },
      state: "ACTIVE",
      created_at: "2023-11-23T11:40:53.309Z",
      updated_at: "2023-11-23T11:40:53.310Z",
      __v: 0,
      implemented_assets: [],
    },
  ],
  GLOBAL: [],
  env: [
    {
      _id: "mHUx1bCq0",
      name: "NEw_env",
      asset_id: "32Md3eIeO",
      workspace_id: "PhgvxiJ7o",
      state: "ACTIVE",
      created_at: "2023-11-23T08:42:06.096Z",
      updated_at: "2023-11-23T08:42:06.096Z",
    },
    {
      _id: "pnMd5MaGa",
      name: "kolo",
      asset_id: "32Md3eIeO",
      workspace_id: "PhgvxiJ7o",
      state: "ACTIVE",
      created_at: "2023-11-23T08:45:21.917Z",
      updated_at: "2023-11-23T08:45:21.918Z",
    },
  ],
};
