export const connectionStyles = {
  container: {
    display: "flex",
    gap: "0.75em",
    alignItems: "center",
  },
  dropDownContainer: {
    position: "relative",
    display: "flex",
    padding: "0.625em",
    gap: "0.625em",
    flex: "1 0 0",
    borderRadius: "0.75em",
    border: "0.046875em solid rgba(0, 0, 0, 0.20)",
    background: "#FFF",
    boxShadow: "0px 0px 0px 0px rgba(0, 0, 0, 0.00) inset",
    alignItems: "center",
    cursor: "pointer",
  },
  imageStyles: {
    width: "1.5em",
  },
  dropDownText: {
    display: "flex",
    flex: "1 0 0",
    color: "#000",
    fontFamily: "Inter, sans-serif",
    fontSize: "1.25em",
    fontStyle: "normal",
    fontWeight: 400,
    letterSpacing: "0.015625em",
  },
  textFieldStyle: {
    height: "3em",
    color: "#000",
    fontFamily: "Inter",
    fontSize: "0.9em",
    fontStyle: "normal",
    fontWeight: 400,
    letterSpacing: "0.01125em",
  },
  odsButtonStyle: {
    width: "100%",
    padding: "1em 1em 0em 1em",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "8px",
    background: "#fff",
    borderTop: "1px solid rgba(0, 0, 0, 0.12)",
    boxSizing: "border-box",
  },
  button: (isDisabled?: boolean) => {
    return {
      cursor: isDisabled ? "auto" : "pointer",
      border: "none",
      display: "flex",
      height: "3em",
      padding: "1.8em 1em",
      alignItems: "center",
      gap: "1em",
      borderRadius: "0.75em",
      color: isDisabled ? "#607D8B" : "#FFF",
      background: isDisabled ? "#CFD8DC" : "#2196F3",
      fontSize: "1em !important",
    };
  },
  buttonText: {
    textAlign: "center",
    fontFamily: "Inter",
    fontSize: "0.875em",
    fontStyle: "normal",
    fontWeight: 600,
    letterSpacing: "0.078125em",
    textTransform: "uppercase",
  },
  listBoxStyles: {
    position: "absolute",
    top: "110%",
    left: 0,
    background: "#000035",
    color: "white",
    height: "200px",
    width: "calc(100% - 20px)",
    zIndex: 10,
    borderRadius: "10px",
    padding: "10px",
    overflowY: "scroll",
    animation: "slideDown 0.5s ease forwards",
    transformOrigin: "top",
    opacity: 0,
    visibility: "hidden",
    "@keyframes slideDown": {
      "0%": {
        opacity: 0,
        transform: "translateY(0px)",
        visibility: "hidden",
      },
      "50%": {
        opacity: 0.5,
        visibility: "visible",
      },
      "100%": {
        opacity: 1,
        transform: "translateY(0)",
        visibility: "visible",
      },
    },
  },
  odsInput: {
    width: "95% !important",
    padding: "0 0.5em !important",
    flexGrow: "0 !important",
    color: "#000",
    fontFamily: "Inter",
    fontSize: "unset !important",
    fontStyle: "normal",
    fontWeight: 400,
    letterSpacing: "0.01125em",
  },
} as const;
