export const variables = {
  NODE: [
    {
      key: "1",
      name: "Short Text",
      type: "SHORT_TEXT",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#FF5252",
      module: "Question",
      go_data: {
        question: "<p>What is your full name?</p>",
        description: "Please provide your first and last name.",
        type: "SHORT_TEXT",
        module: "Question",
        buttonLabel: "Next",
        value: "",
        placeholder: "Enter your answer",
        errors: {
          charLimitError: "",
        },
        settings: {
          questionAlignment: "flex-start",
          required: false,
          maskResponse: false,
          textTransformation: {
            isActive: false,
            case: "NONE",
          },
          toolTipText: "",
          minChar: "1",
          maxChar: "100",
          regex: {
            value: "",
            error: "",
          },
          accessKey: "",
        },
        response_type: "STRING",
        id: "1",
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "string",
                    default: "",
                    path: ["response"],
                    pathStr: "response",
                  },
                ],
              },
            ],
            path: [],
            keys: ["response"],
            flattened_schema: [
              {
                key: "response",
                type: "string",
                default: "",
                path: ["response"],
                pathStr: "response",
              },
            ],
          },
        },
        last_updated: 1752826070619,
      },
      meta: {
        isMultiQuestionSupported: true,
        search_keys: [
          "Small Input",
          "Text Field",
          "One-Liner",
          "Single Line Text",
          "Input Box",
          "Name",
          "Full Name",
          "First Name",
          "Url",
          "Website",
        ],
      },
      description: "What is your full name?",
      location: "0 0",
      errors: [],
      warnings: [],
      nodeNumber: 1,
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "string",
                  default: "",
                  path: ["response"],
                  pathStr: "response",
                },
              ],
            },
          ],
          path: [],
          keys: ["response"],
          flattened_schema: [
            {
              key: "response",
              type: "string",
              default: "",
              path: ["response"],
              pathStr: "response",
            },
          ],
        },
      },
    },
    {
      key: "2",
      name: "Email",
      type: "EMAIL",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#6780D8",
      module: "Question",
      go_data: {
        question: "<p>What is your email address?</p>",
        description: "Please enter a valid email address for follow-up.",
        type: "EMAIL",
        module: "Question",
        buttonLabel: "Next",
        value: "",
        placeholder: "example@example.com",
        settings: {
          questionAlignment: "flex-start",
          required: false,
          noDuplicates: true,
          confirmEmail: false,
          noFreeEmails: false,
          isReadOnly: false,
          prefill: false,
          verifyEmail: false,
          suggestDomains: [],
          accessKey: "",
          regex: {
            value: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
            error: "Please enter a valid email address.",
          },
          defaultValue: {
            type: "fx",
          },
        },
        id: "2",
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "any",
                    default: null,
                    path: ["response"],
                    pathStr: "response",
                  },
                ],
              },
            ],
            path: [],
            keys: ["response"],
            flattened_schema: [
              {
                key: "response",
                type: "any",
                default: null,
                path: ["response"],
                pathStr: "response",
              },
            ],
          },
        },
        last_updated: 1754476762256,
      },
      meta: {
        isMultiQuestionSupported: true,
        search_keys: [
          "Email Address",
          "Contact Email",
          "Email Input",
          "Email Field",
          "Email Box",
        ],
      },
      description: "What is your email address?",
      location: "320 0",
      errors: [],
      warnings: [],
      nodeNumber: 2,
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "any",
                  default: null,
                  path: ["response"],
                  pathStr: "response",
                },
              ],
            },
          ],
          path: [],
          keys: ["response"],
          flattened_schema: [
            {
              key: "response",
              type: "any",
              default: null,
              path: ["response"],
              pathStr: "response",
            },
          ],
        },
      },
    },
    {
      key: "3",
      name: "Dropdown Static",
      type: "DROP_DOWN_STATIC",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#4694E2",
      module: "Question",
      go_data: {
        question: "<p>Which product did you purchase?</p>",
        description: "Select the product you are providing feedback on.",
        type: "DROP_DOWN_STATIC",
        module: "Question",
        buttonLabel: "Next",
        value: "value",
        options: [
          "Skybags Paratrip suitcase",
          "Skybags Trooper",
          "OxygenOS 14 update",
        ],
        errors: {
          defaultChoiceError: "",
        },
        placeholder: "Type or select an option",
        settings: {
          questionAlignment: "flex-start",
          required: false,
          randomize: false,
          isAlphabeticallyArranged: false,
          includeOtherOption: false,
          defaultChoice: [],
          selectionType: "Single",
          exactNumber: "1",
          minNumber: "1",
          maxNumber: "2",
          accessKey: "",
          enableMap: false,
        },
        id: "3",
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "string",
                    default: "value",
                    path: ["response"],
                    pathStr: "response",
                  },
                ],
              },
            ],
            path: [],
            keys: ["response"],
            flattened_schema: [
              {
                key: "response",
                type: "string",
                default: "value",
                path: ["response"],
                pathStr: "response",
              },
            ],
          },
        },
        last_updated: 1752826062333,
      },
      meta: {
        isQuestionRepeatorSupported: true,
        search_keys: [
          "Select Menu",
          "Dropdown List",
          "Choose From Options",
          "Select Field",
          "Pick List",
          "Collection",
        ],
      },
      description: "Which product did you purchase?",
      location: "640 0",
      errors: [],
      warnings: [],
      nodeNumber: 3,
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "string",
                  default: "value",
                  path: ["response"],
                  pathStr: "response",
                },
              ],
            },
          ],
          path: [],
          keys: ["response"],
          flattened_schema: [
            {
              key: "response",
              type: "string",
              default: "value",
              path: ["response"],
              pathStr: "response",
            },
          ],
        },
      },
    },
    {
      key: "4",
      name: "Ranking",
      type: "RANKING",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#9721F3",
      module: "Question",
      go_data: {
        question:
          "<p>How effective was the TSA lock feature on your Skybags Paratrip suitcase?</p>",
        description:
          "Rate the effectiveness of the TSA lock from 1 (not effective) to 5 (very effective).",
        type: "RANKING",
        module: "Question",
        buttonLabel: "Next",
        options: [
          {
            id: "5c4fb661-176f-4ece-a2a1-8505eca2b4dc",
            rank: null,
            label: "Option 1",
          },
          {
            id: "3391fa08-f1d1-47a2-9565-0b3c6b2ff358",
            rank: null,
            label: "Option 2",
          },
          {
            id: "c0fd9147-969c-4363-8aed-0d776df284ae",
            rank: null,
            label: "Option 3",
          },
        ],
        value: [
          {
            id: "ranking-options_1",
            rank: 1,
            label: "test",
          },
        ],
        placeholder: "",
        settings: {
          questionAlignment: "flex-start",
          required: true,
          randomize: false,
          dynamicInput: {
            isActive: false,
            variable: {},
          },
          accessKey: "",
        },
        id: "4",
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "array",
                    default: [
                      {
                        id: "ranking-options_1",
                        rank: 1,
                        label: "test",
                      },
                    ],
                    path: ["response"],
                    pathStr: "[response]",
                    schema: [
                      {
                        type: "object",
                        schema: [
                          {
                            key: "id",
                            type: "string",
                            default: "ranking-options_1",
                            path: ["response", "id"],
                            pathStr: "[response].id",
                          },
                          {
                            key: "rank",
                            type: "number",
                            default: 1,
                            path: ["response", "rank"],
                            pathStr: "[response].rank",
                          },
                          {
                            key: "label",
                            type: "string",
                            default: "test",
                            path: ["response", "label"],
                            pathStr: "[response].label",
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
            path: [],
            keys: [
              "response",
              "response.id",
              "response.rank",
              "response.label",
            ],
            flattened_schema: [
              {
                key: "response",
                type: "array",
                default: [
                  {
                    id: "ranking-options_1",
                    rank: 1,
                    label: "test",
                  },
                ],
                path: ["response"],
                pathStr: "[response]",
              },
            ],
          },
        },
        last_updated: 1752826062368,
      },
      meta: {
        search_keys: [
          "Priority Order",
          "Sort Options",
          "Rating Scale",
          "Order Selector",
          "List Ranking",
        ],
      },
      description:
        "How effective was the TSA lock feature on your Skybags Paratrip suitcase?",
      location: "960 0",
      errors: [],
      warnings: [],
      nodeNumber: 4,
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "array",
                  default: [
                    {
                      id: "ranking-options_1",
                      rank: 1,
                      label: "test",
                    },
                  ],
                  path: ["response"],
                  pathStr: "[response]",
                  schema: [
                    {
                      type: "object",
                      schema: [
                        {
                          key: "id",
                          type: "string",
                          default: "ranking-options_1",
                          path: ["response", "id"],
                          pathStr: "[response].id",
                        },
                        {
                          key: "rank",
                          type: "number",
                          default: 1,
                          path: ["response", "rank"],
                          pathStr: "[response].rank",
                        },
                        {
                          key: "label",
                          type: "string",
                          default: "test",
                          path: ["response", "label"],
                          pathStr: "[response].label",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          path: [],
          keys: ["response", "response.id", "response.rank", "response.label"],
          flattened_schema: [
            {
              key: "response",
              type: "array",
              default: [
                {
                  id: "ranking-options_1",
                  rank: 1,
                  label: "test",
                },
              ],
              path: ["response"],
              pathStr: "[response]",
            },
          ],
        },
      },
    },
    {
      key: "5",
      name: "Yes/No",
      type: "YES_NO",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#212121",
      module: "Question",
      go_data: {
        question:
          "<p>Did the expandable storage feature of the Skybags Trooper meet your travel needs?</p>",
        description:
          "Indicate whether the expandable storage was sufficient for your belongings.",
        type: "YES_NO",
        module: "Question",
        buttonLabel: "Next",
        options: ["Yes", "No"],
        value: "No",
        placeholder: "",
        settings: {
          questionAlignment: "flex-start",
          required: true,
          vertical: false,
          defaultChoice: "",
          accessKey: "",
          enableMap: false,
        },
        id: "5",
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "string",
                    default: "No",
                    path: ["response"],
                    pathStr: "response",
                  },
                ],
              },
            ],
            path: [],
            keys: ["response"],
            flattened_schema: [
              {
                key: "response",
                type: "string",
                default: "No",
                path: ["response"],
                pathStr: "response",
              },
            ],
          },
        },
        last_updated: 1752826062404,
      },
      meta: {
        isMultiQuestionSupported: true,
        isQuestionRepeatorSupported: true,
        search_keys: [
          "Binary Question",
          "Decision Box",
          "Toggle Input",
          "Confirm/Reject",
          "True/False Selector",
          "Boolean",
        ],
      },
      description:
        "Did the expandable storage feature of the Skybags Trooper meet your travel needs?",
      location: "1280 0",
      errors: [],
      warnings: [],
      nodeNumber: 5,
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "string",
                  default: "No",
                  path: ["response"],
                  pathStr: "response",
                },
              ],
            },
          ],
          path: [],
          keys: ["response"],
          flattened_schema: [
            {
              key: "response",
              type: "string",
              default: "No",
              path: ["response"],
              pathStr: "response",
            },
          ],
        },
      },
    },
    {
      key: "6",
      name: "Long Text",
      type: "LONG_TEXT",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#0D47A1",
      module: "Question",
      go_data: {
        question:
          "<p>What specific improvements would you suggest for the OxygenOS 14 update?</p>",
        description:
          "Please detail any features or aspects you believe could be enhanced.",
        type: "LONG_TEXT",
        module: "Question",
        buttonLabel: "Submit",
        value: "",
        placeholder: "Your answer here...",
        errors: {
          charLimitError: "",
        },
        settings: {
          questionAlignment: "flex-start",
          required: false,
          editorMode: false,
          textTransformation: {
            isActive: false,
            case: "NONE",
          },
          minChar: "0",
          maxChar: "500",
          regex: {
            value: "",
            error: "",
          },
          accessKey: "",
          rows: 4,
          defaultValue: {
            type: "fx",
            blocks: [
              {
                subCategory: "NODE",
                type: "NODE",
                subType: "What is your email address?",
                value: "What is your email address?",
                background: "#6780D8",
                foreground: "#fff",
                nodeNumber: 2,
                variableData: {
                  key: "response",
                  module: "Question",
                  type: "any",
                  sample_value: null,
                  default: null,
                  path: ["response"],
                  pathStr: "response",
                  nodeName: "What is your email address?",
                  nodeId: "2",
                  nodeType: "EMAIL",
                },
                blockId: "1906d205-b817-4a4e-aef1-72b46839b9c1",
              },
            ],
          },
        },
        response_type: "STRING",
        id: "6",
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "string",
                    default: "",
                    path: ["response"],
                    pathStr: "response",
                  },
                ],
              },
            ],
            path: [],
            keys: ["response"],
            flattened_schema: [
              {
                key: "response",
                type: "string",
                default: "",
                path: ["response"],
                pathStr: "response",
              },
            ],
          },
        },
        last_updated: 1754477457358,
      },
      meta: {
        search_keys: [
          "Text Area",
          "Paragraph Input",
          "Large Text Field",
          "Essay Box",
          "Comment Box",
          "Notes",
        ],
      },
      description:
        "What specific improvements would you suggest for the OxygenOS 14 update?",
      location: "1600 0",
      errors: [],
      warnings: [],
      nodeNumber: 6,
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "string",
                  default: "",
                  path: ["response"],
                  pathStr: "response",
                },
              ],
            },
          ],
          path: [],
          keys: ["response"],
          flattened_schema: [
            {
              key: "response",
              type: "string",
              default: "",
              path: ["response"],
              pathStr: "response",
            },
          ],
        },
      },
    },
    {
      key: "1754476677007",
      name: "Address",
      type: "ADDRESS",
      template: "roundedRectangle",
      background: "rgb(38, 50, 56)",
      foreground: "#fff",
      light: "#FF5252",
      module: "Question",
      go_data: {
        question: "",
        description: "",
        type: "ADDRESS",
        module: "Question",
        buttonLabel: "Next",
        value: {
          fullName: "",
          country: "",
          addressLineOne: "",
          addressLineTwo: "",
          city: "",
          zipCode: "",
          state: "",
        },
        key_config_map: {
          fullName: {
            display_name: {
              key: "label",
              value: "Full Name",
            },
          },
          country: {
            display_name: {
              key: "label",
              value: "Country",
            },
          },
          addressLineOne: {
            display_name: {
              key: "label",
              value: "Address Line 1",
            },
          },
          addressLineTwo: {
            display_name: {
              key: "label",
              value: "Address Line 2",
            },
          },
          city: {
            display_name: {
              key: "label",
              value: "City/Town",
            },
          },
          zipCode: {
            display_name: {
              key: "label",
              value: "Zip/Post Code",
            },
          },
          state: {
            display_name: {
              key: "label",
              value: "State/Region/Province",
            },
          },
        },
        settings: {
          questionAlignment: "flex-start",
          fullName: false,
          addressLineOne: false,
          addressLineTwo: false,
          city: false,
          state: false,
          zipCode: false,
          country: false,
          accessKey: "",
        },
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "object",
                    default: {
                      fullName: "",
                      country: "",
                      addressLineOne: "",
                      addressLineTwo: "",
                      city: "",
                      zipCode: "",
                      state: "",
                    },
                    path: ["response"],
                    pathStr: "{response}",
                    schema: [
                      {
                        key: "fullName",
                        type: "string",
                        default: "",
                        path: ["response", "fullName"],
                        pathStr: "{response}.fullName",
                        label: "Full Name",
                      },
                      {
                        key: "country",
                        type: "string",
                        default: "",
                        path: ["response", "country"],
                        pathStr: "{response}.country",
                        label: "Country",
                      },
                      {
                        key: "addressLineOne",
                        type: "string",
                        default: "",
                        path: ["response", "addressLineOne"],
                        pathStr: "{response}.addressLineOne",
                        label: "Address Line 1",
                      },
                      {
                        key: "addressLineTwo",
                        type: "string",
                        default: "",
                        path: ["response", "addressLineTwo"],
                        pathStr: "{response}.addressLineTwo",
                        label: "Address Line 2",
                      },
                      {
                        key: "city",
                        type: "string",
                        default: "",
                        path: ["response", "city"],
                        pathStr: "{response}.city",
                        label: "City/Town",
                      },
                      {
                        key: "zipCode",
                        type: "string",
                        default: "",
                        path: ["response", "zipCode"],
                        pathStr: "{response}.zipCode",
                        label: "Zip/Post Code",
                      },
                      {
                        key: "state",
                        type: "string",
                        default: "",
                        path: ["response", "state"],
                        pathStr: "{response}.state",
                        label: "State/Region/Province",
                      },
                      {
                        key: "__to_string",
                        type: "string",
                        default: "",
                        path: ["response", "__to_string"],
                        pathStr: "{response}.__to_string",
                        label: "Complete Address",
                      },
                    ],
                  },
                ],
              },
            ],
            path: [],
            keys: [
              "response",
              "response.fullName",
              "response.country",
              "response.addressLineOne",
              "response.addressLineTwo",
              "response.city",
              "response.zipCode",
              "response.state",
              "response.__to_string",
            ],
            flattened_schema: [
              {
                key: "response",
                type: "object",
                default: {
                  fullName: "",
                  country: "",
                  addressLineOne: "",
                  addressLineTwo: "",
                  city: "",
                  zipCode: "",
                  state: "",
                },
                path: ["response"],
                pathStr: "{response}",
              },
              {
                key: "fullName",
                type: "string",
                default: "",
                path: ["response", "fullName"],
                pathStr: "{response}.fullName",
                label: "Full Name",
              },
              {
                key: "country",
                type: "string",
                default: "",
                path: ["response", "country"],
                pathStr: "{response}.country",
                label: "Country",
              },
              {
                key: "addressLineOne",
                type: "string",
                default: "",
                path: ["response", "addressLineOne"],
                pathStr: "{response}.addressLineOne",
                label: "Address Line 1",
              },
              {
                key: "addressLineTwo",
                type: "string",
                default: "",
                path: ["response", "addressLineTwo"],
                pathStr: "{response}.addressLineTwo",
                label: "Address Line 2",
              },
              {
                key: "city",
                type: "string",
                default: "",
                path: ["response", "city"],
                pathStr: "{response}.city",
                label: "City/Town",
              },
              {
                key: "zipCode",
                type: "string",
                default: "",
                path: ["response", "zipCode"],
                pathStr: "{response}.zipCode",
                label: "Zip/Post Code",
              },
              {
                key: "state",
                type: "string",
                default: "",
                path: ["response", "state"],
                pathStr: "{response}.state",
                label: "State/Region/Province",
              },
              {
                key: "__to_string",
                type: "string",
                default: "",
                path: ["response", "__to_string"],
                pathStr: "{response}.__to_string",
                label: "Complete Address",
              },
            ],
          },
        },
        last_updated: 1754476679019,
      },
      meta: {
        search_keys: [
          "Location Input",
          "Address Field",
          "Place Input",
          "Geo Details",
          "Location Picker",
        ],
      },
      nodeNumber: 7,
      location: "1920 0",
      warnings: [],
      errors: [],
      description: "",
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "object",
                  default: {
                    fullName: "",
                    country: "",
                    addressLineOne: "",
                    addressLineTwo: "",
                    city: "",
                    zipCode: "",
                    state: "",
                  },
                  path: ["response"],
                  pathStr: "{response}",
                  schema: [
                    {
                      key: "fullName",
                      type: "string",
                      default: "",
                      path: ["response", "fullName"],
                      pathStr: "{response}.fullName",
                      label: "Full Name",
                    },
                    {
                      key: "country",
                      type: "string",
                      default: "",
                      path: ["response", "country"],
                      pathStr: "{response}.country",
                      label: "Country",
                    },
                    {
                      key: "addressLineOne",
                      type: "string",
                      default: "",
                      path: ["response", "addressLineOne"],
                      pathStr: "{response}.addressLineOne",
                      label: "Address Line 1",
                    },
                    {
                      key: "addressLineTwo",
                      type: "string",
                      default: "",
                      path: ["response", "addressLineTwo"],
                      pathStr: "{response}.addressLineTwo",
                      label: "Address Line 2",
                    },
                    {
                      key: "city",
                      type: "string",
                      default: "",
                      path: ["response", "city"],
                      pathStr: "{response}.city",
                      label: "City/Town",
                    },
                    {
                      key: "zipCode",
                      type: "string",
                      default: "",
                      path: ["response", "zipCode"],
                      pathStr: "{response}.zipCode",
                      label: "Zip/Post Code",
                    },
                    {
                      key: "state",
                      type: "string",
                      default: "",
                      path: ["response", "state"],
                      pathStr: "{response}.state",
                      label: "State/Region/Province",
                    },
                    {
                      key: "__to_string",
                      type: "string",
                      default: "",
                      path: ["response", "__to_string"],
                      pathStr: "{response}.__to_string",
                      label: "Complete Address",
                    },
                  ],
                },
              ],
            },
          ],
          path: [],
          keys: [
            "response",
            "response.fullName",
            "response.country",
            "response.addressLineOne",
            "response.addressLineTwo",
            "response.city",
            "response.zipCode",
            "response.state",
            "response.__to_string",
          ],
          flattened_schema: [
            {
              key: "response",
              type: "object",
              default: {
                fullName: "",
                country: "",
                addressLineOne: "",
                addressLineTwo: "",
                city: "",
                zipCode: "",
                state: "",
              },
              path: ["response"],
              pathStr: "{response}",
            },
            {
              key: "fullName",
              type: "string",
              default: "",
              path: ["response", "fullName"],
              pathStr: "{response}.fullName",
              label: "Full Name",
            },
            {
              key: "country",
              type: "string",
              default: "",
              path: ["response", "country"],
              pathStr: "{response}.country",
              label: "Country",
            },
            {
              key: "addressLineOne",
              type: "string",
              default: "",
              path: ["response", "addressLineOne"],
              pathStr: "{response}.addressLineOne",
              label: "Address Line 1",
            },
            {
              key: "addressLineTwo",
              type: "string",
              default: "",
              path: ["response", "addressLineTwo"],
              pathStr: "{response}.addressLineTwo",
              label: "Address Line 2",
            },
            {
              key: "city",
              type: "string",
              default: "",
              path: ["response", "city"],
              pathStr: "{response}.city",
              label: "City/Town",
            },
            {
              key: "zipCode",
              type: "string",
              default: "",
              path: ["response", "zipCode"],
              pathStr: "{response}.zipCode",
              label: "Zip/Post Code",
            },
            {
              key: "state",
              type: "string",
              default: "",
              path: ["response", "state"],
              pathStr: "{response}.state",
              label: "State/Region/Province",
            },
            {
              key: "__to_string",
              type: "string",
              default: "",
              path: ["response", "__to_string"],
              pathStr: "{response}.__to_string",
              label: "Complete Address",
            },
          ],
        },
      },
    },
    {
      key: "1754477563321",
      cmsId: "http",
      name: "HTTP",
      type: "HTTP",
      template: "",
      background: "linear-gradient(196deg, #7D007D 2.15%, #C800C8 77.96%)",
      foreground: "#fff",
      dark: "rgb(125, 0, 125)",
      light: "rgb(200, 0, 200)",
      hasTestModule: true,
      canSkipTest: false,
      premium: true,
      meta: {
        search_keys: [
          "Curl",
          "Postman",
          "Api",
          "Url",
          "Get",
          "Post",
          "Put",
          "Request",
        ],
      },
      nodeNumber: 11,
      location: "2560 0",
      warnings: [],
      errors: [],
      go_data: {
        url: {
          type: "fx",
          blocks: [
            {
              type: "PRIMITIVES",
              value: "https://www.google.com",
            },
          ],
          text: "https://www.google.com",
        },
        method: "GET",
        query_params: [
          {
            rowid: "61d02285-62e4-46e1-9e11-202ecd829c4a",
          },
        ],
        headers: [
          {
            rowid: "5edaffc6-973b-4352-a69e-2c74ad3754bc",
          },
        ],
        authorization: {
          type: "none",
          data: null,
        },
        body: {
          type: "none",
          data: null,
        },
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "headers",
                    type: "object",
                    default: {},
                    path: ["headers"],
                    pathStr: "{headers}",
                    schema: [
                      {
                        key: "accept-ch",
                        type: "string",
                        default: "",
                        path: ["headers", "accept-ch"],
                        pathStr: "{headers}.accept-ch",
                      },
                      {
                        key: "alt-svc",
                        type: "string",
                        default: "",
                        path: ["headers", "alt-svc"],
                        pathStr: "{headers}.alt-svc",
                      },
                      {
                        key: "cache-control",
                        type: "string",
                        default: "",
                        path: ["headers", "cache-control"],
                        pathStr: "{headers}.cache-control",
                      },
                      {
                        key: "content-encoding",
                        type: "string",
                        default: "",
                        path: ["headers", "content-encoding"],
                        pathStr: "{headers}.content-encoding",
                      },
                      {
                        key: "content-security-policy-report-only",
                        type: "string",
                        default: "",
                        path: [
                          "headers",
                          "content-security-policy-report-only",
                        ],
                        pathStr:
                          "{headers}.content-security-policy-report-only",
                      },
                      {
                        key: "content-type",
                        type: "string",
                        default: "",
                        path: ["headers", "content-type"],
                        pathStr: "{headers}.content-type",
                      },
                      {
                        key: "date",
                        type: "date",
                        default: "2025-08-06T10:52:57.382Z",
                        path: ["headers", "date"],
                        pathStr: "{headers}.date",
                      },
                      {
                        key: "expires",
                        type: "string",
                        default: "",
                        path: ["headers", "expires"],
                        pathStr: "{headers}.expires",
                      },
                      {
                        key: "p3p",
                        type: "string",
                        default: "",
                        path: ["headers", "p3p"],
                        pathStr: "{headers}.p3p",
                      },
                      {
                        key: "server",
                        type: "string",
                        default: "",
                        path: ["headers", "server"],
                        pathStr: "{headers}.server",
                      },
                      {
                        key: "set-cookie",
                        type: "string",
                        default: "",
                        path: ["headers", "set-cookie"],
                        pathStr: "{headers}.set-cookie",
                      },
                      {
                        key: "transfer-encoding",
                        type: "string",
                        default: "",
                        path: ["headers", "transfer-encoding"],
                        pathStr: "{headers}.transfer-encoding",
                      },
                      {
                        key: "x-frame-options",
                        type: "string",
                        default: "",
                        path: ["headers", "x-frame-options"],
                        pathStr: "{headers}.x-frame-options",
                      },
                      {
                        key: "x-xss-protection",
                        type: "string",
                        default: "",
                        path: ["headers", "x-xss-protection"],
                        pathStr: "{headers}.x-xss-protection",
                      },
                    ],
                  },
                  {
                    key: "body",
                    type: "string",
                    default: "",
                    path: ["body"],
                    pathStr: "body",
                  },
                  {
                    key: "status_code",
                    type: "number",
                    default: 0,
                    path: ["status_code"],
                    pathStr: "status_code",
                  },
                  {
                    key: "curl",
                    type: "string",
                    default: "",
                    path: ["curl"],
                    pathStr: "curl",
                  },
                ],
              },
            ],
            path: [],
            keys: [
              "headers",
              "headers.accept-ch",
              "headers.alt-svc",
              "headers.cache-control",
              "headers.content-encoding",
              "headers.content-security-policy-report-only",
              "headers.content-type",
              "headers.date",
              "headers.expires",
              "headers.p3p",
              "headers.server",
              "headers.set-cookie",
              "headers.transfer-encoding",
              "headers.x-frame-options",
              "headers.x-xss-protection",
              "body",
              "status_code",
              "curl",
            ],
            flattened_schema: [
              {
                key: "headers",
                type: "object",
                default: {},
                path: ["headers"],
                pathStr: "{headers}",
              },
              {
                key: "accept-ch",
                type: "string",
                default: "",
                path: ["headers", "accept-ch"],
                pathStr: "{headers}.accept-ch",
              },
              {
                key: "alt-svc",
                type: "string",
                default: "",
                path: ["headers", "alt-svc"],
                pathStr: "{headers}.alt-svc",
              },
              {
                key: "cache-control",
                type: "string",
                default: "",
                path: ["headers", "cache-control"],
                pathStr: "{headers}.cache-control",
              },
              {
                key: "content-encoding",
                type: "string",
                default: "",
                path: ["headers", "content-encoding"],
                pathStr: "{headers}.content-encoding",
              },
              {
                key: "content-security-policy-report-only",
                type: "string",
                default: "",
                path: ["headers", "content-security-policy-report-only"],
                pathStr: "{headers}.content-security-policy-report-only",
              },
              {
                key: "content-type",
                type: "string",
                default: "",
                path: ["headers", "content-type"],
                pathStr: "{headers}.content-type",
              },
              {
                key: "date",
                type: "date",
                default: "2025-08-06T10:52:57.382Z",
                path: ["headers", "date"],
                pathStr: "{headers}.date",
              },
              {
                key: "expires",
                type: "string",
                default: "",
                path: ["headers", "expires"],
                pathStr: "{headers}.expires",
              },
              {
                key: "p3p",
                type: "string",
                default: "",
                path: ["headers", "p3p"],
                pathStr: "{headers}.p3p",
              },
              {
                key: "server",
                type: "string",
                default: "",
                path: ["headers", "server"],
                pathStr: "{headers}.server",
              },
              {
                key: "set-cookie",
                type: "string",
                default: "",
                path: ["headers", "set-cookie"],
                pathStr: "{headers}.set-cookie",
              },
              {
                key: "transfer-encoding",
                type: "string",
                default: "",
                path: ["headers", "transfer-encoding"],
                pathStr: "{headers}.transfer-encoding",
              },
              {
                key: "x-frame-options",
                type: "string",
                default: "",
                path: ["headers", "x-frame-options"],
                pathStr: "{headers}.x-frame-options",
              },
              {
                key: "x-xss-protection",
                type: "string",
                default: "",
                path: ["headers", "x-xss-protection"],
                pathStr: "{headers}.x-xss-protection",
              },
              {
                key: "body",
                type: "string",
                default: "",
                path: ["body"],
                pathStr: "body",
              },
              {
                key: "status_code",
                type: "number",
                default: 0,
                path: ["status_code"],
                pathStr: "status_code",
              },
              {
                key: "curl",
                type: "string",
                default: "",
                path: ["curl"],
                pathStr: "curl",
              },
            ],
          },
        },
        path_variable: {
          data: [],
        },
        errors: [],
        last_updated: 1754477578328,
      },
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "headers",
                  type: "object",
                  default: {},
                  path: ["headers"],
                  pathStr: "{headers}",
                  schema: [
                    {
                      key: "accept-ch",
                      type: "string",
                      default: "",
                      path: ["headers", "accept-ch"],
                      pathStr: "{headers}.accept-ch",
                    },
                    {
                      key: "alt-svc",
                      type: "string",
                      default: "",
                      path: ["headers", "alt-svc"],
                      pathStr: "{headers}.alt-svc",
                    },
                    {
                      key: "cache-control",
                      type: "string",
                      default: "",
                      path: ["headers", "cache-control"],
                      pathStr: "{headers}.cache-control",
                    },
                    {
                      key: "content-encoding",
                      type: "string",
                      default: "",
                      path: ["headers", "content-encoding"],
                      pathStr: "{headers}.content-encoding",
                    },
                    {
                      key: "content-security-policy-report-only",
                      type: "string",
                      default: "",
                      path: ["headers", "content-security-policy-report-only"],
                      pathStr: "{headers}.content-security-policy-report-only",
                    },
                    {
                      key: "content-type",
                      type: "string",
                      default: "",
                      path: ["headers", "content-type"],
                      pathStr: "{headers}.content-type",
                    },
                    {
                      key: "date",
                      type: "date",
                      default: "2025-08-06T10:52:57.382Z",
                      path: ["headers", "date"],
                      pathStr: "{headers}.date",
                    },
                    {
                      key: "expires",
                      type: "string",
                      default: "",
                      path: ["headers", "expires"],
                      pathStr: "{headers}.expires",
                    },
                    {
                      key: "p3p",
                      type: "string",
                      default: "",
                      path: ["headers", "p3p"],
                      pathStr: "{headers}.p3p",
                    },
                    {
                      key: "server",
                      type: "string",
                      default: "",
                      path: ["headers", "server"],
                      pathStr: "{headers}.server",
                    },
                    {
                      key: "set-cookie",
                      type: "string",
                      default: "",
                      path: ["headers", "set-cookie"],
                      pathStr: "{headers}.set-cookie",
                    },
                    {
                      key: "transfer-encoding",
                      type: "string",
                      default: "",
                      path: ["headers", "transfer-encoding"],
                      pathStr: "{headers}.transfer-encoding",
                    },
                    {
                      key: "x-frame-options",
                      type: "string",
                      default: "",
                      path: ["headers", "x-frame-options"],
                      pathStr: "{headers}.x-frame-options",
                    },
                    {
                      key: "x-xss-protection",
                      type: "string",
                      default: "",
                      path: ["headers", "x-xss-protection"],
                      pathStr: "{headers}.x-xss-protection",
                    },
                  ],
                },
                {
                  key: "body",
                  type: "string",
                  default: "",
                  path: ["body"],
                  pathStr: "body",
                },
                {
                  key: "status_code",
                  type: "number",
                  default: 0,
                  path: ["status_code"],
                  pathStr: "status_code",
                },
                {
                  key: "curl",
                  type: "string",
                  default: "",
                  path: ["curl"],
                  pathStr: "curl",
                },
              ],
            },
          ],
          path: [],
          keys: [
            "headers",
            "headers.accept-ch",
            "headers.alt-svc",
            "headers.cache-control",
            "headers.content-encoding",
            "headers.content-security-policy-report-only",
            "headers.content-type",
            "headers.date",
            "headers.expires",
            "headers.p3p",
            "headers.server",
            "headers.set-cookie",
            "headers.transfer-encoding",
            "headers.x-frame-options",
            "headers.x-xss-protection",
            "body",
            "status_code",
            "curl",
          ],
          flattened_schema: [
            {
              key: "headers",
              type: "object",
              default: {},
              path: ["headers"],
              pathStr: "{headers}",
            },
            {
              key: "accept-ch",
              type: "string",
              default: "",
              path: ["headers", "accept-ch"],
              pathStr: "{headers}.accept-ch",
            },
            {
              key: "alt-svc",
              type: "string",
              default: "",
              path: ["headers", "alt-svc"],
              pathStr: "{headers}.alt-svc",
            },
            {
              key: "cache-control",
              type: "string",
              default: "",
              path: ["headers", "cache-control"],
              pathStr: "{headers}.cache-control",
            },
            {
              key: "content-encoding",
              type: "string",
              default: "",
              path: ["headers", "content-encoding"],
              pathStr: "{headers}.content-encoding",
            },
            {
              key: "content-security-policy-report-only",
              type: "string",
              default: "",
              path: ["headers", "content-security-policy-report-only"],
              pathStr: "{headers}.content-security-policy-report-only",
            },
            {
              key: "content-type",
              type: "string",
              default: "",
              path: ["headers", "content-type"],
              pathStr: "{headers}.content-type",
            },
            {
              key: "date",
              type: "date",
              default: "2025-08-06T10:52:57.382Z",
              path: ["headers", "date"],
              pathStr: "{headers}.date",
            },
            {
              key: "expires",
              type: "string",
              default: "",
              path: ["headers", "expires"],
              pathStr: "{headers}.expires",
            },
            {
              key: "p3p",
              type: "string",
              default: "",
              path: ["headers", "p3p"],
              pathStr: "{headers}.p3p",
            },
            {
              key: "server",
              type: "string",
              default: "",
              path: ["headers", "server"],
              pathStr: "{headers}.server",
            },
            {
              key: "set-cookie",
              type: "string",
              default: "",
              path: ["headers", "set-cookie"],
              pathStr: "{headers}.set-cookie",
            },
            {
              key: "transfer-encoding",
              type: "string",
              default: "",
              path: ["headers", "transfer-encoding"],
              pathStr: "{headers}.transfer-encoding",
            },
            {
              key: "x-frame-options",
              type: "string",
              default: "",
              path: ["headers", "x-frame-options"],
              pathStr: "{headers}.x-frame-options",
            },
            {
              key: "x-xss-protection",
              type: "string",
              default: "",
              path: ["headers", "x-xss-protection"],
              pathStr: "{headers}.x-xss-protection",
            },
            {
              key: "body",
              type: "string",
              default: "",
              path: ["body"],
              pathStr: "body",
            },
            {
              key: "status_code",
              type: "number",
              default: 0,
              path: ["status_code"],
              pathStr: "status_code",
            },
            {
              key: "curl",
              type: "string",
              default: "",
              path: ["curl"],
              pathStr: "curl",
            },
          ],
        },
      },
    },
  ],
};
export const defaultInputContent = [
  {
    subCategory: "NODE",
    type: "NODE",
    subType: "Address.Full Name",
    value: "Address.Full Name",
    background: "#FF5252",
    foreground: "#fff",
    nodeNumber: 4,
    variableData: {
      key: "fullName",
      label: "Full Name",
      module: "Question",
      type: "string",
      sample_value: "",
      default: "",
      path: ["response", "fullName"],
      pathStr: "{response}.fullName",
      nodeName: "Address",
      nodeId: "1754390928356",
      nodeType: "ADDRESS",
    },
    blockId: "b57685b3-3de9-45e2-ad5d-116ada8b22a8",
    error: false,
  },
  {
    subCategory: "NODE",
    type: "NODE",
    subType: "My Transformer",
    value: "My Transformer",
    background: "#4AA3EB",
    foreground: "#fff",
    nodeNumber: 2,
    variableData: {
      key: "response",
      type: "string",
      sample_value: "",
      default: "",
      path: ["response"],
      pathStr: "response",
      nodeName: "My Transformer",
      nodeId: "1754390406770",
      nodeType: "Transformer",
    },
    blockId: "7fe0c2a7-9f2b-412f-a53b-368cd257d2b6",
    error: false,
  },
  {
    subCategory: "NODE",
    type: "NODE",
    subType: "hello world",
    value: "hello world",
    background: "#FF5252",
    foreground: "#fff",
    nodeNumber: 1,
    variableData: {
      key: "response",
      module: "Question",
      type: "string",
      sample_value: "",
      default: "",
      path: ["response"],
      pathStr: "response",
      nodeName: "hello world",
      nodeId: "1754390401980",
      nodeType: "SHORT_TEXT",
    },
    blockId: "4bc55e28-c4cb-47b9-8a1b-64b4a2334340",
    error: false,
  },
  {
    subCategory: "NODE",
    type: "NODE",
    subType: "Address.Zip/Post Code",
    value: "Address.Zip/Post Code",
    background: "#FF5252",
    foreground: "#fff",
    nodeNumber: 4,
    variableData: {
      key: "zipCode",
      label: "Zip/Post Code",
      module: "Question",
      type: "string",
      sample_value: "",
      default: "",
      path: ["response", "zipCode"],
      pathStr: "{response}.zipCode",
      nodeName: "Address",
      nodeId: "1754390928356",
      nodeType: "ADDRESS",
    },
    blockId: "a0dc4188-b27a-49bc-832a-8c53a3de859d",
    error: false,
  },
  {
    subCategory: "NODE",
    type: "NODE",
    subType: "Address",
    value: "Address",
    background: "#FF5252",
    foreground: "#fff",
    nodeNumber: 4,
    variableData: {
      schema: [
        {
          key: "fullName",
          type: "string",
          default: "",
          path: ["response", "fullName"],
          pathStr: "{response}.fullName",
          label: "Full Name",
        },
        {
          key: "country",
          type: "string",
          default: "",
          path: ["response", "country"],
          pathStr: "{response}.country",
          label: "Country",
        },
        {
          key: "addressLineOne",
          type: "string",
          default: "",
          path: ["response", "addressLineOne"],
          pathStr: "{response}.addressLineOne",
          label: "Address Line 1",
        },
        {
          key: "addressLineTwo",
          type: "string",
          default: "",
          path: ["response", "addressLineTwo"],
          pathStr: "{response}.addressLineTwo",
          label: "Address Line 2",
        },
        {
          key: "city",
          type: "string",
          default: "",
          path: ["response", "city"],
          pathStr: "{response}.city",
          label: "City/Town",
        },
        {
          key: "zipCode",
          type: "string",
          default: "",
          path: ["response", "zipCode"],
          pathStr: "{response}.zipCode",
          label: "Zip/Post Code",
        },
        {
          key: "state",
          type: "string",
          default: "",
          path: ["response", "state"],
          pathStr: "{response}.state",
          label: "State/Region/Province",
        },
      ],
      key: "response",
      module: "Question",
      type: "object",
      sample_value: {
        fullName: "",
        country: "",
        addressLineOne: "",
        addressLineTwo: "",
        city: "",
        zipCode: "",
        state: "",
      },
      default: {
        fullName: "",
        country: "",
        addressLineOne: "",
        addressLineTwo: "",
        city: "",
        zipCode: "",
        state: "",
      },
      path: ["response"],
      pathStr: "{response}",
      nodeName: "Address",
      nodeId: "1754390928356",
      nodeType: "ADDRESS",
    },
    blockId: "2416fb03-a7bf-48f0-9596-b6795d93f517",
  },
];
export const dummyTableColumns = [
  {
    id: 2067,
    name: "email test",
    description: "",
    options: {
      defaultValue: "",
    },
    type: "EMAIL",
    cellValueType: "string",
    dbFieldType: "VARCHAR",
    dbFieldName: "email_test_tn9W7F7gerPQCR6wbBiaB3",
    createdTime: "2024-09-17T18:11:05.981Z",
    lastModifiedTime: "2024-09-17T18:11:05.981Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2068,
    name: "scq question",
    description: "",
    options: {
      options: ["Hamilton", "Verstappen", "Prost", "Vettle", "Alonso"],
      defaultValue: "",
    },
    type: "SCQ",
    cellValueType: "string",
    dbFieldType: "TEXT",
    dbFieldName: "scq_question_xvrQFpD9SuqYJQoz75Agah",
    createdTime: "2024-09-17T18:12:05.044Z",
    lastModifiedTime: "2024-09-17T18:12:05.044Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2254,
    name: "dropdown",
    description: "",
    options: {
      options: [
        {
          id: "c821dd96-5f17-4a0c-9306-b7b9a13688dd",
          label: "ads",
        },
        {
          id: "11a675f3-9349-4756-971d-791b6aa397a4",
          label: "sdfsdsf",
        },
        {
          id: "0b4da695-b349-4712-b6f6-30944c592e04",
          label: "vcbxd",
        },
      ],
      defaultValue: [],
      selectionType: "Unlimited",
    },
    type: "DROP_DOWN",
    cellValueType: "string",
    dbFieldType: "JSONB",
    dbFieldName: "dropdown_orbrmuC22x8YTnH3q6BbKe",
    createdTime: "2024-09-26T05:47:30.780Z",
    lastModifiedTime: "2024-09-26T05:47:30.780Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2267,
    name: "time 12 hr format",
    description: "",
    options: {
      defaultTime: {
        time: "",
        meridiem: "",
      },
      isTwentyFourHour: false,
    },
    type: "TIME",
    cellValueType: "string",
    dbFieldType: "JSONB",
    dbFieldName: "time_12_hr_format_tJ9jT3UXd9QurnqxGxaTiQ",
    createdTime: "2024-09-26T07:59:23.563Z",
    lastModifiedTime: "2024-09-26T07:59:23.563Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2268,
    name: "24hr format",
    description: "",
    options: {
      defaultTime: {
        time: "",
      },
      isTwentyFourHour: true,
    },
    type: "TIME",
    cellValueType: "string",
    dbFieldType: "JSONB",
    dbFieldName: "24hr_format_qUgaKpR6x9oA2qpohYYFdd",
    createdTime: "2024-09-26T09:54:24.778Z",
    lastModifiedTime: "2024-09-26T09:54:24.778Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2445,
    name: "Phone Number",
    description: "",
    options: {
      defaultValue: "",
    },
    type: "PHONE_NUMBER",
    cellValueType: "string",
    dbFieldType: "JSONB",
    dbFieldName: "phone_number_cMgeBNyr9xJavNDwXnmv9T",
    createdTime: "2024-10-01T05:33:37.466Z",
    lastModifiedTime: "2024-10-01T05:33:37.466Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2454,
    name: "Zip code ",
    description: "",
    options: {
      allowOtherContry: false,
    },
    type: "ZIP_CODE",
    cellValueType: "string",
    dbFieldType: "JSONB",
    dbFieldName: "zip_code_kbTfwYds8cpGqE5mDh1eXs",
    createdTime: "2024-10-01T11:09:01.199Z",
    lastModifiedTime: "2024-10-01T11:09:01.199Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2179,
    name: "Address",
    description: "",
    options: {},
    type: "ADDRESS",
    cellValueType: "string",
    dbFieldType: "JSONB",
    dbFieldName: "address_cyoEjSNUoNj4f4EGV9Mdhx",
    createdTime: "2024-09-24T05:21:41.595Z",
    lastModifiedTime: "2024-09-24T05:21:41.595Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2066,
    name: "number1",
    description: "",
    options: {
      presets: "",
      activeTab: "formatting",
      allowFraction: false,
      allowNegative: false,
      decimalPlaces: "1 ($1.0)",
      largeNumberAbbreviation: "None",
      showThousandsSeparators: false,
      thousandsAndDecimalSeparator: "Local (1,000,000.00)",
    },
    type: "NUMBER",
    cellValueType: "string",
    dbFieldType: "",
    dbFieldName: "number_eMgXeuxMPXWmA5p1uwZCQ7",
    createdTime: "2024-09-17T18:10:51.466Z",
    lastModifiedTime: "2024-09-24T09:31:03.516Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2065,
    name: "mcq testing",
    description: "asdas",
    options: {
      options: ["abhay", "vedant", "shubham", "ankit"],
      defaultValue: [],
      selectionType: "Unlimited",
    },
    type: "MCQ",
    cellValueType: "string",
    dbFieldType: "",
    dbFieldName: "mcq_testing_6u59xcS7Ajdb4n7zQFhFGo",
    createdTime: "2024-09-17T18:10:38.023Z",
    lastModifiedTime: "2024-09-24T09:32:28.179Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
  {
    id: 2064,
    name: "Name",
    description: "",
    options: {
      id: 2064,
      order: 1,
      nodeId: null,
      status: "active",
      options: {
        defaultValue: "",
      },
      source_id: null,
      createdTime: "2024-09-17T18:09:55.834Z",
      dbFieldName: "name_gquXLVtr4dAGX2pes54rtH",
      dbFieldType: "",
      deletedTime: null,
      tableMetaId: "cm16r17x100iw12hmmszu630x",
      defaultValue: "",
      cellValueType: "string",
      lastModifiedTime: "2025-01-31T12:47:41.179Z",
    },
    type: "SHORT_TEXT",
    cellValueType: "string",
    dbFieldType: "",
    dbFieldName: "name_gquXLVtr4dAGX2pes54rtH",
    createdTime: "2024-09-17T18:09:55.834Z",
    lastModifiedTime: "2025-05-15T01:31:18.980Z",
    deletedTime: null,
    tableMetaId: "cm16r17x100iw12hmmszu630x",
    nodeId: null,
    status: "active",
    source_id: null,
  },
];
