export interface Country {
  countryCode: string;
  countryName: string;
  countryNumber: string;
  pattern?: string;
  currencyCode?: string;
  currencySymbol?: string;
}

export const COUNTRIES: Record<string, Country> = {
  AD: {
    countryCode: "AD",
    countryName: "Andorra",
    countryNumber: "376",
    pattern: "999999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  AE: {
    countryCode: "AE",
    countryName: "United Arab Emirates",
    countryNumber: "971",
    pattern: "99-9999999",
    currencyCode: "AED",
    currencySymbol: "د.إ",
  },
  AF: {
    countryCode: "AF",
    countryName: "Afghanistan",
    countryNumber: "93",
    pattern: "99-999-9999",
    currencyCode: "AFN",
    currencySymbol: "؋",
  },
  AG: {
    countryCode: "AG",
    countryName: "Antigua and Barbuda",
    countryNumber: "1-268",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  AI: {
    countryCode: "AI",
    countryName: "Anguilla",
    countryNumber: "1-264",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  AL: {
    countryCode: "AL",
    countryName: "Albania",
    countryNumber: "355",
    pattern: "999-999-999",
    currencyCode: "ALL",
    currencySymbol: "Lek",
  },
  AM: {
    countryCode: "AM",
    countryName: "Armenia",
    countryNumber: "374",
    pattern: "99-999-999",
    currencyCode: "AMD",
    currencySymbol: "֏",
  },
  AO: {
    countryCode: "AO",
    countryName: "Angola",
    countryNumber: "244",
    pattern: "999-999-999",
    currencyCode: "AOA",
    currencySymbol: "Kz",
  },
  AQ: {
    countryCode: "AQ",
    countryName: "Antarctica",
    countryNumber: "672",
    pattern: "99-999",
    currencyCode: "XCD",
    currencySymbol: "¢",
  },
  AR: {
    countryCode: "AR",
    countryName: "Argentina",
    countryNumber: "54",
    pattern: "999-999-9999",
    currencyCode: "ARS",
    currencySymbol: "$",
  },
  AS: {
    countryCode: "AS",
    countryName: "American Samoa",
    countryNumber: "1-684",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  AT: {
    countryCode: "AT",
    countryName: "Austria",
    countryNumber: "43",
    pattern: "999-9999999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  AU: {
    countryCode: "AU",
    countryName: "Australia",
    countryNumber: "61",
    pattern: "99-9999-9999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  AW: {
    countryCode: "AW",
    countryName: "Aruba",
    countryNumber: "297",
    pattern: "99-9999999",
    currencyCode: "AWG",
    currencySymbol: "ƒ",
  },
  AX: {
    countryCode: "AX",
    countryName: "Åland Islands",
    countryNumber: "358",
    pattern: "99-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  AZ: {
    countryCode: "AZ",
    countryName: "Azerbaijan",
    countryNumber: "994",
    pattern: "99-999-99-99",
    currencyCode: "AZN",
    currencySymbol: "₼",
  },
  BA: {
    countryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    countryNumber: "387",
    pattern: "99-999-999",
    currencyCode: "BAM",
    currencySymbol: "KM",
  },
  BB: {
    countryCode: "BB",
    countryName: "Barbados",
    countryNumber: "1-246",
    pattern: "999-9999",
    currencyCode: "BBD",
    currencySymbol: "$",
  },
  BD: {
    countryCode: "BD",
    countryName: "Bangladesh",
    countryNumber: "880",
    pattern: "999-999-9999",
    currencyCode: "BDT",
    currencySymbol: "৳",
  },
  BE: {
    countryCode: "BE",
    countryName: "Belgium",
    countryNumber: "32",
    pattern: "99-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  BF: {
    countryCode: "BF",
    countryName: "Burkina Faso",
    countryNumber: "226",
    pattern: "99-99-99-99",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  BG: {
    countryCode: "BG",
    countryName: "Bulgaria",
    countryNumber: "359",
    pattern: "999-999-999",
    currencyCode: "BGN",
    currencySymbol: "лв",
  },
  BH: {
    countryCode: "BH",
    countryName: "Bahrain",
    countryNumber: "973",
    pattern: "9999-9999",
    currencyCode: "BHD",
    currencySymbol: ".د.ب",
  },
  BI: {
    countryCode: "BI",
    countryName: "Burundi",
    countryNumber: "257",
    pattern: "99-99-99-99",
    currencyCode: "BIF",
    currencySymbol: "FBu",
  },
  BJ: {
    countryCode: "BJ",
    countryName: "Benin",
    countryNumber: "229",
    pattern: "99-99-99-99",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  BL: {
    countryCode: "BL",
    countryName: "Saint Barthélemy",
    countryNumber: "590",
    pattern: "999-99-99-99",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  BM: {
    countryCode: "BM",
    countryName: "Bermuda",
    countryNumber: "1-441",
    pattern: "999-9999",
    currencyCode: "BMD",
    currencySymbol: "$",
  },
  BN: {
    countryCode: "BN",
    countryName: "Brunei Darussalam",
    countryNumber: "673",
    pattern: "999-9999",
    currencyCode: "BND",
    currencySymbol: "B$",
  },
  BO: {
    countryCode: "BO",
    countryName: "Bolivia, Plurinational State of",
    countryNumber: "591",
    pattern: "999-99999",
    currencyCode: "BOB",
    currencySymbol: "Bs.",
  },
  BQ: {
    countryCode: "BQ",
    countryName: "Bonaire, Sint Eustatius and Saba",
    countryNumber: "599",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  BR: {
    countryCode: "BR",
    countryName: "Brazil",
    countryNumber: "55",
    pattern: "99-99999-9999",
    currencyCode: "BRL",
    currencySymbol: "R$",
  },
  BS: {
    countryCode: "BS",
    countryName: "Bahamas",
    countryNumber: "1-242",
    pattern: "999-9999",
    currencyCode: "BSD",
    currencySymbol: "$",
  },
  BT: {
    countryCode: "BT",
    countryName: "Bhutan",
    countryNumber: "975",
    pattern: "999-999-999",
    currencyCode: "BTN",
    currencySymbol: "Nu.",
  },
  BV: {
    countryCode: "BV",
    countryName: "Bouvet Island",
    countryNumber: "47",
    pattern: "99-99-99",
    currencyCode: "NOK",
    currencySymbol: "kr",
  },
  BW: {
    countryCode: "BW",
    countryName: "Botswana",
    countryNumber: "267",
    pattern: "99-999-999",
    currencyCode: "BWP",
    currencySymbol: "P",
  },
  BY: {
    countryCode: "BY",
    countryName: "Belarus",
    countryNumber: "375",
    pattern: "99-999-9999",
    currencyCode: "BYN",
    currencySymbol: "Br",
  },
  BZ: {
    countryCode: "BZ",
    countryName: "Belize",
    countryNumber: "501",
    pattern: "999-9999",
    currencyCode: "BZD",
    currencySymbol: "BZ$",
  },
  CA: {
    countryCode: "CA",
    countryName: "Canada",
    countryNumber: "1",
    pattern: "999-999-9999",
    currencyCode: "CAD",
    currencySymbol: "$",
  },
  CC: {
    countryCode: "CC",
    countryName: "Cocos (Keeling) Islands",
    countryNumber: "61",
    pattern: "99-999-9999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  CD: {
    countryCode: "CD",
    countryName: "Democratic Republic of the Congo",
    countryNumber: "243",
    pattern: "999-999-999",
    currencyCode: "CDF",
    currencySymbol: "FC",
  },
  CF: {
    countryCode: "CF",
    countryName: "Central African Republic",
    countryNumber: "236",
    pattern: "99-99-99-99",
    currencyCode: "XAF",
    currencySymbol: "FCFA",
  },
  CG: {
    countryCode: "CG",
    countryName: "Congo",
    countryNumber: "242",
    pattern: "99-99-99-99",
    currencyCode: "XAF",
    currencySymbol: "FCFA",
  },
  CH: {
    countryCode: "CH",
    countryName: "Switzerland",
    countryNumber: "41",
    pattern: "99-999-99-99",
    currencyCode: "CHF",
    currencySymbol: "CHF",
  },
  CI: {
    countryCode: "CI",
    countryName: "Côte d'Ivoire",
    countryNumber: "225",
    pattern: "99-99-99-99",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  CK: {
    countryCode: "CK",
    countryName: "Cook Islands",
    countryNumber: "682",
    pattern: "99-999",
    currencyCode: "NZD",
    currencySymbol: "$",
  },
  CL: {
    countryCode: "CL",
    countryName: "Chile",
    countryNumber: "56",
    pattern: "999-999-999",
    currencyCode: "CLP",
    currencySymbol: "$",
  },
  CM: {
    countryCode: "CM",
    countryName: "Cameroon",
    countryNumber: "237",
    pattern: "99-99-99-99",
    currencyCode: "XAF",
    currencySymbol: "FCFA",
  },
  CN: {
    countryCode: "CN",
    countryName: "China",
    countryNumber: "86",
    pattern: "9999-999-999",
    currencyCode: "CNY",
    currencySymbol: "¥",
  },
  CO: {
    countryCode: "CO",
    countryName: "Colombia",
    countryNumber: "57",
    pattern: "999-999-9999",
    currencyCode: "COP",
    currencySymbol: "$",
  },
  CR: {
    countryCode: "CR",
    countryName: "Costa Rica",
    countryNumber: "506",
    pattern: "9999-9999",
    currencyCode: "CRC",
    currencySymbol: "₡",
  },
  CU: {
    countryCode: "CU",
    countryName: "Cuba",
    countryNumber: "53",
    pattern: "99-999999",
    currencyCode: "CUP",
    currencySymbol: "$",
  },
  CV: {
    countryCode: "CV",
    countryName: "Cabo Verde",
    countryNumber: "238",
    pattern: "999-99-99",
    currencyCode: "CVE",
    currencySymbol: "$",
  },
  CW: {
    countryCode: "CW",
    countryName: "Curaçao",
    countryNumber: "599",
    pattern: "999-9999",
    currencyCode: "ANG",
    currencySymbol: "ƒ",
  },
  CX: {
    countryCode: "CX",
    countryName: "Christmas Island",
    countryNumber: "61",
    pattern: "99-999-9999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  CY: {
    countryCode: "CY",
    countryName: "Cyprus",
    countryNumber: "357",
    pattern: "99-999999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  CZ: {
    countryCode: "CZ",
    countryName: "Czech Republic",
    countryNumber: "420",
    pattern: "999-999-999",
    currencyCode: "CZK",
    currencySymbol: "Kč",
  },
  DE: {
    countryCode: "DE",
    countryName: "Germany",
    countryNumber: "49",
    pattern: "9999-9999999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  DJ: {
    countryCode: "DJ",
    countryName: "Djibouti",
    countryNumber: "253",
    pattern: "99-99-99-99",
    currencyCode: "DJF",
    currencySymbol: "Fdj",
  },
  DK: {
    countryCode: "DK",
    countryName: "Denmark",
    countryNumber: "45",
    pattern: "99-99-99-99",
    currencyCode: "DKK",
    currencySymbol: "kr",
  },
  DM: {
    countryCode: "DM",
    countryName: "Dominica",
    countryNumber: "1-767",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  DO: {
    countryCode: "DO",
    countryName: "Dominican Republic",
    countryNumber: "1-809",
    pattern: "999-9999",
    currencyCode: "DOP",
    currencySymbol: "RD$",
  },
  DZ: {
    countryCode: "DZ",
    countryName: "Algeria",
    countryNumber: "213",
    pattern: "999-99-99-99",
    currencyCode: "DZD",
    currencySymbol: "DA",
  },
  EC: {
    countryCode: "EC",
    countryName: "Ecuador",
    countryNumber: "593",
    pattern: "999-999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  EE: {
    countryCode: "EE",
    countryName: "Estonia",
    countryNumber: "372",
    pattern: "999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  EG: {
    countryCode: "EG",
    countryName: "Egypt",
    countryNumber: "20",
    pattern: "9999-999-999",
    currencyCode: "EGP",
    currencySymbol: "£",
  },
  EH: {
    countryCode: "EH",
    countryName: "Western Sahara",
    countryNumber: "212",
    pattern: "999-999999",
    currencyCode: "MAD",
    currencySymbol: "DH",
  },
  ER: {
    countryCode: "ER",
    countryName: "Eritrea",
    countryNumber: "291",
    pattern: "999-9999",
    currencyCode: "ERN",
    currencySymbol: "Nfk",
  },
  ES: {
    countryCode: "ES",
    countryName: "Spain",
    countryNumber: "34",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  ET: {
    countryCode: "ET",
    countryName: "Ethiopia",
    countryNumber: "251",
    pattern: "999-999999",
    currencyCode: "ETB",
    currencySymbol: "Br",
  },
  FI: {
    countryCode: "FI",
    countryName: "Finland",
    countryNumber: "358",
    pattern: "999-9999999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  FJ: {
    countryCode: "FJ",
    countryName: "Fiji",
    countryNumber: "679",
    pattern: "999-9999",
    currencyCode: "FJD",
    currencySymbol: "$",
  },
  FK: {
    countryCode: "FK",
    countryName: "Falkland Islands (Malvinas)",
    countryNumber: "500",
    pattern: "9999",
    currencyCode: "FKP",
    currencySymbol: "£",
  },
  FM: {
    countryCode: "FM",
    countryName: "Federated States of Micronesia",
    countryNumber: "691",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  FO: {
    countryCode: "FO",
    countryName: "Faroe Islands",
    countryNumber: "298",
    pattern: "999-999",
    currencyCode: "DKK",
    currencySymbol: "kr",
  },
  FR: {
    countryCode: "FR",
    countryName: "France",
    countryNumber: "33",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  GA: {
    countryCode: "GA",
    countryName: "Gabon",
    countryNumber: "241",
    pattern: "999-9999",
    currencyCode: "XAF",
    currencySymbol: "FCFA",
  },
  GB: {
    countryCode: "GB",
    countryName: "United Kingdom",
    countryNumber: "44",
    pattern: "9999-999999",
    currencyCode: "GBP",
    currencySymbol: "£",
  },
  GD: {
    countryCode: "GD",
    countryName: "Grenada",
    countryNumber: "1-473",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  GE: {
    countryCode: "GE",
    countryName: "Georgia",
    countryNumber: "995",
    pattern: "999-999999",
    currencyCode: "GEL",
    currencySymbol: "₾",
  },
  GF: {
    countryCode: "GF",
    countryName: "French Guiana",
    countryNumber: "594",
    pattern: "999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  GG: {
    countryCode: "GG",
    countryName: "Guernsey",
    countryNumber: "44",
    pattern: "9999-999999",
    currencyCode: "GBP",
    currencySymbol: "£",
  },
  GH: {
    countryCode: "GH",
    countryName: "Ghana",
    countryNumber: "233",
    pattern: "999-999999",
    currencyCode: "GHS",
    currencySymbol: "₵",
  },
  GI: {
    countryCode: "GI",
    countryName: "Gibraltar",
    countryNumber: "350",
    pattern: "999-9999",
    currencyCode: "GIP",
    currencySymbol: "£",
  },
  GL: {
    countryCode: "GL",
    countryName: "Greenland",
    countryNumber: "299",
    pattern: "99-9999",
    currencyCode: "DKK",
    currencySymbol: "kr",
  },
  GM: {
    countryCode: "GM",
    countryName: "Gambia",
    countryNumber: "220",
    pattern: "999-9999",
    currencyCode: "GMD",
    currencySymbol: "D",
  },
  GN: {
    countryCode: "GN",
    countryName: "Guinea",
    countryNumber: "224",
    pattern: "99-999-999",
    currencyCode: "GNF",
    currencySymbol: "FG",
  },
  GP: {
    countryCode: "GP",
    countryName: "Guadeloupe",
    countryNumber: "590",
    pattern: "999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  GQ: {
    countryCode: "GQ",
    countryName: "Equatorial Guinea",
    countryNumber: "240",
    pattern: "999-999",
    currencyCode: "XAF",
    currencySymbol: "FCFA",
  },
  GR: {
    countryCode: "GR",
    countryName: "Greece",
    countryNumber: "30",
    pattern: "999-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  GS: {
    countryCode: "GS",
    countryName: "South Georgia and the South Sandwich Islands",
    countryNumber: "500",
    pattern: "999-999",
    currencySymbol: "£",
  },
  GT: {
    countryCode: "GT",
    countryName: "Guatemala",
    countryNumber: "502",
    pattern: "9999-9999",
    currencyCode: "GTQ",
    currencySymbol: "Q",
  },
  GU: {
    countryCode: "GU",
    countryName: "Guam",
    countryNumber: "1-671",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  GW: {
    countryCode: "GW",
    countryName: "Guinea-Bissau",
    countryNumber: "245",
    pattern: "999-9999",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  GY: {
    countryCode: "GY",
    countryName: "Guyana",
    countryNumber: "592",
    pattern: "999-9999",
    currencyCode: "GYD",
    currencySymbol: "$",
  },
  HK: {
    countryCode: "HK",
    countryName: "Hong Kong",
    countryNumber: "852",
    pattern: "9999-9999",
    currencyCode: "HKD",
    currencySymbol: "HK$",
  },
  HM: {
    countryCode: "HM",
    countryName: "Heard Island and McDonald Islands",
    countryNumber: "672",
    pattern: "999-999",
    currencyCode: "AUD",
    currencySymbol: "AU$",
  },
  HN: {
    countryCode: "HN",
    countryName: "Honduras",
    countryNumber: "504",
    pattern: "9999-9999",
    currencyCode: "HNL",
    currencySymbol: "L",
  },
  HR: {
    countryCode: "HR",
    countryName: "Croatia",
    countryNumber: "385",
    pattern: "99-999-9999",
    currencyCode: "HRK",
    currencySymbol: "kn",
  },
  HT: {
    countryCode: "HT",
    countryName: "Haiti",
    countryNumber: "509",
    pattern: "99-9999",
    currencyCode: "HTG",
    currencySymbol: "G",
  },
  HU: {
    countryCode: "HU",
    countryName: "Hungary",
    countryNumber: "36",
    pattern: "99-999-9999",
    currencyCode: "HUF",
    currencySymbol: "Ft",
  },
  ID: {
    countryCode: "ID",
    countryName: "Indonesia",
    countryNumber: "62",
    pattern: "9999-999-999",
    currencyCode: "IDR",
    currencySymbol: "Rp",
  },
  IE: {
    countryCode: "IE",
    countryName: "Ireland",
    countryNumber: "353",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  IL: {
    countryCode: "IL",
    countryName: "Israel",
    countryNumber: "972",
    pattern: "99-999-9999",
    currencyCode: "ILS",
    currencySymbol: "₪",
  },
  IM: {
    countryCode: "IM",
    countryName: "Isle of Man",
    countryNumber: "44",
    pattern: "9999-999999",
    currencyCode: "GBP",
    currencySymbol: "£",
  },
  IN: {
    countryCode: "IN",
    countryName: "India",
    countryNumber: "91",
    pattern: "99999-99999",
    currencyCode: "INR",
    currencySymbol: "₹",
  },
  IO: {
    countryCode: "IO",
    countryName: "British Indian Ocean Territory",
    countryNumber: "246",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  IQ: {
    countryCode: "IQ",
    countryName: "Iraq",
    countryNumber: "964",
    pattern: "99-999-9999",
    currencyCode: "IQD",
    currencySymbol: "ع.د",
  },
  IR: {
    countryCode: "IR",
    countryName: "Islamic Republic of Iran",
    countryNumber: "98",
    pattern: "999-999-9999",
    currencyCode: "IRR",
    currencySymbol: "﷼",
  },
  IS: {
    countryCode: "IS",
    countryName: "Iceland",
    countryNumber: "354",
    pattern: "999-9999",
    currencyCode: "ISK",
    currencySymbol: "kr",
  },
  IT: {
    countryCode: "IT",
    countryName: "Italy",
    countryNumber: "39",
    pattern: "999-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  JE: {
    countryCode: "JE",
    countryName: "Jersey",
    countryNumber: "44",
    pattern: "9999-999999",
    currencyCode: "GBP",
    currencySymbol: "£",
  },
  JM: {
    countryCode: "JM",
    countryName: "Jamaica",
    countryNumber: "1-876",
    pattern: "999-9999",
    currencyCode: "JMD",
    currencySymbol: "J$",
  },
  JO: {
    countryCode: "JO",
    countryName: "Jordan",
    countryNumber: "962",
    pattern: "99-999-9999",
    currencyCode: "JOD",
    currencySymbol: "JD",
  },
  JP: {
    countryCode: "JP",
    countryName: "Japan",
    countryNumber: "81",
    pattern: "99-9999-9999",
    currencyCode: "JPY",
    currencySymbol: "¥",
  },
  KE: {
    countryCode: "KE",
    countryName: "Kenya",
    countryNumber: "254",
    pattern: "999-999-999",
    currencyCode: "KES",
    currencySymbol: "KSh",
  },
  KG: {
    countryCode: "KG",
    countryName: "Kyrgyzstan",
    countryNumber: "996",
    pattern: "999-999-999",
    currencyCode: "KGS",
    currencySymbol: "с",
  },
  KH: {
    countryCode: "KH",
    countryName: "Cambodia",
    countryNumber: "855",
    pattern: "99-999-9999",
    currencyCode: "KHR",
    currencySymbol: "៛",
  },
  KI: {
    countryCode: "KI",
    countryName: "Kiribati",
    countryNumber: "686",
    pattern: "999-9999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  KM: {
    countryCode: "KM",
    countryName: "Comoros",
    countryNumber: "269",
    pattern: "99-999-999",
    currencyCode: "KMF",
    currencySymbol: "CF",
  },
  KN: {
    countryCode: "KN",
    countryName: "Saint Kitts and Nevis",
    countryNumber: "1-869",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  KP: {
    countryCode: "KP",
    countryName: "Democratic People's Republic of Korea",
    countryNumber: "850",
    pattern: "99-999-9999",
    currencyCode: "KPW",
    currencySymbol: "₩",
  },
  KR: {
    countryCode: "KR",
    countryName: "Republic of Korea",
    countryNumber: "82",
    pattern: "99-999-9999",
    currencyCode: "KRW",
    currencySymbol: "₩",
  },
  KW: {
    countryCode: "KW",
    countryName: "Kuwait",
    countryNumber: "965",
    pattern: "9999-9999",
    currencyCode: "KWD",
    currencySymbol: "د.ك",
  },
  KY: {
    countryCode: "KY",
    countryName: "Cayman Islands",
    countryNumber: "1-345",
    pattern: "999-9999",
    currencyCode: "KYD",
    currencySymbol: "$",
  },
  KZ: {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    countryNumber: "7",
    pattern: "999-999-9999",
    currencyCode: "KZT",
    currencySymbol: "₸",
  },
  LA: {
    countryCode: "LA",
    countryName: "Lao People's Democratic Republic",
    countryNumber: "856",
    pattern: "99-999-999",
    currencyCode: "LAK",
    currencySymbol: "₭",
  },
  LB: {
    countryCode: "LB",
    countryName: "Lebanon",
    countryNumber: "961",
    pattern: "99-999-999",
    currencyCode: "LBP",
    currencySymbol: "ل.ل",
  },
  LC: {
    countryCode: "LC",
    countryName: "Saint Lucia",
    countryNumber: "1-758",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  LI: {
    countryCode: "LI",
    countryName: "Liechtenstein",
    countryNumber: "423",
    pattern: "999-9999",
    currencyCode: "CHF",
    currencySymbol: "CHF",
  },
  LK: {
    countryCode: "LK",
    countryName: "Sri Lanka",
    countryNumber: "94",
    pattern: "99-999-9999",
    currencyCode: "LKR",
    currencySymbol: "₨",
  },
  LR: {
    countryCode: "LR",
    countryName: "Liberia",
    countryNumber: "231",
    pattern: "99-999-999",
    currencyCode: "LRD",
    currencySymbol: "$",
  },
  LS: {
    countryCode: "LS",
    countryName: "Lesotho",
    countryNumber: "266",
    pattern: "999-9999",
    currencyCode: "LSL",
    currencySymbol: "L",
  },
  LT: {
    countryCode: "LT",
    countryName: "Lithuania",
    countryNumber: "370",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  LU: {
    countryCode: "LU",
    countryName: "Luxembourg",
    countryNumber: "352",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  LV: {
    countryCode: "LV",
    countryName: "Latvia",
    countryNumber: "371",
    pattern: "99-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  LY: {
    countryCode: "LY",
    countryName: "Libya",
    countryNumber: "218",
    pattern: "99-999-9999",
    currencyCode: "LYD",
    currencySymbol: "LD",
  },
  MA: {
    countryCode: "MA",
    countryName: "Morocco",
    countryNumber: "212",
    pattern: "99-999-9999",
    currencyCode: "MAD",
    currencySymbol: "DH",
  },
  MC: {
    countryCode: "MC",
    countryName: "Monaco",
    countryNumber: "377",
    pattern: "9999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  MD: {
    countryCode: "MD",
    countryName: "Republic of Moldova",
    countryNumber: "373",
    pattern: "99-999-999",
    currencyCode: "MDL",
    currencySymbol: "L",
  },
  ME: {
    countryCode: "ME",
    countryName: "Montenegro",
    countryNumber: "382",
    pattern: "99-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  MF: {
    countryCode: "MF",
    countryName: "Saint Martin (French part)",
    countryNumber: "590",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  MG: {
    countryCode: "MG",
    countryName: "Madagascar",
    countryNumber: "261",
    pattern: "99-999-999",
    currencyCode: "MGA",
    currencySymbol: "Ar",
  },
  MH: {
    countryCode: "MH",
    countryName: "Marshall Islands",
    countryNumber: "692",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  MK: {
    countryCode: "MK",
    countryName: "Republic of Macedonia",
    countryNumber: "389",
    pattern: "99-999-999",
    currencyCode: "MKD",
    currencySymbol: "ден",
  },
  ML: {
    countryCode: "ML",
    countryName: "Mali",
    countryNumber: "223",
    pattern: "99-999-999",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  MM: {
    countryCode: "MM",
    countryName: "Myanmar",
    countryNumber: "95",
    pattern: "99-999-999",
    currencyCode: "MMK",
    currencySymbol: "K",
  },
  MN: {
    countryCode: "MN",
    countryName: "Mongolia",
    countryNumber: "976",
    pattern: "99-999-999",
    currencyCode: "MNT",
    currencySymbol: "₮",
  },
  MO: {
    countryCode: "MO",
    countryName: "Macao",
    countryNumber: "853",
    pattern: "9999-9999",
    currencyCode: "MOP",
    currencySymbol: "MOP$",
  },
  MP: {
    countryCode: "MP",
    countryName: "Northern Mariana Islands",
    countryNumber: "1-670",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  MQ: {
    countryCode: "MQ",
    countryName: "Martinique",
    countryNumber: "596",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  MR: {
    countryCode: "MR",
    countryName: "Mauritania",
    countryNumber: "222",
    pattern: "99-999-999",
    currencyCode: "MRU",
    currencySymbol: "UM",
  },
  MS: {
    countryCode: "MS",
    countryName: "Montserrat",
    countryNumber: "1-664",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  MT: {
    countryCode: "MT",
    countryName: "Malta",
    countryNumber: "356",
    pattern: "9999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  MU: {
    countryCode: "MU",
    countryName: "Mauritius",
    countryNumber: "230",
    pattern: "9999-9999",
    currencyCode: "MUR",
    currencySymbol: "₨",
  },
  MV: {
    countryCode: "MV",
    countryName: "Maldives",
    countryNumber: "960",
    pattern: "999-9999",
    currencyCode: "MVR",
    currencySymbol: "ރ",
  },
  MW: {
    countryCode: "MW",
    countryName: "Malawi",
    countryNumber: "265",
    pattern: "9999-9999",
    currencyCode: "MWK",
    currencySymbol: "MK",
  },
  MX: {
    countryCode: "MX",
    countryName: "Mexico",
    countryNumber: "52",
    pattern: "999-999-9999",
    currencyCode: "MXN",
    currencySymbol: "$",
  },
  MY: {
    countryCode: "MY",
    countryName: "Malaysia",
    countryNumber: "60",
    pattern: "99-9999-9999",
    currencyCode: "MYR",
    currencySymbol: "RM",
  },
  MZ: {
    countryCode: "MZ",
    countryName: "Mozambique",
    countryNumber: "258",
    pattern: "99-999-999",
    currencyCode: "MZN",
    currencySymbol: "MT",
  },
  NA: {
    countryCode: "NA",
    countryName: "Namibia",
    countryNumber: "264",
    pattern: "99-999-999",
    currencyCode: "NAD",
    currencySymbol: "$",
  },
  NC: {
    countryCode: "NC",
    countryName: "New Caledonia",
    countryNumber: "687",
    pattern: "99-99-99",
    currencyCode: "XPF",
    currencySymbol: "₣",
  },
  NE: {
    countryCode: "NE",
    countryName: "Niger",
    countryNumber: "227",
    pattern: "99-99-99",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  NF: {
    countryCode: "NF",
    countryName: "Norfolk Island",
    countryNumber: "672",
    pattern: "99-999-999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  NG: {
    countryCode: "NG",
    countryName: "Nigeria",
    countryNumber: "234",
    pattern: "99-999-9999",
    currencyCode: "NGN",
    currencySymbol: "₦",
  },
  NI: {
    countryCode: "NI",
    countryName: "Nicaragua",
    countryNumber: "505",
    pattern: "9999-9999",
    currencyCode: "NIO",
    currencySymbol: "C$",
  },
  NL: {
    countryCode: "NL",
    countryName: "Netherlands",
    countryNumber: "31",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  NO: {
    countryCode: "NO",
    countryName: "Norway",
    countryNumber: "47",
    pattern: "99-99-99-99",
    currencyCode: "NOK",
    currencySymbol: "kr",
  },
  NP: {
    countryCode: "NP",
    countryName: "Nepal",
    countryNumber: "977",
    pattern: "99-9999999",
    currencyCode: "NPR",
    currencySymbol: "₨",
  },
  NR: {
    countryCode: "NR",
    countryName: "Nauru",
    countryNumber: "674",
    pattern: "999-999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  NU: {
    countryCode: "NU",
    countryName: "Niue",
    countryNumber: "683",
    pattern: "9999-9999",
    currencyCode: "NZD",
    currencySymbol: "$",
  },
  NZ: {
    countryCode: "NZ",
    countryName: "New Zealand",
    countryNumber: "64",
    pattern: "99-999-9999",
    currencyCode: "NZD",
    currencySymbol: "$",
  },
  OM: {
    countryCode: "OM",
    countryName: "Oman",
    countryNumber: "968",
    pattern: "99-999-999",
    currencyCode: "OMR",
    currencySymbol: "ر.ع.",
  },
  PA: {
    countryCode: "PA",
    countryName: "Panama",
    countryNumber: "507",
    pattern: "9999-9999",
    currencyCode: "PAB",
    currencySymbol: "B/.",
  },
  PE: {
    countryCode: "PE",
    countryName: "Peru",
    countryNumber: "51",
    pattern: "999-999-999",
    currencyCode: "PEN",
    currencySymbol: "S/.",
  },
  PF: {
    countryCode: "PF",
    countryName: "French Polynesia",
    countryNumber: "689",
    pattern: "99-99-99",
    currencyCode: "XPF",
    currencySymbol: "₣",
  },
  PG: {
    countryCode: "PG",
    countryName: "Papua New Guinea",
    countryNumber: "675",
    pattern: "9999-9999",
    currencyCode: "PGK",
    currencySymbol: "K",
  },
  PH: {
    countryCode: "PH",
    countryName: "Philippines",
    countryNumber: "63",
    pattern: "9999-9999",
    currencyCode: "PHP",
    currencySymbol: "₱",
  },
  PK: {
    countryCode: "PK",
    countryName: "Pakistan",
    countryNumber: "92",
    pattern: "99-9999999",
    currencyCode: "PKR",
    currencySymbol: "₨",
  },
  PL: {
    countryCode: "PL",
    countryName: "Poland",
    countryNumber: "48",
    pattern: "99-999-99-99",
    currencyCode: "PLN",
    currencySymbol: "zł",
  },
  PM: {
    countryCode: "PM",
    countryName: "Saint Pierre and Miquelon",
    countryNumber: "508",
    pattern: "99-99-99",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  PN: {
    countryCode: "PN",
    countryName: "Pitcairn",
    countryNumber: "64",
    pattern: "9999-9999",
    currencyCode: "NZD",
    currencySymbol: "NZ$",
  },
  PR: {
    countryCode: "PR",
    countryName: "Puerto Rico",
    countryNumber: "1-787",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  PS: {
    countryCode: "PS",
    countryName: "Palestine",
    countryNumber: "970",
    pattern: "99-999-9999",
    currencyCode: "ILS",
    currencySymbol: "₪",
  },
  PT: {
    countryCode: "PT",
    countryName: "Portugal",
    countryNumber: "351",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  PW: {
    countryCode: "PW",
    countryName: "Palau",
    countryNumber: "680",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  PY: {
    countryCode: "PY",
    countryName: "Paraguay",
    countryNumber: "595",
    pattern: "999-999-999",
    currencyCode: "PYG",
    currencySymbol: "₲",
  },
  QA: {
    countryCode: "QA",
    countryName: "Qatar",
    countryNumber: "974",
    pattern: "9999-9999",
    currencyCode: "QAR",
    currencySymbol: "ر.ق",
  },
  RE: {
    countryCode: "RE",
    countryName: "Réunion",
    countryNumber: "262",
    pattern: "99-99-99",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  RO: {
    countryCode: "RO",
    countryName: "Romania",
    countryNumber: "40",
    pattern: "99-999-9999",
    currencyCode: "RON",
    currencySymbol: "lei",
  },
  RS: {
    countryCode: "RS",
    countryName: "Serbia",
    countryNumber: "381",
    pattern: "99-999-9999",
    currencyCode: "RSD",
    currencySymbol: "дин.",
  },
  RU: {
    countryCode: "RU",
    countryName: "Russian Federation",
    countryNumber: "7",
    pattern: "999-999-99-99",
    currencyCode: "RUB",
    currencySymbol: "₽",
  },
  RW: {
    countryCode: "RW",
    countryName: "Rwanda",
    countryNumber: "250",
    pattern: "99-9999-9999",
    currencyCode: "RWF",
    currencySymbol: "RF",
  },
  SA: {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    countryNumber: "966",
    pattern: "9999-9999",
    currencyCode: "SAR",
    currencySymbol: "ر.س",
  },
  SB: {
    countryCode: "SB",
    countryName: "Solomon Islands",
    countryNumber: "677",
    pattern: "99-99999",
    currencyCode: "SBD",
    currencySymbol: "$",
  },
  SC: {
    countryCode: "SC",
    countryName: "Seychelles",
    countryNumber: "248",
    pattern: "4-999-999",
    currencyCode: "SCR",
    currencySymbol: "₨",
  },
  SD: {
    countryCode: "SD",
    countryName: "Sudan",
    countryNumber: "249",
    pattern: "999-999-999",
    currencyCode: "SDG",
    currencySymbol: "SD",
  },
  SE: {
    countryCode: "SE",
    countryName: "Sweden",
    countryNumber: "46",
    pattern: "99-999-99-99",
    currencyCode: "SEK",
    currencySymbol: "kr",
  },
  SG: {
    countryCode: "SG",
    countryName: "Singapore",
    countryNumber: "65",
    pattern: "9999-9999",
    currencyCode: "SGD",
    currencySymbol: "S$",
  },
  SH: {
    countryCode: "SH",
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    countryNumber: "290",
    pattern: "9-99999",
    currencyCode: "SHP",
    currencySymbol: "£",
  },
  SI: {
    countryCode: "SI",
    countryName: "Slovenia",
    countryNumber: "386",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  SJ: {
    countryCode: "SJ",
    countryName: "Svalbard and Jan Mayen",
    countryNumber: "47",
    pattern: "99-99-99-99",
    currencyCode: "NOK",
    currencySymbol: "kr",
  },
  SK: {
    countryCode: "SK",
    countryName: "Slovakia",
    countryNumber: "421",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  SL: {
    countryCode: "SL",
    countryName: "Sierra Leone",
    countryNumber: "232",
    pattern: "99-999999",
    currencyCode: "SLL",
    currencySymbol: "Le",
  },
  SM: {
    countryCode: "SM",
    countryName: "San Marino",
    countryNumber: "378",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  SN: {
    countryCode: "SN",
    countryName: "Senegal",
    countryNumber: "221",
    pattern: "99-999-9999",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  SO: {
    countryCode: "SO",
    countryName: "Somalia",
    countryNumber: "252",
    pattern: "9-999999",
    currencyCode: "SOS",
    currencySymbol: "S",
  },
  SR: {
    countryCode: "SR",
    countryName: "Suriname",
    countryNumber: "597",
    pattern: "999-9999",
    currencyCode: "SRD",
    currencySymbol: "$",
  },
  SS: {
    countryCode: "SS",
    countryName: "South Sudan",
    countryNumber: "211",
    pattern: "99-999-9999",
    currencyCode: "SSP",
    currencySymbol: "£",
  },
  ST: {
    countryCode: "ST",
    countryName: "Sao Tome and Principe",
    countryNumber: "239",
    pattern: "99-99999",
    currencyCode: "STN",
    currencySymbol: "Db",
  },
  SV: {
    countryCode: "SV",
    countryName: "El Salvador",
    countryNumber: "503",
    pattern: "9999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  SX: {
    countryCode: "SX",
    countryName: "Sint Maarten (Dutch part)",
    countryNumber: "1-721",
    pattern: "999-9999",
    currencyCode: "ANG",
    currencySymbol: "ƒ",
  },
  SY: {
    countryCode: "SY",
    countryName: "Syrian Arab Republic",
    countryNumber: "963",
    pattern: "9999-999-999",
    currencyCode: "SYP",
    currencySymbol: "£",
  },
  SZ: {
    countryCode: "SZ",
    countryName: "Swaziland",
    countryNumber: "268",
    pattern: "99-999-9999",
    currencyCode: "SZL",
    currencySymbol: "E",
  },
  TC: {
    countryCode: "TC",
    countryName: "Turks and Caicos Islands",
    countryNumber: "1-649",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  TD: {
    countryCode: "TD",
    countryName: "Chad",
    countryNumber: "235",
    pattern: "99-99-99-99",
    currencyCode: "XAF",
    currencySymbol: "FCFA",
  },
  TF: {
    countryCode: "TF",
    countryName: "French Southern Territories",
    countryNumber: "262",
    pattern: "99-99-99-99",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  TG: {
    countryCode: "TG",
    countryName: "Togo",
    countryNumber: "228",
    pattern: "99-999-9999",
    currencyCode: "XOF",
    currencySymbol: "CFA",
  },
  TH: {
    countryCode: "TH",
    countryName: "Thailand",
    countryNumber: "66",
    pattern: "999-999-9999",
    currencyCode: "THB",
    currencySymbol: "฿",
  },
  TJ: {
    countryCode: "TJ",
    countryName: "Tajikistan",
    countryNumber: "992",
    pattern: "99-999-9999",
    currencyCode: "TJS",
    currencySymbol: "SM",
  },
  TK: {
    countryCode: "TK",
    countryName: "Tokelau",
    countryNumber: "690",
    pattern: "999-9999",
    currencyCode: "NZD",
    currencySymbol: "$",
  },
  TL: {
    countryCode: "TL",
    countryName: "Timor-Leste",
    countryNumber: "670",
    pattern: "999-999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  TM: {
    countryCode: "TM",
    countryName: "Turkmenistan",
    countryNumber: "993",
    pattern: "9-999-9999",
    currencyCode: "TMT",
    currencySymbol: "T",
  },
  TN: {
    countryCode: "TN",
    countryName: "Tunisia",
    countryNumber: "216",
    pattern: "99-999-999",
    currencyCode: "TND",
    currencySymbol: "د.ت",
  },
  TO: {
    countryCode: "TO",
    countryName: "Tonga",
    countryNumber: "676",
    pattern: "99999",
    currencyCode: "TOP",
    currencySymbol: "T$",
  },
  TR: {
    countryCode: "TR",
    countryName: "Turkey",
    countryNumber: "90",
    pattern: "999-999-9999",
    currencyCode: "TRY",
    currencySymbol: "₺",
  },
  TT: {
    countryCode: "TT",
    countryName: "Trinidad and Tobago",
    countryNumber: "1-868",
    pattern: "999-9999",
    currencyCode: "TTD",
    currencySymbol: "TT$",
  },
  TV: {
    countryCode: "TV",
    countryName: "Tuvalu",
    countryNumber: "688",
    pattern: "99999",
    currencyCode: "AUD",
    currencySymbol: "$",
  },
  TW: {
    countryCode: "TW",
    countryName: "Taiwan, Province of China",
    countryNumber: "886",
    pattern: "9999-999-999",
    currencyCode: "TWD",
    currencySymbol: "NT$",
  },
  TZ: {
    countryCode: "TZ",
    countryName: "United Republic of Tanzania",
    countryNumber: "255",
    pattern: "99-999-9999",
    currencyCode: "TZS",
    currencySymbol: "TSh",
  },
  UA: {
    countryCode: "UA",
    countryName: "Ukraine",
    countryNumber: "380",
    pattern: "99-999-9999",
    currencyCode: "UAH",
    currencySymbol: "₴",
  },
  UG: {
    countryCode: "UG",
    countryName: "Uganda",
    countryNumber: "256",
    pattern: "999-999999",
    currencyCode: "UGX",
    currencySymbol: "USh",
  },
  UM: {
    countryCode: "UM",
    countryName: "United States Minor Outlying Islands",
    countryNumber: "1",
    pattern: "999-999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  US: {
    countryCode: "US",
    countryName: "United States",
    countryNumber: "1",
    pattern: "999-999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  UY: {
    countryCode: "UY",
    countryName: "Uruguay",
    countryNumber: "598",
    pattern: "9-999-9999",
    currencyCode: "UYU",
    currencySymbol: "$U",
  },
  UZ: {
    countryCode: "UZ",
    countryName: "Uzbekistan",
    countryNumber: "998",
    pattern: "99-999-9999",
    currencyCode: "UZS",
    currencySymbol: "сўм",
  },
  VA: {
    countryCode: "VA",
    countryName: "Holy See (Vatican City State)",
    countryNumber: "379",
    pattern: "99-999-9999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  VC: {
    countryCode: "VC",
    countryName: "Saint Vincent and the Grenadines",
    countryNumber: "1-784",
    pattern: "999-9999",
    currencyCode: "XCD",
    currencySymbol: "$",
  },
  VE: {
    countryCode: "VE",
    countryName: "Bolivarian Republic of Venezuela",
    countryNumber: "58",
    pattern: "9999-999999",
    currencyCode: "VES",
    currencySymbol: "Bs",
  },
  VG: {
    countryCode: "VG",
    countryName: "Virgin Islands, British",
    countryNumber: "1-284",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  VI: {
    countryCode: "VI",
    countryName: "Virgin Islands, U.S.",
    countryNumber: "1-340",
    pattern: "999-9999",
    currencyCode: "USD",
    currencySymbol: "$",
  },
  VN: {
    countryCode: "VN",
    countryName: "Viet Nam",
    countryNumber: "84",
    pattern: "9999-999-999",
    currencyCode: "VND",
    currencySymbol: "₫",
  },
  VU: {
    countryCode: "VU",
    countryName: "Vanuatu",
    countryNumber: "678",
    pattern: "99-99999",
    currencyCode: "VUV",
    currencySymbol: "VT",
  },
  WF: {
    countryCode: "WF",
    countryName: "Wallis and Futuna",
    countryNumber: "681",
    pattern: "99-99-99-99",
    currencyCode: "XPF",
    currencySymbol: "₣",
  },
  WS: {
    countryCode: "WS",
    countryName: "Samoa",
    countryNumber: "685",
    pattern: "99-99999",
    currencyCode: "WST",
    currencySymbol: "WS$",
  },
  XK: {
    countryCode: "XK",
    countryName: "Kosovo",
    countryNumber: "383",
    pattern: "999-999-999",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  YE: {
    countryCode: "YE",
    countryName: "Yemen",
    countryNumber: "967",
    pattern: "999-999-999",
    currencyCode: "YER",
    currencySymbol: "﷼",
  },
  YT: {
    countryCode: "YT",
    countryName: "Mayotte",
    countryNumber: "262",
    pattern: "99-99-99-99",
    currencyCode: "EUR",
    currencySymbol: "€",
  },
  ZA: {
    countryCode: "ZA",
    countryName: "South Africa",
    countryNumber: "27",
    pattern: "99-999-9999",
    currencyCode: "ZAR",
    currencySymbol: "R",
  },
  ZM: {
    countryCode: "ZM",
    countryName: "Zambia",
    countryNumber: "260",
    pattern: "999-999999",
    currencyCode: "ZMW",
    currencySymbol: "ZK",
  },
  ZW: {
    countryCode: "ZW",
    countryName: "Zimbabwe",
    countryNumber: "263",
    pattern: "9-999999",
    currencyCode: "ZWL",
    currencySymbol: "Z$",
  },
  OT: {
    countryCode: "OT",
    countryName: "Other",
    countryNumber: "",
  },
};

export function getCountry(countryCode: string): Country | undefined {
  return COUNTRIES[countryCode?.toUpperCase()];
}

export function getAllCountryCodes(): string[] {
  return Object.keys(COUNTRIES);
}

export function getFlagUrl(countryCode: string): string {
  if (!countryCode) return "";
  return `https://flagcdn.com/256x192/${countryCode.toLowerCase()}.png`;
}

const flagImageCache = new Map<string, HTMLImageElement>();

export function loadFlagImage(
  countryCode: string
): Promise<HTMLImageElement | null> {
  return new Promise((resolve) => {
    const cached = flagImageCache.get(countryCode);
    if (cached && cached.complete) {
      resolve(cached);
      return;
    }

    const img = new Image();
    img.crossOrigin = "anonymous";

    img.onload = () => {
      flagImageCache.set(countryCode, img);
      resolve(img);
    };

    img.onerror = () => {
      resolve(null);
    };

    img.src = `https://flagcdn.com/256x192/${countryCode.toLowerCase()}.png`;
  });
}

export function drawFlagSync(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  countryCode: string
): void {
  if (!countryCode) return;

  const cached = flagImageCache.get(countryCode);
  if (cached && cached.complete) {
    ctx.drawImage(cached, x, y, width, height);
    return;
  }

  ctx.fillStyle = "#E0E0E0";
  ctx.fillRect(x, y, width, height);
  ctx.strokeStyle = "#CCCCCC";
  ctx.lineWidth = 1;
  ctx.strokeRect(x, y, width, height);

  loadFlagImage(countryCode);
}
