export const Styles = {
  popperRootStyle: {
    margin: "60px 0.5em 0.5em 1em !important",
    borderRadius: "0.75em",
    backgroundColor: "#fff",
    zIndex: 1300,
    boxShadow: "0px 0px 20px rgba(0, 0, 0, 0.25)",
    boxSizing: "border-box",
  },
  wrapperContainerStyle: {
    width: "31.25em",
    height: "15em",
    display: "grid",
    gridTemplateRows: "auto auto 1fr",
    gap: "1em",
    padding: "0.5em",
  },
  searchWrapperStyle: {
    backgroundColor: "#ECEFF1",
    display: "flex",
    gap: "0.5em",
    borderRadius: "0.75em",
    height: "2.5em",
    alignItems: "center",
    paddingLeft: "0.5em",
  },
  listContainerStyle: {
    width: "30em",
    height: "15em",
    padding: "0.5em",
    overflow: "hidden auto",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    "& p:hover": {
      backgroundColor: "#ECEFF1",
      borderRadius: "0.75em",
    },
  } as const,
  noItemsFoundStyle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  optionStyle: {
    cursor: "pointer",
    textWrap: "wrap",
    padding: "0.5em",
  },
};
