const FIELD_OPTIONS_MAPPING = [
	{ label: "Predefined Data Enhancements", value: "ENRICHMENT" },
	{ label: "Short Text", value: "SHORT_TEXT" },
	{ label: "Long Text", value: "LONG_TEXT" },
	{ label: "Number", value: "NUMBER" },
	{ label: "Email", value: "EMAIL" },
	{ label: "Address", value: "ADDRESS" },
	{ label: "Currency", value: "CURRENCY" },
	{ label: "Phone Number", value: "PHONE_NUMBER" },
	{ label: "Yes/No", value: "YES_NO" },
	{ label: "Single Choice", value: "SCQ" },
	{ label: "Multiple Choice", value: "MCQ" },
	{ label: "Dropdown", value: "DROP_DOWN" },
	{ label: "Dropdown", value: "DROP_DOWN_STATIC" },
	{ label: "Date", value: "DATE" },
	{ label: "Time", value: "TIME" },
	{ label: "File Upload", value: "FILE_PICKER" },
	{ label: "Zip Code", value: "ZIP_CODE" },
	{ label: "Signature", value: "SIGNATURE" },
	{ label: "Formula", value: "FORMULA" },
	{ label: "Ranking", value: "RANKING" },
	{ label: "List", value: "LIST" },
	{ label: "Created Time", value: "CREATED_TIME" },
	{ label: "Rating", value: "RATING" },
];

export { FIELD_OPTIONS_MAPPING };
