/**
 * Shared form theme constants for template library and preview.
 * Single source of truth used by Theme Manager and form preview.
 */

export const TEMPLATE_LIBRARY_THEMES = [
  {
    id: "template-default-theme",
    name: "Default Theme",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#263238",
      description: "#263238",
      answer: "#263238",
      buttons: "#000000",
      buttonText: "#FFFFFF",
      backgroundColor: "#FFFFFF",
      backgroundImage: "",
    },
  },
  {
    id: "template-christmas-red-frost",
    name: "Christmas Red Frost",
    styles: {
      fontFamily: "Georgia",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#ffffff",
      description: "#ffffff",
      answer: "#263238",
      buttons: "#ffffff",
      buttonText: "#800000",
      backgroundColor: "#FFFFFF",
      backgroundImage:
        "https://ccc.oute.app/1234567890/1766487918371/Chritsmas%28Red%29%20form%20theme.webp",
    },
  },
  {
    id: "template-christmas-crimson-snow",
    name: "Christmas Crimson Snow",
    styles: {
      fontFamily: "Playfair Display",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#263238",
      description: "#263238",
      answer: "#263238",
      buttons: "#000000",
      buttonText: "#FFFFFF",
      backgroundColor: "#FFFFFF",
      backgroundImage:
        "https://ccc.oute.app/1234567890/1766488259019/Christmas%20Crimson%20Snow.webp",
    },
  },
  {
    id: "template-christmas-santas-journey",
    name: "Christmas Santa's Journey",
    styles: {
      fontFamily: "EB Garamond",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#ffffff",
      description: "#ffffff",
      answer: "#263238",
      buttons: "#ffffff",
      buttonText: "#c1181d",
      backgroundColor: "#FFFFFF",
      backgroundImage:
        "https://ccc.oute.app/1234567890/1766572483073/screen%20%281%29.gif",
    },
  },
  {
    id: "template-purple-haze",
    name: "Purple Haze",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#3400AD",
      description: "#3400AD",
      answer: "#280085",
      buttons: "#4e01ad",
      buttonText: "#FFFFFF",
      backgroundColor: "white",
      backgroundImage: "https://ccc.oute.app/test/1737983268787/Theme1.webp",
    },
  },
  {
    id: "template-blue-echo",
    name: "Blue Echo",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#0048bd",
      description: "#0048bd",
      answer: "#002E8A",
      buttons: "#1a55cb",
      buttonText: "#FFFFFF",
      backgroundColor: "#7d26cd",
      backgroundImage: "https://ccc.oute.app/test/1737957536775/Theme2.webp",
    },
  },
  {
    id: "template-white-space",
    name: "White Space",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#27323a",
      description: "#27323a",
      answer: "#27323a",
      buttons: "#27323a",
      buttonText: "#FFFFFF",
      backgroundColor: "#f4757c",
      backgroundImage: "https://ccc.oute.app/test/1737956864922/Theme3.webp",
    },
  },
  {
    id: "template-dark-bloom",
    name: "Dark Bloom",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#51C2AB",
      description: "#51C2AB",
      answer: "#004739",
      buttons: "#317C70",
      buttonText: "#FFFFFF",
      backgroundColor: "#ffdc6d",
      backgroundImage: "https://ccc.oute.app/test/1738051462748/Theme4.webp",
    },
  },
  {
    id: "template-clear-horizons",
    name: "Clear Horizons",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#444743",
      description: "#444743",
      answer: "#263238",
      buttons: "#2D2F2D",
      buttonText: "#FFFFFF",
      backgroundColor: "#d893d0",
      backgroundImage: "https://ccc.oute.app/test/1738051610886/Theme5.webp",
    },
  },
  {
    id: "template-tiny-command-dark",
    name: "Tiny Command Dark",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#FFFFFF",
      description: "#FFFFFF",
      answer: "#1C3693",
      buttons: "#FFFFFF",
      buttonText: "#1C3693",
      backgroundColor: "#FFFFFF",
      backgroundImage:
        "https://ccc.oute.app/test/1738132382555/Tiny%20Command%20Dark.webp",
    },
  },
  {
    id: "template-tiny-command-light",
    name: "Tiny Command Light",
    styles: {
      fontFamily: "Helvetica Neue",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#1C3693",
      description: "#1C3693",
      answer: "#1C3693",
      buttons: "#1C3693",
      buttonText: "#FFFFFF",
      backgroundColor: "#1C3693",
      backgroundImage:
        "https://ccc.oute.app/test/1738132741007/Tiny%20Command%20Light.webp",
    },
  },
];

export const PREVIEW_THEMES = [
  {
    id: "preview-ocean-breeze",
    name: "Ocean Breeze",
    styles: {
      fontFamily: "Inter",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#0A4A6B",
      description: "#0A4A6B",
      answer: "#1E6B8A",
      buttons: "#0A4A6B",
      buttonText: "#FFFFFF",
      backgroundColor: "#E8F4F8",
      backgroundImage: "",
    },
  },
  {
    id: "preview-sunset-glow",
    name: "Sunset Glow",
    styles: {
      fontFamily: "Roboto",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#FFFFFF",
      description: "#FFFFFF",
      answer: "#FFF4E6",
      buttons: "#FF6B35",
      buttonText: "#FFFFFF",
      backgroundColor: "#FF8C42",
      backgroundImage: "",
    },
  },
  {
    id: "preview-forest-green",
    name: "Forest Green",
    styles: {
      fontFamily: "Open Sans",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#1B4332",
      description: "#1B4332",
      answer: "#2D6A4F",
      buttons: "#2D6A4F",
      buttonText: "#FFFFFF",
      backgroundColor: "#F1F8F4",
      backgroundImage: "",
    },
  },
  {
    id: "preview-midnight-blue",
    name: "Midnight Blue",
    styles: {
      fontFamily: "Poppins",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#FFFFFF",
      description: "#E0E7FF",
      answer: "#C7D2FE",
      buttons: "#6366F1",
      buttonText: "#FFFFFF",
      backgroundColor: "#1E1B4B",
      backgroundImage: "",
    },
  },
  {
    id: "preview-rose-gold",
    name: "Rose Gold",
    styles: {
      fontFamily: "Lato",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#4A2C2A",
      description: "#4A2C2A",
      answer: "#6B3E3A",
      buttons: "#D4A574",
      buttonText: "#FFFFFF",
      backgroundColor: "#FFF5F0",
      backgroundImage: "",
    },
  },
  {
    id: "preview-lavender-dreams",
    name: "Lavender Dreams",
    styles: {
      fontFamily: "Montserrat",
      questionSize: "M",
      buttonCorners: "rounded",
      textAlignment: "center",
      questions: "#4C1D95",
      description: "#4C1D95",
      answer: "#6D28D9",
      buttons: "#8B5CF6",
      buttonText: "#FFFFFF",
      backgroundColor: "#F5F3FF",
      backgroundImage: "",
    },
  },
  {
    id: "preview-coral-reef",
    name: "Coral Reef",
    styles: {
      fontFamily: "Nunito",
      questionSize: "M",
      buttonCorners: "circular",
      textAlignment: "center",
      questions: "#FFFFFF",
      description: "#FFFFFF",
      answer: "#FFE5E5",
      buttons: "#FF6B6B",
      buttonText: "#FFFFFF",
      backgroundColor: "#FF8787",
      backgroundImage: "",
    },
  },
];

export const DEFAULT_THEME = TEMPLATE_LIBRARY_THEMES[0];

/** @deprecated Use TEMPLATE_LIBRARY_THEMES for template library. Kept for backwards compatibility. */
export const GALLERY_THEMES = TEMPLATE_LIBRARY_THEMES;
