export {
  getSearchConfig,
  getMode,
  ADD_SIDEBAR_COMPONENT as ADD_NODE_COMPONENT,
  INTEGRATIONS,
  JUMP_TO_NODE_COMPONENT,
  GLOBAL_PARAMS_COMPONENT,
  HELP_COMPONENT,
  INTEGRATION_COMPONENT,
} from "../components/canvas/config";
