import _ from "lodash";
import {
  RequestAuthType,
  RequestBodyType,
  RequestMethodType,
  RequestRawDataType,
} from "../../classes";
import { CONTENT_TYPE, HEADER, PARAMS } from "./constant";
import { convertJsonToGridSchema } from "@oute/oute-ds.molecule.input-grid-v2/components";
import { HTTP_ERRORS } from "../../utils/errorEnums";

export const isCurlCommand = (input) => /curl\s+/.test(input);

export const transformObjectToRows = (data) => {
  return Object.entries(data).map(([key, value]) => ({
    expand: false,
    rowid: _.uniqueId(Date.now()),
    key: key,
    value: createPrimitive(value),
    valueStr: value,
  }));
};

export const subTypeOptions =
  new RequestRawDataType().getAllRequestRawDataTypes();

export const methodOptions = new RequestMethodType().getAllRequestMethodTypes();

export const authorizationOptions =
  new RequestAuthType().getAllRequestAuthTypes();

export const radioGroupData = new RequestBodyType()
  .getAllRequestBodyTypes()
  .map((data) => ({
    value: data,
    labelText: data,
  }));

export const createPrimitive = (value) => {
  return {
    type: "fx",
    blocks: [
      {
        type: "PRIMITIVES",
        value,
      },
    ],
  };
};

const updateRequestBody = (bodyData, bodyInfo, httpData) => {
  httpData.body_type = bodyInfo.body_type;

  if (!_.isEmpty(bodyData)) {
    switch (bodyInfo.body_type) {
      case RequestBodyType.RAW:
        httpData.subType =
          subTypeOptions.find(
            (option) => option.id === bodyInfo.body_sub_type
          ) || subTypeOptions[0];

        if (httpData.subType.id !== RequestRawDataType.JSON.id) {
          httpData.rawData = createPrimitive(JSON.stringify(bodyData));
        } else {
          httpData.rawData = convertJsonToGridSchema({ "": { ...bodyData } });
        }
        break;
      case RequestBodyType.FORM_DATA:
        httpData.formGridData = transformObjectToRows(bodyData);
        break;
      case RequestBodyType.X_WWW_FORM_URL_ENCODED: {
        /* Not sure about the reason behind this logic. But it seems incorrect and the right implementation is handled below. */
        /* 
          const urlEncodedData = queryStringToObject(bodyData); 
          httpData.urlencodedGridData = transformObjectToRows(urlEncodedData);
         */
        httpData.urlencodedGridData = transformObjectToRows(bodyData);
        break;
      }
      default:
        break;
    }
  }
};

export const queryStringToObject = (queryString) => {
  queryString.split("&").reduce((acc, pair) => {
    const [key, value] = pair.split("=");
    acc[decodeURIComponent(key)] = decodeURIComponent(value);
    return acc;
  }, {});
};

export const parsedCurlJSONToHttpData = (parsedCurlJSON) => {
  if (_.isEmpty(parsedCurlJSON)) return;
  const httpData = {};
  for (const [key, value] of Object.entries(parsedCurlJSON)) {
    switch (key) {
      case "headers":
        httpData.headers = transformObjectToRows(value);
        break;
      case "method":
        httpData.method =
          methodOptions.find((option) => option === value) || methodOptions[0];
        break;
      case "body_info": {
        let body_type = value.type;
        let body_sub_type = value.sub_type;
        let body = parsedCurlJSON.body;
        /* Not sure about the reason behind this logic. Commenting it as it seems unnecessary */
        // if (
        //   parsedCurlJSON?.headers?.["Content-Type"] ===
        //   RequestBodyType.X_WWW_FORM_URL_ENCODED
        // ) {
        //   body_type = RequestBodyType.X_WWW_FORM_URL_ENCODED;
        // }
        updateRequestBody(body, { body_type, body_sub_type }, httpData);
        break;
      }
      case "url": {
        const urlFromCurl = createPrimitive(value);
        httpData.url = { ...urlFromCurl, text: value };
        break;
      }
      case "query_params":
        httpData.query_params = transformObjectToRows(value);
        break;
      default:
        break;
    }
  }
  return httpData;
};

export const createContentTypeRow = (contentType) => {
  return {
    rowid: _.uniqueId(Date.now()),
    expand: false,
    key: CONTENT_TYPE,
    value: createPrimitive(contentType),
    valueStr: contentType,
    autoGenerated: true,
  };
};

// const checkWholeNumber = (key, value, errors) => {
//   const errorMessage = `${HTTP_ERRORS.NOT_WHOLE_NUMBER} ${key}`;
//   if (!errors.includes(errorMessage) && !Number.isInteger(Number(value))) {
//     errors.push(errorMessage);
//   }
// };

const isFxTypeWithEmptyBlocks = (item) => {
  if (!item.value) return true;
  return (
    item.value?.type === "fx" &&
    Array.isArray(item.value.blocks) &&
    item.value.blocks.length === 0
  );
};

const checkBlocksArrayIsEmpty = (data) => {
  return data.some(isFxTypeWithEmptyBlocks);
};

const isDataEmpty = (data) => {
  return data.some((item) => {
    const hasKey = !!item.key;
    const isFxEmpty = isFxTypeWithEmptyBlocks(item);
    return !hasKey && !isFxEmpty; // invalid case
  });
};

export const checkEmptyFields = (data, type) => {
  if (type === HEADER) {
    if (isDataEmpty(data)) {
      return HTTP_ERRORS.EMPTY_HEADERS_FIELDS;
    } else {
      return null;
    }
  }
  if (type === PARAMS) {
    if (isDataEmpty(data)) {
      return HTTP_ERRORS.EMPTY_PARAMS_FIELDS;
    } else {
      return null;
    }
  }
};

export const checkBody = (bodyData) => {
  // Initialize a Set with existing errors to prevent duplicates
  const errorMessageSet = new Set();

  // Iterate over bodyData using a for loop
  for (let i = 0; bodyData && i < bodyData.length; i++) {
    const row = bodyData[i];

    if (!row.key && (!isFxTypeWithEmptyBlocks(row) || row.default)) {
      if (!errorMessageSet.has(HTTP_ERRORS.EMPTY_KEY_COLUMN_BODY)) {
        errorMessageSet.add(HTTP_ERRORS.EMPTY_KEY_COLUMN_BODY);
      }
      break;
    }

    //removed the value fields related error texts as it is not needed

    // If both errors have been found, exit the loop early
    // if (
    //   errorMessageSet.has(HTTP_ERRORS.EMPTY_KEY_COLUMN_BODY) &&
    //   errorMessageSet.has(HTTP_ERRORS.EMPTY_VALUE_COLUMN_BODY)
    // ) {
    //   break;
    // }

    // if (!errorMessageSet.has(HTTP_ERRORS.EMPTY_KEY_COLUMN_BODY) && !row.key) {
    //   errorMessageSet.add(HTTP_ERRORS.EMPTY_KEY_COLUMN_BODY);
    // }

    // if (
    //   !errorMessageSet.has(HTTP_ERRORS.EMPTY_VALUE_COLUMN_BODY) &&
    //   isFxTypeWithEmptyBlocks(row)
    // ) {
    //   errorMessageSet.add(HTTP_ERRORS.EMPTY_VALUE_COLUMN_BODY);
    // }
  }

  return Array.from(errorMessageSet);
};

export const checkAuthorization = (data) => {
  if (checkBlocksArrayIsEmpty(data)) {
    return HTTP_ERRORS.INVALID_AUTH;
  }
};

export const checkFormData = (data, errors) => {
  data?.body?.data?.forEach((row) => checkBody(row, errors));
};
