import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { ExpandedRecordModal } from '../expanded-record-modal';
import { CellType } from '@/types';

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string) => {
      const map: Record<string, string> = {
        'records.recordDetails': 'Record Details',
        'records.of': 'of',
        'records.duplicateRecord': 'Duplicate Record',
        'records.copyRecordUrl': 'Copy Record URL',
        'records.askAi': 'Ask AI',
        'records.deleteRecord': 'Delete Record',
        'records.enterZipCode': 'Enter zip code',
        'records.enterCommaValues': 'Enter values',
        'records.enterRank': 'Enter rank',
        'records.noSignature': 'No signature',
        'fields.autoGenerated': 'Auto-generated',
        'fields.computed': 'Computed',
        'comments.comments': 'Comments',
        'history.history': 'History',
        close: 'Close',
        save: 'Save',
      };
      return map[key] || key;
    },
    i18n: { language: 'en' },
  }),
}));

vi.mock('@/services/api', () => ({
  getFileUploadUrl: vi.fn(),
  uploadFileToPresignedUrl: vi.fn(),
  confirmFileUpload: vi.fn(),
  updateLinkCell: vi.fn(),
  searchForeignRecords: vi.fn(),
  triggerButtonClick: vi.fn(),
}));

vi.mock('@/stores/ai-chat-store', () => ({
  useAIChatStore: Object.assign(vi.fn(() => ({})), {
    getState: vi.fn(() => ({
      setContextPrefill: vi.fn(),
      setIsOpen: vi.fn(),
    })),
  }),
}));

vi.mock('@/components/comments/comment-panel', () => ({
  CommentPanel: () => <div data-testid="comment-panel">Comments</div>,
}));

vi.mock('@/components/record-history-panel', () => ({
  RecordHistoryPanel: () => <div data-testid="history-panel">History</div>,
}));

const columns = [
  { id: 'col-1', name: 'Name', type: CellType.String, width: 200 },
  { id: 'col-2', name: 'Age', type: CellType.Number, width: 100 },
  { id: 'col-3', name: 'Active', type: CellType.Checkbox, width: 80 },
];

const record = {
  id: 'rec-1',
  cells: {
    'col-1': { type: CellType.String, data: 'Alice', displayData: 'Alice' },
    'col-2': { type: CellType.Number, data: 30, displayData: '30' },
    'col-3': { type: CellType.Checkbox, data: true, displayData: 'true' },
  },
};

describe('ExpandedRecordModal', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('does not render when record is null', () => {
    const { container } = render(
      <ExpandedRecordModal
        open={true}
        record={null}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
      />
    );
    expect(container.innerHTML).toBe('');
  });

  it('renders record details title', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
      />
    );
    expect(screen.getByText('Record Details')).toBeInTheDocument();
  });

  it('renders all columns as field rows', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
      />
    );
    expect(screen.getByText('Name')).toBeInTheDocument();
    expect(screen.getByText('Age')).toBeInTheDocument();
    expect(screen.getByText('Active')).toBeInTheDocument();
  });

  it('renders field values', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
      />
    );
    expect(screen.getByDisplayValue('Alice')).toBeInTheDocument();
  });

  it('shows record counter when totalRecords and currentIndex provided', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
        currentIndex={2}
        totalRecords={10}
      />
    );
    expect(screen.getByText('3 of 10')).toBeInTheDocument();
  });

  it('calls onClose when Close button clicked', () => {
    const onClose = vi.fn();
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={onClose}
        onSave={vi.fn()}
      />
    );
    const closeButtons = screen.getAllByText('Close');
    const footerClose = closeButtons.find(el => el.tagName === 'BUTTON' || el.closest('button'));
    if (footerClose) {
      const btn = footerClose.closest('button') || footerClose;
      fireEvent.click(btn);
    }
    expect(onClose).toHaveBeenCalled();
  });

  it('calls onSave with edited values on Save', () => {
    const onSave = vi.fn();
    const onClose = vi.fn();
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={onClose}
        onSave={onSave}
      />
    );
    const nameInput = screen.getByDisplayValue('Alice');
    fireEvent.change(nameInput, { target: { value: 'Bob' } });
    fireEvent.click(screen.getByText('Save'));
    expect(onSave).toHaveBeenCalledWith('rec-1', expect.objectContaining({ 'col-1': 'Bob' }));
  });

  it('calls onPrev when previous button clicked', () => {
    const onPrev = vi.fn();
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
        onPrev={onPrev}
        hasPrev={true}
      />
    );
    const buttons = screen.getAllByRole('button');
    const prevBtn = buttons.find(b => !b.disabled && b.querySelector('.lucide-chevron-left'));
    if (prevBtn) {
      fireEvent.click(prevBtn);
      expect(onPrev).toHaveBeenCalled();
    }
  });

  it('disables prev button when hasPrev is false', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
        hasPrev={false}
        hasNext={true}
      />
    );
    const buttons = screen.getAllByRole('button');
    const prevBtn = buttons.find(b => b.querySelector('.lucide-chevron-left'));
    if (prevBtn) expect(prevBtn).toBeDisabled();
  });

  it('calls onNext when next button clicked', () => {
    const onNext = vi.fn();
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
        onNext={onNext}
        hasNext={true}
      />
    );
    const buttons = screen.getAllByRole('button');
    const nextBtn = buttons.find(b => !b.disabled && b.querySelector('.lucide-chevron-right'));
    if (nextBtn) {
      fireEvent.click(nextBtn);
      expect(onNext).toHaveBeenCalled();
    }
  });

  it('renders comment panel by default', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
        tableId="tbl-1"
      />
    );
    expect(screen.getByTestId('comment-panel')).toBeInTheDocument();
  });

  it('renders string field editor for String type', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
      />
    );
    const input = screen.getByDisplayValue('Alice');
    expect(input).toHaveAttribute('type', 'text');
  });

  it('renders number field editor for Number type', () => {
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={vi.fn()}
        onSave={vi.fn()}
      />
    );
    const input = screen.getByDisplayValue('30');
    expect(input).toHaveAttribute('type', 'number');
  });

  it('does not save when no edits made', () => {
    const onSave = vi.fn();
    const onClose = vi.fn();
    render(
      <ExpandedRecordModal
        open={true}
        record={record as any}
        columns={columns as any}
        onClose={onClose}
        onSave={onSave}
      />
    );
    fireEvent.click(screen.getByText('Save'));
    expect(onSave).not.toHaveBeenCalled();
    expect(onClose).toHaveBeenCalled();
  });
});
