export interface ProspectItem {
  title: string;
  url: string;
  content: string;
}

export const companyProspectPreviewData: ProspectItem[] = [
  { title: 'Cox Automotive | Automotive Solutions', url: 'https://www.coxautoinc.com', content: 'Cox Automotive is a leading provider of products and services that span the automotive ecosystem worldwide. With a portfolio of over 25 brands and 34,000 team members, they drive every aspect of the automotive industry.' },
  { title: 'Tesla | Electric Vehicles & Clean Energy', url: 'https://www.tesla.com', content: 'Tesla accelerates the world\'s transition to sustainable energy through electric vehicles, energy storage, and solar panels. A global leader in EV technology and manufacturing.' },
  { title: 'Apple Inc. | Technology & Innovation', url: 'https://www.apple.com', content: 'Apple designs and develops world-class hardware, software, and services, including the iPhone, Mac, iPad, and Apple Watch. A global technology leader with a focus on privacy and user experience.' },
  { title: 'Microsoft | Cloud & Enterprise Software', url: 'https://www.microsoft.com', content: 'Microsoft empowers every person and organization on the planet to achieve more. Products include Azure, Microsoft 365, Dynamics 365, and LinkedIn.' },
  { title: 'Google | Search, Ads & Cloud', url: 'https://www.google.com', content: 'Google\'s mission is to organize the world\'s information and make it universally accessible. Products include Search, Ads, Google Cloud, and Android.' },
  { title: 'Amazon | E-commerce & Cloud Computing', url: 'https://www.amazon.com', content: 'Amazon is guided by four principles: customer obsession, passion for invention, commitment to operational excellence, and long-term thinking. AWS is the leading cloud platform.' },
  { title: 'Salesforce | CRM & Customer Success', url: 'https://www.salesforce.com', content: 'Salesforce is the world\'s #1 customer relationship management (CRM) platform. They help businesses connect with customers in a whole new way.' },
  { title: 'HubSpot | Marketing & Sales Platform', url: 'https://www.hubspot.com', content: 'HubSpot is a leading CRM platform with all the software, integrations, and resources you need to connect marketing, sales, content management, and customer service.' },
  { title: 'Stripe | Payments Infrastructure', url: 'https://www.stripe.com', content: 'Stripe is a technology company that builds economic infrastructure for the internet. Businesses of every size use Stripe\'s software and APIs to accept payments.' },
  { title: 'Shopify | E-commerce Platform', url: 'https://www.shopify.com', content: 'Shopify is a commerce platform that allows anyone to set up an online store and sell their products. Merchants can also sell in physical locations with Shopify POS.' },
  { title: 'Atlassian | Software Development Tools', url: 'https://www.atlassian.com', content: 'Atlassian makes tools to help teams work smarter including Jira, Confluence, and Trello. Used by over 250,000 organizations across 190 countries.' },
  { title: 'Twilio | Cloud Communications', url: 'https://www.twilio.com', content: 'Twilio is the leading cloud communications platform, helping companies build better customer engagement with APIs for messaging, voice, video, and email.' },
  { title: 'Zendesk | Customer Service Platform', url: 'https://www.zendesk.com', content: 'Zendesk is a service-first CRM company that builds software designed to improve customer relationships. Products power billions of customer conversations.' },
  { title: 'Slack | Team Communication', url: 'https://www.slack.com', content: 'Slack is where work happens. It brings your team together by replacing email with something faster, better organized, and more secure.' },
  { title: 'Notion | All-in-one Workspace', url: 'https://www.notion.so', content: 'Notion is an all-in-one workspace where you can write, plan, collaborate and get organized. It allows you to take notes, add tasks, manage projects, and more.' },
  { title: 'Figma | Collaborative Design', url: 'https://www.figma.com', content: 'Figma is a collaborative interface design tool that enables teams to create, test, and ship better designs from start to finish.' },
  { title: 'Datadog | Cloud Monitoring', url: 'https://www.datadoghq.com', content: 'Datadog is the monitoring and security platform for cloud applications. Over 20,000 customers across every industry use Datadog to observe and secure applications.' },
  { title: 'Snowflake | Cloud Data Platform', url: 'https://www.snowflake.com', content: 'Snowflake enables the data cloud, offering a cloud-built platform delivering unlimited scale, concurrency, and performance for data warehousing and analytics.' },
  { title: 'Databricks | Unified Data + AI', url: 'https://www.databricks.com', content: 'Databricks provides a unified analytics platform that accelerates innovation by unifying data engineering, data science, and machine learning.' },
  { title: 'MongoDB | Developer Data Platform', url: 'https://www.mongodb.com', content: 'MongoDB is a developer data platform that helps organizations build sophisticated applications with data. It is the most popular general purpose database platform.' },
  { title: 'Okta | Identity & Access Management', url: 'https://www.okta.com', content: 'Okta is an enterprise-grade, identity management service, built for the cloud, but compatible with many on-premises applications. It offers cloud software that helps companies manage and secure user authentication.' },
  { title: 'Cloudflare | Network Performance & Security', url: 'https://www.cloudflare.com', content: 'Cloudflare is a global network designed to make everything you connect to the internet secure, private, fast, and reliable. One of the world\'s largest networks with over 200 cities.' },
  { title: 'GitHub | Code Collaboration & DevOps', url: 'https://www.github.com', content: 'GitHub is where over 100 million developers shape the future of software. It hosts the largest source code community in the world, with Git-based version control.' },
  { title: 'Zoom | Video Communications', url: 'https://www.zoom.us', content: 'Zoom helps businesses and organizations bring their teams together in a frictionless environment to get more done. Offers video, voice, chat, and content sharing.' },
  { title: 'Asana | Project Management', url: 'https://www.asana.com', content: 'Asana is a web and mobile application designed to help teams organize, track, and manage their work. It is a visual project management tool used by teams worldwide.' },
  { title: 'Monday.com | Work OS', url: 'https://www.monday.com', content: 'Monday.com is a Work OS that powers teams to run processes, projects, and everyday work how they see fit. Over 200,000 companies worldwide use monday.com.' },
  { title: 'Intercom | Customer Messaging', url: 'https://www.intercom.com', content: 'Intercom is a conversational relationship platform (CRP) that helps businesses build better customer relationships. It brings messaging products for sales, marketing, and support together.' },
  { title: 'Amplitude | Product Analytics', url: 'https://www.amplitude.com', content: 'Amplitude is a product analytics platform that helps businesses understand their users, rapidly release better product experiences, and grow their business.' },
  { title: 'Segment | Customer Data Platform', url: 'https://www.segment.com', content: 'Segment is a Customer Data Platform (CDP) that helps companies harness first-party customer data. It simplifies collecting data and connecting to 300+ tools.' },
  { title: 'Rippling | HR & IT Management', url: 'https://www.rippling.com', content: 'Rippling is an HR management software that allows companies to manage their HR, payroll, and IT in one unified workforce platform.' },
];
