export const TYPE_MAPPING = {
  SHORT_TEXT: 'TEXT',
  LONG_TEXT: 'TEXT',
  MCQ: 'JSONB',
  SCQ: 'TEXT',
  PHONE_NUMBER: 'JSONB',
  ZIP_CODE: 'JSONB',
  DROP_DOWN: 'JSONB',
  DROP_DOWN_STATIC: 'JSONB',
  YES_NO: 'VARCHAR',
  EMAIL: 'VARCHAR',
  DATE: 'TIMESTAMPTZ',
  CURRENCY: 'JSONB',
  NUMBER: 'DOUBLE PRECISION',
  RATING: 'INTEGER',
  FILE_PICKER: 'JSONB',
  TIME: 'JSONB',
  ADDRESS: 'JSONB',
  UNKNOWN: 'TEXT',
  SIGNATURE: 'TEXT',
  FORMULA: 'TEXT',
  LIST: 'JSONB',
  ENRICHMENT: 'TEXT',
  RANKING: 'JSONB',
  SLIDER: 'INTEGER',
  OPINION_SCALE: 'INTEGER',
  LINK: 'JSONB',
  USER: 'JSONB',
  CHECKBOX: 'BOOLEAN',
  ROLLUP: 'JSONB',
  LOOKUP: 'JSONB',
  BUTTON: 'JSONB',
  AUTO_NUMBER: 'INTEGER',
};

export enum QUESTION_TYPE {
  SHORT_TEXT = 'SHORT_TEXT',
  LONG_TEXT = 'LONG_TEXT',
  MCQ = 'MCQ',
  SCQ = 'SCQ',
  PHONE_NUMBER = 'PHONE_NUMBER',
  ZIP_CODE = 'ZIP_CODE',
  DROP_DOWN = 'DROP_DOWN',
  DROP_DOWN_STATIC = 'DROP_DOWN_STATIC',
  YES_NO = 'YES_NO',
  EMAIL = 'EMAIL',
  DATE = 'DATE',
  CURRENCY = 'CURRENCY',
  NUMBER = 'NUMBER',
  RATING = 'RATING',
  FILE_PICKER = 'FILE_PICKER',
  TIME = 'TIME',
  ADDRESS = 'ADDRESS',
  SIGNATURE = 'SIGNATURE',
  UNKNOWN = 'UNKNOWN',
  LIST = 'LIST',
  ENRICHMENT = 'ENRICHMENT',
  CREATED_TIME = 'CREATED_TIME',
  RANKING = 'RANKING',
  SLIDER = 'SLIDER',
  OPINION_SCALE = 'OPINION_SCALE',
  ID = 'ID',
  FORMULA = 'FORMULA',
  LINK = 'LINK',
  USER = 'USER',
  CREATED_BY = 'CREATED_BY',
  LAST_MODIFIED_BY = 'LAST_MODIFIED_BY',
  LAST_MODIFIED_TIME = 'LAST_MODIFIED_TIME',
  AUTO_NUMBER = 'AUTO_NUMBER',
  BUTTON = 'BUTTON',
  CHECKBOX = 'CHECKBOX',
  ROLLUP = 'ROLLUP',
  LOOKUP = 'LOOKUP',
}

export const TYPE_VALUE_MAPPING = {
  SHORT_TEXT: 'string',
  LONG_TEXT: 'string',
  MCQ: 'array_of_strings',
  DROP_DOWN_STATIC: 'array_of_strings',
  SCQ: 'string',
  PHONE_NUMBER: 'object',
  ZIP_CODE: 'object',
  DROP_DOWN: 'array_of_objects',
  YES_NO: 'string',
  EMAIL: 'string',
  DATE: 'timestamptz',
  CURRENCY: 'object',
  NUMBER: 'number',
  RATING: 'number',
  FILE_PICKER: 'array_of_objects',
  TIME: 'object',
  ADDRESS: 'object',
  SIGNATURE: 'string',
  LIST: 'array_of_strings',
  ENRICHMENT: 'string',
  CREATED_TIME: 'timestamptz',
  RANKING: 'array_of_objects',
  SLIDER: 'number',
  OPINION_SCALE: 'number',
  ID: 'number',
  LINK: 'array_of_objects',
  USER: 'object',
  CREATED_BY: 'object',
  LAST_MODIFIED_BY: 'object',
  LAST_MODIFIED_TIME: 'timestamptz',
  AUTO_NUMBER: 'number',
  BUTTON: 'object',
  CHECKBOX: 'boolean',
  ROLLUP: 'object',
  LOOKUP: 'object',
};

export const JSONB_KEY_FOR_SEARCHING = {
  PHONE_NUMBER: 'phoneNumber',
  ZIP_CODE: 'zipCode',
  FILE_PICKER: 'url',
  DROP_DOWN: 'label',
  CURRENCY: 'currencyValue',
  TIME: 'time',
  ADDRESS: 'state',
  RANKING: 'label',
  LINK: 'title',
  USER: 'title',
  CREATED_BY: 'title',
  LAST_MODIFIED_BY: 'title',
  BUTTON: 'label',
};

export const keys_with_data_type_jsonb = [
  'PHONE_NUMBER',
  'FILE_PICKER',
  'MCQ',
  'DROP_DOWN_STATIC',
  'DROP_DOWN',
  'ZIP_CODE',
  'ADDRESS',
  'LIST',
  'RANKING',
  'LINK',
  'USER',
  'BUTTON',
  'ROLLUP',
  'LOOKUP',
];

export const DATA_KEYS = {
  ADDRESS: [
    'city',
    'state',
    'country',
    'zipCode',
    'fullName',
    'addressLineOne',
    'addressLineTwo',
  ],
  PHONE_NUMBER: ['countryCode', 'phoneNumber', 'countryNumber'],
  USER: ['id', 'title', 'email', 'avatarUrl'],
  CREATED_BY: ['id', 'title', 'email', 'avatarUrl'],
  LAST_MODIFIED_BY: ['id', 'title', 'email', 'avatarUrl'],
  LINK: ['id', 'title'],
  BUTTON: ['label', 'color', 'clickCount'],
};

/**
 * System Field Mapping
 * Maps system field types to their database column names
 */
export const SYSTEM_FIELD_MAPPING: Record<string, string> = {
  [QUESTION_TYPE.ID]: '__id',
  [QUESTION_TYPE.CREATED_TIME]: '__created_time',
  [QUESTION_TYPE.CREATED_BY]: '__created_by',
  [QUESTION_TYPE.LAST_MODIFIED_BY]: '__last_updated_by',
  [QUESTION_TYPE.LAST_MODIFIED_TIME]: '__last_modified_time',
  [QUESTION_TYPE.AUTO_NUMBER]: '__auto_number',
};

export const COMPUTED_FIELD_TYPES = [
  QUESTION_TYPE.FORMULA,
  QUESTION_TYPE.ROLLUP,
  QUESTION_TYPE.LOOKUP,
  QUESTION_TYPE.AUTO_NUMBER,
  QUESTION_TYPE.CREATED_TIME,
  QUESTION_TYPE.CREATED_BY,
  QUESTION_TYPE.LAST_MODIFIED_BY,
  QUESTION_TYPE.LAST_MODIFIED_TIME,
];

export const LINK_RELATIONSHIP = {
  ONE_ONE: 'oneOne',
  ONE_MANY: 'oneMany',
  MANY_ONE: 'manyOne',
  MANY_MANY: 'manyMany',
} as const;

export const ROLLUP_FUNCTIONS = [
  'countall',
  'counta',
  'count',
  'sum',
  'average',
  'max',
  'min',
  'and',
  'or',
  'xor',
  'array_join',
  'array_unique',
  'array_compact',
  'concatenate',
] as const;
