export const variables = {
  NODE: [
    {
      key: "1736936780625",
      name: "HTTP",
      type: "HTTP",
      template: "",
      background: "linear-gradient(196deg, #7D007D 2.15%, #C800C8 77.96%)",
      foreground: "#fff",
      dark: "rgb(125, 0, 125)",
      light: "rgb(200, 0, 200)",
      hasTestModule: true,
      canSkipTest: false,
      location: "-1.5777218104420236e-29 248.14999999999998",
      warnings: [],
      errors: [],
      go_data: {
        url: {
          type: "fx",
          blocks: [
            {
              type: "PRIMITIVES",
              value: "https://www.google.com",
            },
          ],
          text: "https://www.google.com",
        },
        method: "GET",
        query_params: [],
        headers: [],
        authorization: {
          type: "none",
          data: null,
        },
        body: {
          type: "none",
          data: null,
        },
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "headers",
                    type: "object",
                    sample_value: { sample: "sample" },
                    default: { sample: "sample" },
                    path: ["headers"],
                    pathStr: "{headers}",
                    schema: [
                      {
                        key: "accept-ch",
                        type: "string",
                        sample_value: "Sec-CH-Prefers-Color-Scheme",
                        default: "Sec-CH-Prefers-Color-Scheme",
                        path: ["headers", "accept-ch"],
                        pathStr: "{headers}.accept-ch",
                      },
                      {
                        key: "alt-svc",
                        type: "string",
                        sample_value:
                          'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                        default:
                          'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                        path: ["headers", "alt-svc"],
                        pathStr: "{headers}.alt-svc",
                      },
                    ],
                  },
                  {
                    key: "body",
                    type: "string",
                    sample_value: "sample",
                    default: "sample",
                    path: ["body"],
                    pathStr: "body",
                  },
                  {
                    key: "status_code",
                    type: "number",
                    sample_value: 200,
                    default: 200,
                    path: ["status_code"],
                    pathStr: "status_code",
                  },
                  {
                    key: "curl",
                    type: "string",
                    sample_value: "curl -L -X GET https://www.google.com ",
                    default: "curl -L -X GET https://www.google.com ",
                    path: ["curl"],
                    pathStr: "curl",
                  },
                ],
              },
            ],
            path: [],
            keys: [
              "{headers}",
              "{headers}.accept-ch",
              "{headers}.alt-svc",
              "body",
              "status_code",
              "curl",
            ],
            flattened_schema: [
              {
                key: "headers",
                type: "object",
                sample_value: {
                  "accept-ch": "Sec-CH-Prefers-Color-Scheme",
                  "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                  "cache-control": "private, max-age=0",
                  "content-encoding": "gzip",
                  "content-security-policy-report-only":
                    "object-src 'none';base-uri 'self';script-src 'nonce-8dJfnGTiR2TZnAW3L-kFNg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
                  "content-type": "text/html; charset=ISO-8859-1",
                  date: "Wed, 15 Jan 2025 10:26:42 GMT",
                  expires: "-1",
                  p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
                  server: "gws",
                  "set-cookie":
                    "AEC=AZ6Zc-W-MjIzg0yvpcoMdf5iUNyMbG4ZiLyYA9Zn2Rv4qWd05ElsAM_VWlo; expires=Mon, 14-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=520=RUPwAKz7FTPpR0o5492g_Z1Q_nCrMvp7VzgfQT55kyXaif5WIXeMgJXtHBJluLpUA4taJ-av7a0lLAI2GrEKAmIfWKXGUhNU5pK4AOLbKNugRMID0EZfNwmou9QGPmj_7WZvjGKCbkgGy-mEmGJSau2qc6fE87C2-LvPbkjfXJVN1z7Jfz2-wwF6dS7tzm9fNAbupX1Vbxil0Q; expires=Thu, 17-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; HttpOnly",
                  "transfer-encoding": "chunked",
                  "x-frame-options": "SAMEORIGIN",
                  "x-xss-protection": "0",
                },
                default: {
                  "accept-ch": "Sec-CH-Prefers-Color-Scheme",
                  "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                  "cache-control": "private, max-age=0",
                  "content-encoding": "gzip",
                  "content-security-policy-report-only":
                    "object-src 'none';base-uri 'self';script-src 'nonce-8dJfnGTiR2TZnAW3L-kFNg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
                  "content-type": "text/html; charset=ISO-8859-1",
                  date: "Wed, 15 Jan 2025 10:26:42 GMT",
                  expires: "-1",
                  p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
                  server: "gws",
                  "set-cookie":
                    "AEC=AZ6Zc-W-MjIzg0yvpcoMdf5iUNyMbG4ZiLyYA9Zn2Rv4qWd05ElsAM_VWlo; expires=Mon, 14-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=520=RUPwAKz7FTPpR0o5492g_Z1Q_nCrMvp7VzgfQT55kyXaif5WIXeMgJXtHBJluLpUA4taJ-av7a0lLAI2GrEKAmIfWKXGUhNU5pK4AOLbKNugRMID0EZfNwmou9QGPmj_7WZvjGKCbkgGy-mEmGJSau2qc6fE87C2-LvPbkjfXJVN1z7Jfz2-wwF6dS7tzm9fNAbupX1Vbxil0Q; expires=Thu, 17-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; HttpOnly",
                  "transfer-encoding": "chunked",
                  "x-frame-options": "SAMEORIGIN",
                  "x-xss-protection": "0",
                },
                path: ["headers"],
                pathStr: "{headers}",
              },
              {
                key: "accept-ch",
                type: "string",
                sample_value: "Sec-CH-Prefers-Color-Scheme",
                default: "Sec-CH-Prefers-Color-Scheme",
                path: ["headers", "accept-ch"],
                pathStr: "{headers}.accept-ch",
              },
              {
                key: "alt-svc",
                type: "string",
                sample_value: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                default: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                path: ["headers", "alt-svc"],
                pathStr: "{headers}.alt-svc",
              },
              {
                key: "body",
                type: "string",
                sample_value: "sample",
                default: "sample",
                path: ["body"],
                pathStr: "body",
              },
              {
                key: "status_code",
                type: "number",
                sample_value: 200,
                default: 200,
                path: ["status_code"],
                pathStr: "status_code",
              },
              {
                key: "curl",
                type: "string",
                sample_value: "curl -L -X GET https://www.google.com ",
                default: "curl -L -X GET https://www.google.com ",
                path: ["curl"],
                pathStr: "curl",
              },
            ],
          },
        },
        path_variable: {
          data: [],
        },
        errors: [],
        last_updated: 1736936803825,
      },
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "headers",
                  type: "object",
                  sample_value: {
                    "accept-ch": "Sec-CH-Prefers-Color-Scheme",
                    "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                    "cache-control": "private, max-age=0",
                    "content-encoding": "gzip",
                    "content-security-policy-report-only":
                      "object-src 'none';base-uri 'self';script-src 'nonce-8dJfnGTiR2TZnAW3L-kFNg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
                    "content-type": "text/html; charset=ISO-8859-1",
                    date: "Wed, 15 Jan 2025 10:26:42 GMT",
                    expires: "-1",
                    p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
                    server: "gws",
                    "set-cookie":
                      "AEC=AZ6Zc-W-MjIzg0yvpcoMdf5iUNyMbG4ZiLyYA9Zn2Rv4qWd05ElsAM_VWlo; expires=Mon, 14-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=520=RUPwAKz7FTPpR0o5492g_Z1Q_nCrMvp7VzgfQT55kyXaif5WIXeMgJXtHBJluLpUA4taJ-av7a0lLAI2GrEKAmIfWKXGUhNU5pK4AOLbKNugRMID0EZfNwmou9QGPmj_7WZvjGKCbkgGy-mEmGJSau2qc6fE87C2-LvPbkjfXJVN1z7Jfz2-wwF6dS7tzm9fNAbupX1Vbxil0Q; expires=Thu, 17-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; HttpOnly",
                    "transfer-encoding": "chunked",
                    "x-frame-options": "SAMEORIGIN",
                    "x-xss-protection": "0",
                  },
                  default: {
                    "accept-ch": "Sec-CH-Prefers-Color-Scheme",
                    "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                    "cache-control": "private, max-age=0",
                    "content-encoding": "gzip",
                    "content-security-policy-report-only":
                      "object-src 'none';base-uri 'self';script-src 'nonce-8dJfnGTiR2TZnAW3L-kFNg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
                    "content-type": "text/html; charset=ISO-8859-1",
                    date: "Wed, 15 Jan 2025 10:26:42 GMT",
                    expires: "-1",
                    p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
                    server: "gws",
                    "set-cookie":
                      "AEC=AZ6Zc-W-MjIzg0yvpcoMdf5iUNyMbG4ZiLyYA9Zn2Rv4qWd05ElsAM_VWlo; expires=Mon, 14-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=520=RUPwAKz7FTPpR0o5492g_Z1Q_nCrMvp7VzgfQT55kyXaif5WIXeMgJXtHBJluLpUA4taJ-av7a0lLAI2GrEKAmIfWKXGUhNU5pK4AOLbKNugRMID0EZfNwmou9QGPmj_7WZvjGKCbkgGy-mEmGJSau2qc6fE87C2-LvPbkjfXJVN1z7Jfz2-wwF6dS7tzm9fNAbupX1Vbxil0Q; expires=Thu, 17-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; HttpOnly",
                    "transfer-encoding": "chunked",
                    "x-frame-options": "SAMEORIGIN",
                    "x-xss-protection": "0",
                  },
                  path: ["headers"],
                  pathStr: "{headers}",
                  schema: [
                    {
                      key: "accept-ch",
                      type: "string",
                      sample_value: "Sec-CH-Prefers-Color-Scheme",
                      default: "Sec-CH-Prefers-Color-Scheme",
                      path: ["headers", "accept-ch"],
                      pathStr: "{headers}.accept-ch",
                    },
                    {
                      key: "alt-svc",
                      type: "string",
                      sample_value:
                        'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                      default: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                      path: ["headers", "alt-svc"],
                      pathStr: "{headers}.alt-svc",
                    },
                  ],
                },
                {
                  key: "body",
                  type: "string",
                  sample_value: "sample",
                  default: "sample",
                  path: ["body"],
                  pathStr: "body",
                },
                {
                  key: "status_code",
                  type: "number",
                  sample_value: 200,
                  default: 200,
                  path: ["status_code"],
                  pathStr: "status_code",
                },
                {
                  key: "curl",
                  type: "string",
                  sample_value: "curl -L -X GET https://www.google.com ",
                  default: "curl -L -X GET https://www.google.com ",
                  path: ["curl"],
                  pathStr: "curl",
                },
              ],
            },
          ],
          path: [],
          keys: [
            "{headers}",
            "{headers}.accept-ch",
            "{headers}.alt-svc",
            "body",
            "status_code",
            "curl",
          ],
          flattened_schema: [
            {
              key: "headers",
              type: "object",
              sample_value: {
                "accept-ch": "Sec-CH-Prefers-Color-Scheme",
                "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                "cache-control": "private, max-age=0",
                "content-encoding": "gzip",
                "content-security-policy-report-only":
                  "object-src 'none';base-uri 'self';script-src 'nonce-8dJfnGTiR2TZnAW3L-kFNg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
                "content-type": "text/html; charset=ISO-8859-1",
                date: "Wed, 15 Jan 2025 10:26:42 GMT",
                expires: "-1",
                p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
                server: "gws",
                "set-cookie":
                  "AEC=AZ6Zc-W-MjIzg0yvpcoMdf5iUNyMbG4ZiLyYA9Zn2Rv4qWd05ElsAM_VWlo; expires=Mon, 14-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=520=RUPwAKz7FTPpR0o5492g_Z1Q_nCrMvp7VzgfQT55kyXaif5WIXeMgJXtHBJluLpUA4taJ-av7a0lLAI2GrEKAmIfWKXGUhNU5pK4AOLbKNugRMID0EZfNwmou9QGPmj_7WZvjGKCbkgGy-mEmGJSau2qc6fE87C2-LvPbkjfXJVN1z7Jfz2-wwF6dS7tzm9fNAbupX1Vbxil0Q; expires=Thu, 17-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; HttpOnly",
                "transfer-encoding": "chunked",
                "x-frame-options": "SAMEORIGIN",
                "x-xss-protection": "0",
              },
              default: {
                "accept-ch": "Sec-CH-Prefers-Color-Scheme",
                "alt-svc": 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
                "cache-control": "private, max-age=0",
                "content-encoding": "gzip",
                "content-security-policy-report-only":
                  "object-src 'none';base-uri 'self';script-src 'nonce-8dJfnGTiR2TZnAW3L-kFNg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp",
                "content-type": "text/html; charset=ISO-8859-1",
                date: "Wed, 15 Jan 2025 10:26:42 GMT",
                expires: "-1",
                p3p: 'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
                server: "gws",
                "set-cookie":
                  "AEC=AZ6Zc-W-MjIzg0yvpcoMdf5iUNyMbG4ZiLyYA9Zn2Rv4qWd05ElsAM_VWlo; expires=Mon, 14-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=520=RUPwAKz7FTPpR0o5492g_Z1Q_nCrMvp7VzgfQT55kyXaif5WIXeMgJXtHBJluLpUA4taJ-av7a0lLAI2GrEKAmIfWKXGUhNU5pK4AOLbKNugRMID0EZfNwmou9QGPmj_7WZvjGKCbkgGy-mEmGJSau2qc6fE87C2-LvPbkjfXJVN1z7Jfz2-wwF6dS7tzm9fNAbupX1Vbxil0Q; expires=Thu, 17-Jul-2025 10:26:42 GMT; path=/; domain=.google.com; HttpOnly",
                "transfer-encoding": "chunked",
                "x-frame-options": "SAMEORIGIN",
                "x-xss-protection": "0",
              },
              path: ["headers"],
              pathStr: "{headers}",
            },
            {
              key: "accept-ch",
              type: "string",
              sample_value: "Sec-CH-Prefers-Color-Scheme",
              default: "Sec-CH-Prefers-Color-Scheme",
              path: ["headers", "accept-ch"],
              pathStr: "{headers}.accept-ch",
            },
            {
              key: "alt-svc",
              type: "string",
              sample_value: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
              default: 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
              path: ["headers", "alt-svc"],
              pathStr: "{headers}.alt-svc",
            },
            {
              key: "body",
              type: "string",
              sample_value: "sample",
              default: "sample",
              path: ["body"],
              pathStr: "body",
            },
            {
              key: "status_code",
              type: "number",
              sample_value: 200,
              default: 200,
              path: ["status_code"],
              pathStr: "status_code",
            },
            {
              key: "curl",
              type: "string",
              sample_value: "curl -L -X GET https://www.google.com ",
              default: "curl -L -X GET https://www.google.com ",
              path: ["curl"],
              pathStr: "curl",
            },
          ],
        },
      },
    },
    {
      key: "1736937296609",
      name: "Multi Choice",
      type: "MCQ",
      template: "roundedRectangle",
      background: "#fff",
      foreground: "rgb(38, 50, 56)",
      module: "Question",
      go_data: {
        question: "",
        description: "",
        type: "MCQ",
        module: "Question",
        buttonLabel: "<strong>NEXT</strong>",
        options: [""],
        placeholder: "",
        errors: {
          defaultValueError: "",
        },
        settings: {
          questionAlignment: "flex-start",
          required: false,
          randomize: false,
          isAlignmentVertical: true,
          other: false,
          defaultValue: [],
          selection: {
            type: "Unlimited",
            range: {
              start: "1",
              end: "2",
            },
            exactNumber: "1",
          },
          accessKey: "",
        },
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "any",
                    sample_value: null,
                    default: null,
                    path: ["response"],
                    pathStr: "response",
                  },
                ],
              },
            ],
            path: [],
            keys: ["response"],
            flattened_schema: [
              {
                key: "response",
                type: "any",
                sample_value: null,
                default: null,
                path: ["response"],
                pathStr: "response",
              },
            ],
          },
        },
        last_updated: 1736944394124,
      },
      meta: {
        search_keys: [
          "MCQ",
          "Multi-Select",
          "Checkbox Options",
          "Multiple Answers",
          "Choose Multiple",
          "Select Many",
        ],
      },
      location: "2444.999999999999 -2.1019476964872256e-45",
      warnings: [],
      errors: [],
      description: "",
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "any",
                  sample_value: null,
                  default: null,
                  path: ["response"],
                  pathStr: "response",
                },
              ],
            },
          ],
          path: [],
          keys: ["response"],
          flattened_schema: [
            {
              key: "response",
              type: "any",
              sample_value: null,
              default: null,
              path: ["response"],
              pathStr: "response",
            },
          ],
        },
      },
    },
    {
      key: "1736944168296",
      name: "Zip Code",
      type: "ZIP_CODE",
      template: "roundedRectangle",
      background: "#fff",
      foreground: "rgb(38, 50, 56)",
      module: "Question",
      go_data: {
        question:
          '<p class="PlaygroundEditorTheme__paragraph" dir="ltr"><span style="white-space: pre-wrap;">My ZipCode Question</span></p>',
        description: "",
        type: "ZIP_CODE",
        module: "Question",
        buttonLabel: "<strong>NEXT</strong>",
        value: {
          countryCode: "AZ",
          zipCode: "",
        },
        placeholder: "e.g. 123-456",
        settings: {
          questionAlignment: "flex-start",
          required: false,
          isCountryChangeEnabled: false,
          allowOtherZipCodes: false,
          defaultCountry: {
            countryCode: "IN",
            countryNumber: "91",
          },
          accessKey: "",
        },
        output: {
          schema: {
            schema: [
              {
                type: "object",
                schema: [
                  {
                    key: "response",
                    type: "object",
                    sample_value: {
                      countryCode: "AZ",
                      zipCode: "",
                    },
                    default: {
                      countryCode: "AZ",
                      zipCode: "",
                    },
                    path: ["response"],
                    pathStr: "{response}",
                    schema: [
                      {
                        key: "countryCode",
                        type: "string",
                        sample_value: "AZ",
                        default: "AZ",
                        path: ["response", "countryCode"],
                        pathStr: "{response}.countryCode",
                      },
                      {
                        key: "zipCode",
                        type: "string",
                        sample_value: "",
                        default: "",
                        path: ["response", "zipCode"],
                        pathStr: "{response}.zipCode",
                      },
                    ],
                  },
                ],
              },
            ],
            path: [],
            keys: [
              "{response}",
              "{response}.countryCode",
              "{response}.zipCode",
            ],
            flattened_schema: [
              {
                key: "response",
                type: "object",
                sample_value: {
                  countryCode: "AZ",
                  zipCode: "",
                },
                default: {
                  countryCode: "AZ",
                  zipCode: "",
                },
                path: ["response"],
                pathStr: "{response}",
              },
              {
                key: "countryCode",
                type: "string",
                sample_value: "AZ",
                default: "AZ",
                path: ["response", "countryCode"],
                pathStr: "{response}.countryCode",
              },
              {
                key: "zipCode",
                type: "string",
                sample_value: "",
                default: "",
                path: ["response", "zipCode"],
                pathStr: "{response}.zipCode",
              },
            ],
          },
        },
        last_updated: 1736944409081,
      },
      meta: {
        isMultiQuestionSupported: true,
        search_keys: [
          "Postal Code",
          "PIN Input",
          "ZIP Field",
          "Area Code",
          "Postcode Field",
        ],
      },
      location: "2144.999999999999 -2.1019476964872256e-45",
      warnings: [],
      errors: [],
      description: "My ZipCode Question",
      data: {
        schema: {
          schema: [
            {
              type: "object",
              schema: [
                {
                  key: "response",
                  type: "object",
                  sample_value: {
                    countryCode: "AZ",
                    zipCode: "",
                  },
                  default: {
                    countryCode: "AZ",
                    zipCode: "",
                  },
                  path: ["response"],
                  pathStr: "{response}",
                  schema: [
                    {
                      key: "countryCode",
                      label: "Country Code",
                      type: "string",
                      sample_value: "AZ",
                      default: "AZ",
                      path: ["response", "countryCode"],
                      pathStr: "{response}.countryCode",
                    },
                    {
                      key: "zipCode",
                      label: "Zip Code",
                      type: "string",
                      sample_value: "",
                      default: "",
                      path: ["response", "zipCode"],
                      pathStr: "{response}.zipCode",
                    },
                  ],
                },
              ],
            },
          ],
          path: [],
          keys: ["{response}", "{response}.countryCode", "{response}.zipCode"],
          flattened_schema: [
            {
              key: "response",
              type: "object",
              sample_value: {
                countryCode: "AZ",
                zipCode: "",
              },
              default: {
                countryCode: "AZ",
                zipCode: "",
              },
              path: ["response"],
              pathStr: "{response}",
            },
            {
              key: "countryCode",
              type: "string",
              sample_value: "AZ",
              default: "AZ",
              path: ["response", "countryCode"],
              pathStr: "{response}.countryCode",
            },
            {
              key: "zipCode",
              type: "string",
              sample_value: "",
              default: "",
              path: ["response", "zipCode"],
              pathStr: "{response}.zipCode",
            },
          ],
        },
      },
    },
  ],
};
