/**
 * Shared constants for Canvas Assistant
 */

export const SUGGEST_NEXT_BAR_TYPES = [
  "TRIGGER_SETUP_V3",
  "FORM_TRIGGER",
  "CUSTOM_WEBHOOK",
  "TIME_BASED_TRIGGER_V2",
  "SHEET_TRIGGER_V2",
  "HTTP",
  "TRANSFORMER_V3",
  "SELF_EMAIL",
  "CREATE_RECORD_V2",
  "UPDATE_RECORD_V2",
  "DB_FIND_ALL_V2",
  "DB_FIND_ONE_V2",
  "GPT",
  "GPT_RESEARCHER",
  "GPT_WRITER",
  "GPT_ANALYZER",
  "GPT_SUMMARIZER",
  "IFELSE_V2",
  "ITERATOR_V2",
  "DELAY_V2",
  "PERSON_ENRICHMENT_V2",
  "COMPANY_ENRICHMENT_V2",
];
