import { NODE_TEMPLATES } from "../../templates/nodeTemplates";
import { Globe, Download, Send, Shield, Upload, FileCode } from "lucide-react";
import { generateUUID } from "@/lib/utils";
import { HTTP_TYPE } from "../constants/types";

export const HTTP_NODE = {
  cmsId: "http",
  _src: "https://cdn-v1.tinycommand.com/1234567890/1742541365028/Http.svg",
  name: "HTTP Request",
  type: HTTP_TYPE,
  template: NODE_TEMPLATES.CIRCLE,
  background: "linear-gradient(196deg, #7D007D 2.15%, #C800C8 77.96%)",
  foreground: "#fff",
  dark: "#7D007D",
  light: "#C800C8",
  hasTestModule: true,
  canSkipTest: false,
  premium: true,
  meta: {
    search_keys: [
      "Curl",
      "Postman",
      "Api",
      "Url",
      "Get",
      "Post",
      "Put",
      "Request",
      "HTTP",
      "HTTP v2",
      "REST",
      "Fetch",
      "Webhook",
    ],
  },
};

export const THEME = {
  primaryButtonBg: "#7D007D",
  primaryButtonText: "#ffffff",
  iconBg: "rgba(125, 0, 125, 0.08)",
  iconBorder: "rgba(125, 0, 125, 0.15)",
  iconColor: "#7D007D",
  accentColor: "#7D007D",
  accentColorLight: "#C800C8",
};

export const HTTP_METHODS = [
  { value: "GET", label: "GET", color: "#22c55e", bgColor: "bg-green-500" },
  { value: "POST", label: "POST", color: "#3b82f6", bgColor: "bg-blue-500" },
  { value: "PUT", label: "PUT", color: "#f97316", bgColor: "bg-orange-500" },
  { value: "PATCH", label: "PATCH", color: "#eab308", bgColor: "bg-yellow-500" },
  { value: "DELETE", label: "DELETE", color: "#ef4444", bgColor: "bg-red-500" },
];

export const BODY_TYPES = {
  NONE: "none",
  FORM_DATA: "form-data",
  URL_ENCODED: "x-www-form-urlencoded",
  RAW: "raw",
  BINARY: "binary",
};

export const BINARY_SOURCE_UPLOAD = "upload";
export const BINARY_SOURCE_FORMULA = "formula";

export const FORM_DATA_ROW_TYPE_TEXT = "text";
export const FORM_DATA_ROW_TYPE_FILE = "file";

export const BODY_TYPE_OPTIONS = [
  { id: BODY_TYPES.NONE, label: "None" },
  { id: BODY_TYPES.FORM_DATA, label: "Form Data" },
  { id: BODY_TYPES.URL_ENCODED, label: "URL Encoded" },
  { id: BODY_TYPES.RAW, label: "Raw" },
  { id: BODY_TYPES.BINARY, label: "Binary" },
];

export const RAW_TYPES = [
  { id: "json", label: "JSON", contentType: "application/json" },
  { id: "text", label: "Text", contentType: "text/plain" },
  { id: "xml", label: "XML", contentType: "application/xml" },
  { id: "html", label: "HTML", contentType: "text/html" },
  { id: "javascript", label: "JavaScript", contentType: "application/javascript" },
];

export const AUTH_TYPES = {
  NONE: "none",
  BASIC: "basic",
  BEARER: "bearer",
};

export const AUTH_TYPE_OPTIONS = [
  { id: AUTH_TYPES.NONE, label: "No Auth" },
  { id: AUTH_TYPES.BASIC, label: "Basic Auth" },
  { id: AUTH_TYPES.BEARER, label: "Bearer Token" },
];

export const CONTENT_TYPE_HEADER = "Content-Type";

export const CONTENT_TYPES = {
  JSON: "application/json",
  FORM_DATA: "multipart/form-data",
  URL_ENCODED: "application/x-www-form-urlencoded",
  BINARY: "application/octet-stream",
};

export const TABS = {
  INITIALISE: "initialise",
  CONFIGURE: "configure",
  TEST: "test",
};

export const HTTP_TEMPLATES = [
  {
    id: "get-request",
    name: "GET Request",
    description: "Fetch data from an API endpoint",
    icon: Download,
    defaults: {
      method: "GET",
      url: { type: "fx", blocks: [], text: "" },
      headers: [],
      query_params: [],
      body: { type: BODY_TYPES.NONE, data: null },
      authorization: { type: AUTH_TYPES.NONE, data: null },
    },
  },
  {
    id: "post-json",
    name: "POST JSON",
    description: "Send JSON data to an API",
    icon: Send,
    defaults: {
      method: "POST",
      url: { type: "fx", blocks: [], text: "" },
      headers: [
        {
          key: CONTENT_TYPE_HEADER,
          value: { type: "fx", blocks: [{ type: "PRIMITIVES", value: CONTENT_TYPES.JSON }], text: CONTENT_TYPES.JSON },
          valueStr: CONTENT_TYPES.JSON,
          rowid: generateUUID(),
          autoGenerated: true,
        },
      ],
      query_params: [],
      body: {
        type: BODY_TYPES.RAW,
        data: { type: "fx", blocks: [], text: "" },
        sub_type: "json",
      },
      authorization: { type: AUTH_TYPES.NONE, data: null },
    },
  },
  {
    id: "auth-bearer",
    name: "Authenticated Request",
    description: "API call with Bearer token",
    icon: Shield,
    defaults: {
      method: "GET",
      url: { type: "fx", blocks: [], text: "" },
      headers: [],
      query_params: [],
      body: { type: BODY_TYPES.NONE, data: null },
      authorization: {
        type: AUTH_TYPES.BEARER,
        data: [{ key: "token", value: { type: "fx", blocks: [], text: "" }, valueStr: "" }],
      },
    },
  },
  {
    id: "file-upload",
    name: "File Upload",
    description: "Upload files using multipart form",
    icon: Upload,
    defaults: {
      method: "POST",
      url: { type: "fx", blocks: [], text: "" },
      headers: [],
      query_params: [],
      body: {
        type: BODY_TYPES.FORM_DATA,
        data: [
          {
            key: "file",
            value: "",
            valueStr: "",
            type: FORM_DATA_ROW_TYPE_FILE,
            fileData: null,
            rowid: generateUUID(),
            expand: false,
          },
        ],
      },
      authorization: { type: AUTH_TYPES.NONE, data: null },
    },
  },
  {
    id: "curl-import",
    name: "Import cURL",
    description: "Paste a cURL command to auto-configure",
    icon: FileCode,
    isCurlImport: true,
  },
];

export const getDefaultState = () => ({
  method: "GET",
  url: { type: "fx", blocks: [], text: "" },
  headers: [],
  query_params: [],
  body: { type: BODY_TYPES.NONE, data: null, sub_type: null },
  authorization: { type: AUTH_TYPES.NONE, data: null },
  output: {  },
  path_variable: { data: [] },
  _templateId: null,
  _isFromScratch: true,
});

export const METHOD_BODY_DEFAULTS = {
  GET: { showBody: false, defaultBodyType: BODY_TYPES.NONE },
  POST: { showBody: true, defaultBodyType: BODY_TYPES.RAW, defaultRawType: "json" },
  PUT: { showBody: true, defaultBodyType: BODY_TYPES.RAW, defaultRawType: "json" },
  PATCH: { showBody: true, defaultBodyType: BODY_TYPES.RAW, defaultRawType: "json" },
  DELETE: { showBody: true, defaultBodyType: BODY_TYPES.NONE },
};
