import React from "react";
import {
  Search,
  HeadphonesIcon,
  Plus,
  Undo2,
  Redo2,
  AlignLeft,
  AlignCenter,
  Folder,
  FolderOpen,
  Users,
  Heart,
  Star,
  Trash2,
  Type,
  Rocket,
  Puzzle,
  X,
  Maximize2,
  Minimize2,
  MoreHorizontal,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  Bell,
  Menu,
  Moon,
  Eye,
  EyeOff,
  Mail,
  FileText,
  HelpCircle,
  Info,
  AlertTriangle,
  Building2,
  Check,
  CheckCircle2,
  Share2,
  User,
  UserPlus,
  Pencil,
  MapPin,
  Clock,
  Save,
  Globe,
  LogOut,
  Grid,
  List,
  CornerDownLeft,
  Link,
  FolderInput,
  RotateCcw,
  Play,
  FileCheck,
  FileBox,
  Copy,
  Filter,
  Download,
  Calendar,
  Zap,
  Plug,
  Braces,
  XCircle,
  Scale,
  Table2,
  LayoutGrid,
  Megaphone,
  Store,
  MessageSquare,
  Variable,
  Receipt,
  CreditCard,
  Handshake,
  PlayCircle,
  Pause,
  ArrowLeft,
  CalendarClock,
  Sun,
  CalendarDays,
  CalendarRange,
  AlarmClock,
  CalendarCheck,
  Palette,
  Image,
  LayoutDashboard,
  ArrowLeftRight,
  Monitor,
  Smartphone,
  Move,
  GripVertical,
  ExternalLink,
  Settings,
  Crosshair,
  Bold,
  Italic,
  Circle,
  Square,
  RectangleHorizontal,
  Upload,
  AlignRight,
  BookOpen,
  ListOrdered,
  Bot,
  ImagePlus,
  Replace,
  Send,
  Sparkles,
  Volume2,
  File,
  FileImage,
  FileVideo,
  FileSpreadsheet,
  FileArchive,
  UploadCloud,
  CloudUpload,
  StopCircle,
  ZoomIn,
  ZoomOut,
  Twitter,
  Linkedin,
  Facebook,
  QrCode,
  AlertCircle,
  Diamond,
  LayoutTemplate,
  MessagesSquare,
  MessageCircle,
  Terminal,
  Database,
  Cpu,
  Workflow,
  Smile,
  Crown,
  ThumbsUp,
  Coffee,
  Trophy,
  KeyRound,
  Layers,
  RefreshCw,
  ClipboardList,
  GitBranch,
  Cable,
  Calculator,
  Newspaper,
  BotMessageSquare,
  Wrench,
  CircleDot,
  CirclePause,
  CircleAlert,
  Activity,
  TrendingUp,
  BarChart3,
  Users2,
  History,
  Share,
  Home,
  Cloud,
  CloudOff,
  Power,
  PowerOff,
  Loader2,
  LoaderCircle,
  Box,
  ArrowUp,
  ArrowDown,
  Command,
  WrapText,
  Lightbulb,
  CircleMinus,
  Shield,
  FileJson,
} from "lucide-react";
import type { LucideProps } from "lucide-react";

// Type for icon component
type IconComponent = React.ForwardRefExoticComponent<
  Omit<LucideProps, "ref"> & React.RefAttributes<SVGSVGElement>
>;

// Mapping of OUTE icon names to Lucide components
export const lucideIconMap: Record<string, IconComponent> = {
  // Core UI Icons
  OUTESearchIcon: Search,
  OUTEAddIcon: Plus,
  OUTECloseIcon: X,
  OUTETrashIcon: Trash2,
  OUTEEditIcon: Pencil,
  OUTEInfoIcon: Info,
  OUTEWarningIcon: AlertTriangle,
  OUTEDoneIcon: Check,
  OUTEHelpIcon: HelpCircle,
  OUTESettingIcon: Settings,
  OUTESaveIcon: Save,
  OUTESyncIcon: RefreshCw,
  OUTEClearIcon: XCircle,

  // Navigation Icons
  OUTEChevronLeftIcon: ChevronLeft,
  OUTEChevronRightIcon: ChevronRight,
  OUTEExpandMoreIcon: ChevronDown,
  OUTEExpandLessIcon: ChevronUp,
  OUTEArrowBackIcon: ArrowLeft,
  OUTEMenuIcon: Menu,
  OUTEMoreHorizIcon: MoreHorizontal,
  OUTEMoreVerticalIcon: MoreVertical,

  // File & Folder Icons
  OUTEFolderIcon: Folder,
  OUTEFolderOpenIcon: FolderOpen,
  OUTEDocumentIcon: FileText,
  // OUTEFormIcon: FileCheck,
  OUTEContentIcon: FileBox,
  OUTESheetIcon: Table2,
  OUTECopyContentIcon: Copy,
  OUTEMoveIcon: FolderInput,
  OUTEDownloadIcon: Download,
  OUTEUploadIcon: Upload,

  // Communication Icons
  OUTEEmailIcon: Mail,
  OUTEBellIcon: Bell,
  OUTEShareIcon: Share2,
  OUTEAnnouncementIcon: Megaphone,

  // User & People Icons
  OUTEPersonIcon: User,
  OUTEMembersIcon: Users,
  OUTEMemberIcon: User,
  OUTELogoutIcon: LogOut,
  OUTESupportAgentIcon: HeadphonesIcon,

  // View & Display Icons
  OUTEGridViewIcon: Grid,
  OUTEListViewIcon: List,
  OUTEOpenFullscreenIcon: Maximize2,
  OUTECloseFullscreenIcon: Minimize2,
  OUTEVisibilityOnIcon: Eye,
  OUTEVisibilityOffIcon: EyeOff,
  VisibilityOnOutlinedIcon: Eye,
  OUTEDarkModeIcon: Moon,
  OUTEDesktopIcon: Monitor,
  OUTEMobileIcon: Smartphone,

  // Action Icons
  OUTEPlayIcon: Play,
  OUTEPauseIcon: Pause,
  OUTEPlayCircleFilled: PlayCircle,
  OUTERestoreIcon: RotateCcw,
  OUTEUndoIcon: Undo2,
  OUTERedoIcon: Redo2,
  StopIcon: StopCircle,
  ZoomInIcon: ZoomIn,
  ZoomOutIcon: ZoomOut,

  // Location & Time Icons
  OUTELocationIcon: MapPin,
  OUTEClockIcon: Clock,
  OUTEScheduleIcon: CalendarClock,
  OUTEEventIcon: Calendar,
  OUTEGlobeIcon: Globe,
  OUTEGPSFixedIcon: Crosshair,

  // Formatting Icons
  OUTEBoldIcon: Bold,
  OUTEItalicIcon: Italic,
  OUTEFontIcon: Type,
  OUTELeftAlignIcon: AlignLeft,
  OUTECenterAlignIcon: AlignCenter,
  OUTEImageRightAlignIcon: AlignRight,
  OUTEImageLeftAlignIcon: AlignLeft,

  // Workflow & Integration Icons
  // OUTEWorkflowIcon: Workflow,
  OUTEWorkflowsIcon: GitBranch,
  OUTETriggerIcon: Zap,
  OUTEConnectionIcon: Plug,
  OUTEActionIcon: Zap,
  OUTEIntegrationIcon: Puzzle,
  OUTEIntegrationsIcon: Cable,
  OUTERuleIcon: Scale,
  OUTECurlyBracesIcon: Braces,
  OUTEFxIcon: Variable,

  // Mode Icons (Header V2)
  OUTEFormsIcon: ClipboardList,
  OUTEToolsIcon: Wrench,
  OUTECMSNewIcon: Newspaper,
  OUTEAgentsIcon: BotMessageSquare,

  // Business Icons
  OUTECorporateIcon: Building2,
  OUTEReceiptIcon: Receipt,
  OUTEPaymentIcon: CreditCard,
  OUTEHandshakeIcon: Handshake,
  OUTEMarketplaceIcon: Store,

  // Favorites & Reactions
  OUTEFavoriteIcon: Heart,
  OUTEHeartIcon: Heart,
  OUTEStarIcon: Star,
  OUTEInterestsIcon: Star,
  OUTESmileIcon: Smile,
  OUTECrownIcon: Crown,
  OUTEThumbUpIcon: ThumbsUp,
  OUTECupIcon: Trophy,
  OUTETrophyIcon: Trophy,

  // Image Icons
  OUTEImageIcon: Image,
  OUTEAddImageIcon: ImagePlus,
  ImageReplaceIcon: Replace,
  ImageIcon: FileImage,

  // Misc UI Icons
  OUTEFilterIcon: Filter,
  OUTEInsertLinkIcon: Link,
  OUTEEnterIcon: CornerDownLeft,
  OUTEDragIcon: GripVertical,
  OUTEJumpToIcon: ExternalLink,
  OUTEPaletteIcon: Palette,
  OUTECategoryIcon: LayoutDashboard,
  OUTESwapHorizontal: ArrowLeftRight,
  OUTERocketLaunchIcon: Rocket,
  OUTEExtensionIcon: Puzzle,
  OUTEResponseIcon: MessageSquare,
  // OUTECMSIcon: LayoutGrid,
  OUTEDeveloperGuideIcon: BookOpen,
  OUTEListAltIcon: ListOrdered,

  // AI & Tech Icons
  OUTEPromptIcon: Terminal,
  OUTEKnowledgeBaseIcon: Database,
  OUTEMemoryIcon: Cpu,
  SparkleIcon: Sparkles,
  SendIcon: Send,
  CheckIcon: Check,
  OUTECheckCircleIcon: CheckCircle2,
  OUTEDatabaseIcon: Database,

  // Status Icons (Header V2)
  OUTELiveIcon: CircleDot,
  OUTEPausedIcon: CirclePause,
  OUTEErrorIcon: CircleAlert,
  OUTEActivityIcon: Activity,

  // Metrics Icons (Header V2)
  OUTETrendingIcon: TrendingUp,
  OUTEMetricsIcon: BarChart3,
  OUTEResponsesIcon: Users2,

  // Action Icons (Header V2)
  OUTEHistoryIcon: History,
  OUTEShareNewIcon: Share,
  OUTEHomeIcon: Home,

  // Connection Icons (Header V2)
  OUTECloudIcon: Cloud,
  OUTECloudOffIcon: CloudOff,
  OUTEPowerIcon: Power,
  OUTEPowerOffIcon: PowerOff,

  // Utility Icons (Header V2)
  OUTELoaderIcon: Loader2,

  // File Type Icons (some have Lucide equivalents)
  AudioIcon: Volume2,
  DocIcon: File,
  VideoIcon: FileVideo,
  PdfIcon: FileText,
  XlsxIcon: FileSpreadsheet,
  ZipIcon: FileArchive,
  UploadFileIcon: UploadCloud,

  // Social Icons
  TwitterIcon: Twitter,
  LinkedInIcon: Linkedin,
  FacebookIcon: Facebook,
  QRCodeIcon: QrCode,
  MailIcon: Mail,

  // View Type Icons (for forms)
  CardViewIcon: LayoutTemplate,
  ChatViewIcon: MessagesSquare,
  ClassicViewIcon: MessageCircle,

  // CommandPalette Icons
  OUTECubeOutlineIcon: Box,
  OUTEAutoFixHighIcon: Sparkles,
  OUTEAutoAwesomeIcon: Sparkles,
  OUTELoopIcon: RefreshCw,
  OUTEAssessmentOutlinedIcon: FileCheck,
  OUTEWebhookIcon: Zap,
  OUTEWarningAmberIcon: AlertTriangle,
  OUTEEmailOutlinedIcon: Mail,
  OUTEInfoOutlinedIcon: Info,

  /* Formula bar / formula-fx */
  Lightbulb,
  MinusCircle: CircleMinus,
  Calendar,
  Settings,
  Table2,
  Box,
  Circle,
  Check,
  XCircle,
};

// Helper to get Lucide icon by OUTE name
export const getLucideIcon = (
  outeIconName: string,
  props?: LucideProps
): React.ReactNode | null => {
  const IconComponent = lucideIconMap[outeIconName];
  if (IconComponent) {
    return <IconComponent {...props} />;
  }
  return null;
};

// Check if a Lucide equivalent exists
export const hasLucideEquivalent = (outeIconName: string): boolean => {
  return outeIconName in lucideIconMap;
};

// Legacy export for backwards compatibility
export const icons = {
  search: Search,
  supportAgent: HeadphonesIcon,
  add: Plus,
  undo: Undo2,
  redo: Redo2,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  check: Check,
  chevronDown: ChevronDown,
  chevronsUpDown: ChevronsUpDown,
  chevronLeft: ChevronLeft,
  arrowLeft: ArrowLeft,
  x: X,
  checkCircle: CheckCircle2,
  clock: Clock,
  database: Database,
  fileText: FileText,
  // Mode icons
  clipboardList: ClipboardList,
  gitBranch: GitBranch,
  cable: Cable,
  newspaper: Newspaper,
  botMessageSquare: BotMessageSquare,
  wrench: Wrench,
  // Status icons
  circleDot: CircleDot,
  circlePause: CirclePause,
  circleAlert: CircleAlert,
  activity: Activity,
  info: Info,
  // Metrics icons
  trendingUp: TrendingUp,
  barChart3: BarChart3,
  calculator: Calculator,
  users2: Users2,
  // Action icons
  save: Save,
  rocket: Rocket,
  userPlus: UserPlus,
  history: History,
  share: Share,
  home: Home,
  // Connection icons
  cloud: Cloud,
  cloudOff: CloudOff,
  power: Power,
  powerOff: PowerOff,
  // Utility icons
  loader2: Loader2,
  loaderCircle: LoaderCircle,
  upload: Upload,
  sparkles: Sparkles,
  calendar: Calendar,
  refreshCw: RefreshCw,
  rotateCcw: RotateCcw,
  trash2: Trash2,
  // Tab icons
  palette: Palette,
  settings: Settings,
  image: Image,
  imagePlus: ImagePlus,
  layoutDashboard: LayoutDashboard,
  table2: Table2,
  // Embed icons
  braces: Braces,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  maximize2: Maximize2,
  minimize2: Minimize2,
  layoutGrid: LayoutGrid,
  layoutTemplate: LayoutTemplate,
  square: Square,
  layers: Layers,
  type: Type,
  messageCircle: MessageCircle,
  helpCircle: HelpCircle,
  monitor: Monitor,
  bookOpen: BookOpen,
  megaphone: Megaphone,
  copy: Copy,
  // Settings icons
  bell: Bell,
  globe: Globe,
  mapPin: MapPin,
  // Additional icons
  cloudUpload: CloudUpload,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  diamond: Diamond,
  mail: Mail,
  facebook: Facebook,
  linkedin: Linkedin,
  twitter: Twitter,
  list: List,
  qrCode: QrCode,
  share2: Share2,
  send: Send,
  link: Link,
  // Password visibility toggle (used by ODSTextField)
  edit: Pencil,
  pencil: Pencil,
  eye: Eye,
  eyeOff: EyeOff,
  keyRound: KeyRound,
  // MCQ / drag & add actions
  gripVertical: GripVertical,
  cornerDownLeft: CornerDownLeft,
  smartphone: Smartphone,
  move: Move,
  // Achievement/Award icons
  trophy: Trophy,
  // Text formatting icons
  wrapText: WrapText,
  shield: Shield,
  fileJson: FileJson,
  sun: Sun,
  calendarDays: CalendarDays,
  calendarRange: CalendarRange,
  alarmClock: AlarmClock,
  calendarCheck: CalendarCheck,
};
