import { QuestionType } from "@src/module/constants";

const QUESTION_NODES = Object.values(QuestionType);

const CONTROL_FLOW_NODES = [
  "HTTP",
  "IFELSE",
  "IFELSE_V2",
  "INTEGRATION",
  "TRANSFORMER",
  "IC_WORKFLOW",
  "GPT",
  "CREATE_SHEET_RECORD",
  "UPDATE_SHEET_RECORD",
  "DELETE_SHEET_RECORD",
  "FIND_ALL_SHEET_RECORD",
  "FIND_ONE_SHEET_RECORD",
  "CREATE_SHEET_RECORD_V2",
  "UPDATE_SHEET_RECORD_V2",
  "UPDATE_ONE_SHEET_RECORD",
  "DELETE_SHEET_RECORD_V2",
  "FIND_ALL_SHEET_RECORD_V2",
  "FIND_ONE_SHEET_RECORD_V2",
  "CREATE_RECORD_V2",
  "UPDATE_RECORD_V2",
  "DELETE_RECORD_V2",
  "DB_FIND_ALL_V2",
  "DB_FIND_ONE_V2",
  "DB_INSERT",
  "DB_FIND",
  "DB_FIND_ONE",
  "DB_UPSERT",
  "DB_UPDATE_MANY",
  "DB_DELETE_MANY",
  "DB_EXECUTE_QUERY",
  "MATCH_PATTERN",
  "SELF_EMAIL",
  "AGENT_WORKFLOW",
  "PERSON_ENRICHMENT",
  "EMAIL_ENRICHMENT",
  "COMPANY_ENRICHMENT",
];

const CONTENT_NODES = [
  QuestionType.WELCOME,
  QuestionType.ENDING,
  QuestionType.QUOTE,
  QuestionType.LOADING,
];

const NODES_WITH_ASYNC_TASK = [
  QuestionType.FILE_PICKER,
  QuestionType.SIGNATURE,
];

enum LOCALLY_EXECUTABLE_NODES {
  IF_ELSE = "IFELSE",
  IFELSE_V2 = "IFELSE_V2",
  TRANSFORMER = "Transformer",
  MATCH_PATTERN = "MATCH_PATTERN",
}

export {
  LOCALLY_EXECUTABLE_NODES,
  QUESTION_NODES,
  CONTROL_FLOW_NODES,
  CONTENT_NODES,
  NODES_WITH_ASYNC_TASK,
};
